### ISSUE TITLE
Link to the `symbols` branch in the "See also" readme section

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#1000]
This goes for all the repos.

**Comment by vulcandth** [comment]
You created this just to be the one to create #1000 didn't you. lol

**Comment by Rangi42** [comment]
![image](https://user-images.githubusercontent.com/35663410/187823921-2b6825e4-0895-4860-b1fb-d1712b0e6a46.png)

I'll get around to it later.
