### ISSUE TITLE
Rename `macros/wram.asm` to `macros/ram.asm`

### ISSUE THREAD

**Issue by vulcandth** [pret/pokecrystal#1001]
The macros in `macros/wram.asm` are, and will be used, in other ram locations.

**Comment by Idain** [comment]
In which locations are they being used?

**Comment by vulcandth** [comment]
> In which locations are they being used?

@Idain 
The following MACRO's are used elsewhere (there may be more)
`box` is used in sram.asm
`mailmsg` is used in wram.asm & sram.asm
`hall_of_fame` is used in wram.asm & sram.asm

And there will be plans to add more with the identification of the mobile code.

**Comment by Idain** [comment]
Interesting. I support the name change!
