### ISSUE TITLE
Add branch protection rule to `master` branch to prevent accidental deletion

### ISSUE THREAD

**Issue by vulcandth** [pret/pokecrystal#1007]
As the title says... I recommend adding a single branch protection rule to prevent accidental deletion of the `master` branch. This should never happen, and would almost have to be intentional... but I see little reason not to enable it... As its never needed, until it is needed.

Just a thought. What do you all think, @Rangi42 @mid-kid @dannye?

**Comment by Rangi42** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

I like the sound of these rules:

- Require pull request reviews before merging (as long as maintainers can approve their own PRs)
- Require status checks before merging (GitHub Actions CI's `make compare` must pass)
- Doesn't allow force pushes
- Doesn't allow deletions

**Comment by vulcandth** [comment]
Those are great too.. just didn't know how far you'd want to go with it.

**Comment by mid-kid** [comment]
I will "meh" very hard. I trust everyone with push access knows what they're doing, is already using PRs to pass CI and whatnot before pushing nontrivial changes, and etc. I've seen settings like forcing reviews cause more harm than good whenever people just aren't available and/or nontrivial changes are involved.

Furthermore, every one of us has a full copy of the repository. If things do go haywire, I expect disaster recovery to be fairly trivial. Personally I'm more prone to pushing commits I intended to PR than anything that requires `push --force` (the latter being useful to quickly undo mistakes).

**Comment by vulcandth** [comment]
I think for our repos the only rules that make sense to me are:

- Require status checks before merging (GitHub Actions CI's `make compare` must pass) [This can just help prevent merging a little to quickly after that *last push* to fix a minor thing. No reason not to ensure the `make compare` passes before merge.]
- Doesn't allow deletions [There is absolutely no reason to delete the `master` branch... so no reason to not prevent it. Only way this would happen is by *accident*? Would be very difficult to make the mistake.. but why not have the extra protection? I work in Cyber Security, and some pretty dumb things happen.. many of which are accidents... even from trusted professionals. Still easy enough to recover from one of our backups.. but still.]

The following don't make sense for us:
- Require pull request reviews before merging: (If we can approve our own PR's, then its pointless... especially when push directly if required. We are grown-ups, I think we are pretty good at communicating with each other and knowing when we need reviews.).
- Doesn't allow force pushes: (Although these should be avoided as much as possible, they are helpful to fix mistakes if we catch them soon enough. Having the option enabled would slow down the process)

I'd also like to state if any of these options become a problem, they can simply be toggled off. Even temporarily.

**Comment by mid-kid** [comment]
I guess status checks are fine if the github action only takes half a minute, though I often run `make compare` locally anyway. I guess in the latter event I can still merge manually instead of going through the PR interface, so that's fine.

I thought "allowing deletions" meant the same thing as force pushing, but if it's related to branch deletion then yeah it's fine to disallow that. If it's configurable then apply it to only master and symbols, we might have temporary branches in the future.

> If we can approve our own PR's, then its pointless...

I disagree with this setting, but you can configure it to require other people's reviews, or a minimum amount of reviews. But yeah, I've seen it go wrong in other pret repos where it ended up encouraging sloppy reviews or blockades as available reviewers were busy.

**Comment by vulcandth** [comment]
> If it's configurable then apply it to only master and symbols, we might have temporary branches in the future. 

Yeah that was the idea. It can be applied to only the `master` and `symbols` branch.

**Comment by vulcandth** [comment]
Sounds like we are at least in all agreeance about disallowing branch deletions; So if there are no further comments or concerns over the next week or so... i'll enable that single branch protection rule for `master` and `symbols` only and close this issue.

**Comment by vulcandth** [comment]
Enabled Branch protection rules for `pokecrystal` and `pokegolds`'s `master` and `symbols` branches to prevent branch deletion. 

If this is also desired for `pokered` someone else will need to do that as I do not have the permissions.
