### ISSUE TITLE
Bug: `_RunMobileScript` does not treat 0 as an out-of-bound index

### ISSUE THREAD

**Issue by bbbbbbbbba** [pret/pokecrystal#1024]
AKA [0x1500 control code arbitrary code execution](https://glitchcity.wiki/0x1500_control_code_arbitrary_code_execution).

https://github.com/pret/pokecrystal/blob/0f5540740bb494cfc6a5c724a2eeac4e064e9659/mobile/mobile_5f.asm#L3552-L3573

Since this checks for out-of-bound indices >= 0x10, the fact it doesn't check for 0 should almost certainly be considered a bug, not a design choice (plus, it makes sense for mobile scripts — things that are designed to be received externally — to be better sanitized).

Incidentally, it seems the ">= 0x10" check means that the last entry of the jump table would never be used, although this one may well be intended since it's the same function as the second-to-last entry. (While we are at it, we probably want to add 1 to the indices written after those jumptable entries, so that they match with the actual byte following 0x15, which undergoes `dec a` before being used to calculate the jumptable address.)

**Comment by Rangi42** [comment]
```diff
 _RunMobileScript:
 	ld a, [de]
 	inc de
 	cp "@"
 	jr z, .finished
+	and a
+	jr z, .finished
 	cp $10 ; jumptable size
 	jr nc, .finished
 	dec a
 	push de
 	ld e, a
 	ld d, 0
 	ld hl, .Jumptable
 	add hl, de
 	add hl, de
 	ld a, [hli]
 	ld h, [hl]
 	ld l, a
 	jp hl
```

**Comment by mid-kid** [comment]
Thanks for the report.
We don't document bugs that require external devices or modifications to trigger, and can't be triggered by sensible data edits either. This includes corruptions resulting from chaining other bugs (e.g. save resetting).
There's a *lot* of internal tables that have over- or underflow issues, as these never expect to be fed values sourced from places other than the game itself (or other connected games), and documenting all of these would significantly lower the signal-to-noise ratio of our bug documentation. We have to draw the line somewhere.
I hope you understand.
