### ISSUE TITLE
.gbcpal files should use `-c embedded`

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#1026]
```diff
 %.gbcpal: %.png
-	$(RGBGFX) -p $@ $<
+	$(RGBGFX) -c embedded -p $@ $<
```

This doesn't matter for pokecrystal's particular graphics, but might in hacks (see also https://github.com/pret/pokegold/issues/107).

**Comment by Idain** [comment]
It'd be good to be more consistent across repos, too. I like the idea.
