### ISSUE TITLE
Github Workflow `set-output` command is deprecated & disabled soon!

### ISSUE THREAD

**Issue by vulcandth** [pret/pokecrystal#1038]
The Github actions workflows are reporting the following error:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Supposedly `set-output` will be disabled May 31st 2023 according the the article https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I'm not as familiar with the workflows, and I don't exactly see where we are using the command... but someone should take a look.

You can see and example of the above warning by looking at the workflow `Update Symbols`.

Rangi/Pfero can one of ya'll take a look if you have time?

**Comment by Rangi42** [comment]
From https://github.com/EndBug/add-and-commit/issues/448:

> You're using an outdated version of `add-and-commit`
> Please upgrade to `v9`, where this issue has already been fixed.

**Comment by vulcandth** [comment]
Ah that makes sense.

Looks like we will need to do a bit more than just update the version, `branch` is no longer a valid input. I think we need to switch to the symbols branch first before running this now?

```
Warning: Unexpected input(s) 'branch', valid inputs are ['add', 'author_name', 'author_email', 'commit', 'committer_name', 'committer_email', 'cwd', 'default_author', 'fetch', 'message', 'new_branch', 'pathspec_error_handling', 'pull', 'push', 'remove', 'tag', 'tag_push', 'github_token']
```

**Comment by vulcandth** [comment]
Alright just confirmed on one of my other repo's the `branch` input is not necessary as we already have the correct branch checked out in the `cwd` : `./symbols` directory.
