### ISSUE TITLE
Fairy Type won't print

### ISSUE THREAD

**Issue by yoshi401** [pret/pokecrystal#1040]
I've added fairy type to my pokecrystal code following the tutorial, however, the type comes up as question marks in game instead of printing "Fairy". Not sure what the fix for this is.

**Comment by vulcandth** [comment]
Github issues are reserved for identifying problems, and improvements for the disassembly. We would be happy to assist you with any other general rom hacking help on our discord server: https://discord.gg/d5dubZ3
