### ISSUE TITLE
Fix definitions for `tempo_relative` and `new_song`

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#1043]
These unused commands have inaccurate macro definitions. `tempo_relative` takes a `bigdw \1 ; tempo adjustment` argument, but `Music_TempoRelative` only reads one signed byte. `new_song` also takes a `bigdw \1 ; id` argument, but `Music_NewSong` reads a little-endian two-byte music ID value. The macros should be updated accordingly.

**Comment by Idain** [comment]
I might make a PR to help.
