### ISSUE TITLE
Bad comment in RTC-checking code

### ISSUE THREAD

**Issue by aaaaaa123456789** [pret/pokecrystal#1059]
https://github.com/pret/pokecrystal/blob/1d64befdb7caf0db43f30810fb19fe5b1fba7786/engine/menus/main_menu.asm#L284

This code here checks for the RTC overflow bit, which gets set when the RTC day count exceeds _512_. However, since it is bit 6 of the control register, which also contains the upper portion of the day count, someone accidentally documented it as an actual check for $4000. (In actuality, bits 1-5 of that register are unmapped.)

This should just say it is checking whether the RTC overflow bit is set.

**Comment by mid-kid** [comment]
please consider making a PR instead

**Comment by aaaaaa123456789** [comment]
> please consider making a PR instead

This is my "I don't want to fork the repo while I'm doing 200 other things, but I don't want to forget about the issue" contribution :P

**Comment by mid-kid** [comment]
> I don't want to fork the repo while I'm doing 200 other things

Maybe you'll find some use in the Github CLI. I find that the `git clone` → make changes → `git commit` → `gh pr create` workflow is quite comfortable, it even forks the repo for you. It's so good that I literally only use `gh` for that command.
Alternatively, sometimes the web interface works for simple things.

**Comment by Rangi42** [comment]
This was fixed as part of https://github.com/pret/pokegold/pull/120, which will be ported to pokecrystal after review+merge.
