### ISSUE TITLE
Incorrect Mystery Gift decorations

### ISSUE THREAD

**Issue by SnorlaxMonster** [pret/pokecrystal#1082]
The names of the DECOFLAGs used for Mystery Gift decorations in [mystery_gift_decos.asm](https://github.com/pret/pokecrystal/blob/master/data/decorations/mystery_gift_decos.asm) are incorrect, and do not accurately reflect the decorations that can actually be sent in-game.

There's both a difference in order (which is important, as the order is used when determining which gift to send) and the contents of the lists.

The current list incorrectly includes two items that are instead purchased by Mom:
- Charmander Doll
- Pikachu Doll

The real list includes the following items, but they are missing from the current list:
- Big Lapras Doll
- Geodude Doll

For comparison, see [this writeup on Project Pokémon](https://projectpokemon.org/home/forums/topic/43930-mystery-gift-reverse-engineering-of-ir-protocol/) by bayleaf, who reverse-engineered the Mystery Gift protocol. And [this write-up on Blue Moon Falls](https://bluemoonfalls.com/pages/general/mystery-gift), which was recently updated with details of how Mystery Gift works with Stadium 2.

Additionally, the [MysteryGiftFallbackItem](https://github.com/pret/pokecrystal/blob/0b91f5c6569cff5c88698b455f353ba7d083b727/engine/link/mystery_gift_2.asm#L144) is currently listed as the Polkadot Bed, when according to bayleaf's research it should be the Red Carpet.

This issue was fixed in [this pokegold PR](https://github.com/pret/pokegold/pull/108) by @Tiddlywinkss (except the fallback item, which was not changed). However, that PR was submitted several months ago and has not yet been merged.

**Comment by mid-kid** [comment]
That PR solves this entire issue?
Yeah, that still has to be merged. Some accepted PRs linger for a while before someone bothers porting it to the other decomp as well. You can help out by submitting an equivalent PR to crystal.
I guess I'll do it for now.

**Comment by SnorlaxMonster** [comment]
Almost the entire issue. The one thing it doesn't fix is the fallback item, which should be the Red Carpet instead of the Polkadot Bed, according to bayleaf's research.

Unfortunately, I'm not entirely sure what the correct interpretation of that constant is. Only that it shouldn't be DECO_POLKADOT_BED, since it ultimately resolves to the Red Carpet.

**Comment by mid-kid** [comment]
Merged as of https://github.com/pret/pokecrystal/commit/b0ddb0758dd86950ad3c504aa09a4e3e2dffd495
Did that fix it?

**Comment by SnorlaxMonster** [comment]
> Merged as of [b0ddb07](https://github.com/pret/pokecrystal/commit/b0ddb0758dd86950ad3c504aa09a4e3e2dffd495) Did that fix it?

Not quite, it didn't fix the default decoration. I've just submitted pull request #1084 that fixes that as well. Merging that will fully resolve this issue.

**Comment by vulcandth** [comment]
resolved in https://github.com/pret/pokecrystal/commit/75f0ad395576700e57e7c10dbb4a954ea35ba27d
