### ISSUE TITLE
Support `-` for stdin and stdout in bpp2png and other tools

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#1083]
This would let you do things like `head -c 16 image.2bpp | tools/bpp2png - firsttile.png`, or `tools/bpp2png image.2bpp - | gm convert -resize 200% - zoomed.png`.

**Comment by mid-kid** [comment]
If you wanna go all the way, default to stdin/stdout when no filenames are passe.

**Comment by Rangi42** [comment]
bpp2png was the tool this would be most useful for, and it's no longer necessary since rgbgfx can reverse images itself.
