### ISSUE TITLE
The `list_start` macro should take a max string length for `li` to check

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#1086]
These macros are used for lists of move names, item names, trainer class names, etc. In most cases they have a maximum string length which would be convenient to enforce.

**Comment by vulcandth** [comment]
How should `li` handle: `li "# BALL"`? Should it try to expand out `#`?

**Comment by Rangi42** [comment]
Hmm. That might just make it not worth doing.

**Comment by vulcandth** [comment]
I'm worried that anything we do to try to expand it out, would mean a user might have the modify the macro if they change the control characters... furthermore if we don't expand it out, then it gives a false sense of safety. So I say lets not do this.
