### ISSUE TITLE
Sweet scent can still be used after being overwritten by a newly learned move 

### ISSUE THREAD

**Issue by gjpg** [pret/pokecrystal#1092]
I was farming encounters using sweet scent (via my level 17 Oddish). At level 18 I overwrote the move with sleep powder, but the sweet scent dialogue still triggers after encounters, allowing me to use it again indefinitely.

**Comment by vulcandth** [comment]
I was unable to reproduce this. Is this with a vanilla copy of Pokémon crystal? Or is this in a hack?

If its a clean pokecrystal that it happened in; do you have a save or something you can share? Have you used any cheats?

**Comment by gjpg** [comment]
Mistakenly submitted this on the wrong project, sorry.
