### ISSUE TITLE
Maybe add comments explaining that `stat_multipliers.asm` and `stat_multipliers_2.asm` are stored in different banks

### ISSUE THREAD

**Issue by Grate-Oracle-Lewot** [pret/pokecrystal#1119]
These two tables are identical, which is noted in their comments, but it's not explained why two identical tables are needed (it's because they're in different banks). Speaking from experience, this might lead someone to assume that one table could be deleted and the other reused, resulting in stats being modified based on garbage data. This is particularly insidious because it doesn't cause any build errors and isn't immediately obvious when playing, but in some cases it leads to infinite loops. Suffice to say that a short comment explaining the bank situation would have saved me a whole lot of trouble, and I'd like to save others that trouble.

**Comment by dannye** [comment]
Big fan of that.
