### ISSUE TITLE
Make a separate repo for helper scripts?

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#1145]
The tools/ folder is partly for tools necessary to build pokecrystal, which are all written in C. But it also contains various Python scripts that do little potentially-useful things, like removing duplicate tiles from an image, identifying duplicate frames in a Pokemon animation, fixing indexed palettes, adding address comments to assembly labels, etc.

I see a few problems with this status quo. Scripts get copied across all four repos (crystal, gold, red, yellow), since they're generally applicable. Updates to one need to get made everywhere, and sometimes get out of sync. Some repos just don't even have all the scripts. And they sort of clutter the directory and make it harder to see how few tools are actually needed. Plus some scripts aren't even really applicable, e.g. toc.py is more for the wiki than the actual code.

I'd like to make a separate "`pokeasmtools`" repo for these scripts. That way, it could have more dedicated documentation/explanation for each one, including INSTALL.md instructions on how to set up Python (which is irrelevant to building the actual ROMs).

Thoughts? @dannye @mid-kid @vulcandth (if anyone likes this suggestion but wants to bikeshed the repo name, feel free.)

**Comment by aaaaaa123456789** [comment]
Seems like a good idea to me!

**Comment by dannye** [comment]
Sounds fine to me. What about the non-essential non-python scripts? Like free_space.awk. And compare.sh has always bothered me (and compare2.sh??).

And is bpp2png.c actually necessary? Does it do anything that rgbgfx can't do? If it's not needed, then it maybe looks like lodepng isn't needed either.

I'd be in favor of removing anything that isn't strictly needed for building.

**Comment by Rangi42** [comment]
Yes, the .awk and .sh scripts would also be moved/consolidated. None of them are necessary for `make`ing the repos, and they're generally applicable to all disassemblies.

bpp2png.c was created before rgbgfx could reverse-convert images. I'll move or get rid of it once rgbds 0.9.0 releases with a lot of rgbgfx bugfixes.

**Comment by mid-kid** [comment]
This sounds ok to me. The only advantage to the current setup is that the tools will be more easily backed up if the repos get struck, but it's not a huge advantage either.

**Comment by Rangi42** [comment]
Sounds like it's time for <code>pokemon-<s>reverse-</s>engineering-tools</code> then! :3

**Comment by Rangi42** [comment]
Alright, https://github.com/pret/pokemon-asm-tools exists! It could use more documentation; see https://github.com/pret/pokemon-asm-tools/issues/1.

**Comment by Rangi42** [comment]
(I renamed this to [`gb-asm-tools`](https://github.com/pret/gb-asm-tools) since the scripts are useful for GB/GBC projects in general, and to reduce its ties to that trademark.)

**Comment by kanzure** [comment]
This is how it was 10 years ago, but it was changed for reasons I don't remember. We used a git submodule to share tools. There was pokemon-reverse-engineering-tools.git etc.

**Comment by aaaaaa123456789** [comment]
Basically because submodules suck and are confusing. People kept cloning the repo without submodules, etc.

**Comment by kanzure** [comment]
Ah, it was https://github.com/pret/pokemon-reverse-engineering-tools

**Comment by dannye** [comment]
The difference now is that the old submodule was primarily for rom-data-dumping tools, which are now pretty much entirely irrelevant, whereas the new gb-asm-tools is for useful optional utilities for (users of) the disassembly projects themselves.

The main goal/advantage of ditching the submodule is still valid -- tools required to build the project are still *directly* in the repo, not a separate repo/submodule.
