### ISSUE TITLE
Optional “build with Gold’s intro”

### ISSUE THREAD

**Issue by iimarckus** [pret/pokecrystal#212]
Have a way to replace the Suicune/Unown movie with the intro from G/S.

**Comment by yenatch** [comment]
Gold/Silver are different enough from Crystal that work on those games should be going toward [pokegold](https://github.com/pret/pokegold) instead.

**Comment by mid-kid** [comment]
Does this mean we should get rid of `CRYSTAL_` macros, or is it to be able to share files?

**Comment by yenatch** [comment]
Let's leave them for now until that data is in pokegold.

**Comment by yenatch** [comment]
pret/pokegold#4
