### ISSUE TITLE
easy_install is no longer part of python-setuptools

### ISSUE THREAD

**Issue by yenatch** [pret/pokecrystal#318]
why not

**Comment by kanzure** [comment]
seems to be mentioned in the docs for setuptools though? https://pypi.python.org/pypi/setuptools

**Comment by yenatch** [comment]
To my knowledge, this has not been fixed. This is preventing pypng from being installed.

pypng is on pip as well:
```bash
# linux
sudo apt-get install python-pip
```
```bash
# osx/windows
wget bootstrap.pypa.io/get-pip.py
python get-pip.py
```

Having to change dependencies all the time is a lot of trouble for pypng alone. We could distribute pypng as described in https://github.com/drj11/pypng/blob/master/README.md, or we could use rgbgfx instead.

**Comment by yenatch** [comment]
quick fix:
```bash
python <(lynx -source bootstrap.pypa.io/get-pip.py)
pip install pypng
```

**Comment by yenatch** [comment]
It seems to have been moved to `easy_install-2.7` (thanks @PikalaxALT).

while we're here, pip vs easy_install?

**Comment by kanzure** [comment]
Lately pip has been actually maintained, so I say pip.
