### ISSUE TITLE
Trouble getting large in-battle sprites working

### ISSUE THREAD

**Issue by Bynine** [pret/pokecrystal#327]
I've been putting custom sprites in the game, specifically right now the ones you see in fights and in the menu. I can get small, 40x40 sprites working fine if I compress them like this, then convert them to 2bpp.lz with gfx.py:

![image](https://cloud.githubusercontent.com/assets/15815916/11117617/2ad36dfc-8909-11e5-8b47-8a3789dfe00a.png) = ![image](https://cloud.githubusercontent.com/assets/15815916/11117618/32e62a8e-8909-11e5-85e8-4af53a6f1d4e.png)

However, larger sprites won't cooperate. I've been trying to put a 56x56 sprite in the game's 252nd slot, but it loads as a 48x48 (and so it gets all jumbled and not all of it loads.)

![image](https://cloud.githubusercontent.com/assets/15815916/11117675/cd4429be-8909-11e5-89a1-3cc13e9ed25d.png) = ![image](https://cloud.githubusercontent.com/assets/15815916/11117692/f5543a16-8909-11e5-91f4-2e021c7feb9a.png) = ![image](https://cloud.githubusercontent.com/assets/15815916/11117684/dedb305a-8909-11e5-8556-52084c5f6389.png)

(Note: I compressed it identically to Mantine's sprite, a 56x56 sprite.)

Any ideas on why this isn't working? Is there some part of the game's code I'm missing that determines the size of in-game sprites?

**Comment by Ketsuban** [comment]
The dimensions of the frontpic are stored as part of a Pokémon's [base stats](https://github.com/pret/pokecrystal/blob/master/data/base_stats.asm). Does that help at all?

**Comment by Bynine** [comment]
That's the ticket! I missed that when looking over the stats. Thanks much, friend!
