### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by SpriteMidr** [pret/pokecrystal#332]
I apologise if this is in the wrong place, I am just curious as to if this is a disassembly of Pokemon Crystal, how does posting the source as open source not infringe copyright laws for Nintendo?

Not being awkward or anything but I was just curious as to how the legal aspect of this would work.

Thanks

**Comment by Cfretz244** [comment]
I've actually also been wondering about this, and I've just been really hoping that it never becomes a problem.

**Comment by Cfretz244** [comment]
Because this is a really cool project.

**Comment by ashleyscopes** [comment]
I find it interesting. I am just  surprised either GameFreak or Nintendo have not taken it down yet. They are very protective of their content according to this page: https://www.nintendo.com/corp/legal.jsp . I am not moaning about this project at all, just interested on where it stands legally.

**Comment by Cfretz244** [comment]
Yeah, I mean, I guess it comes down the fact that a disassembly is essentially already publicly available. It's not as if the original source code had leaked online and was being hosted by this project. Anybody could, in theory, dump out the rom and perform a disassembly. They've just gone the extra step here and created an actual build process and added symbols.

**Comment by kanzure** [comment]
> how does posting the source as open source

There is no "open-source license" attached to the source code in the repository. For an overview of the definition of "open-source software" licensing, see: http://opensource.org/osd

**Comment by SpriteMidr** [comment]
It is still the equivalent of putting closed source code up for public access, which was my point. When I say open source, I meant that the source code is open to be viewed by the public. You still have not answered the question of how does this project stand legally.

**Comment by Kroc** [comment]
> It is still the equivalent of putting closed source code up for public access
No, it's reverse engineering for archival, educational and journalistic purposes -- which is covered under fair use laws. There is none of Nintendo's original source code in here, nothing. Nintendo's source code is locked up in a safe somewhere or possibly lost forever. Everything here has been built from scratch from reverse engineering the binary. ONLY the original binary is protected by copyright -- the fact that a bunch of text, independently created, processed via a computer algorithm can create the same binary output is inconsequential to copyright.

**Comment by wodim** [comment]
>ONLY the original binary is protected by copyright -- the fact that a bunch of text, independently created, processed via a computer algorithm can create the same binary output is inconsequential to copyright.

I will take a copyright-protected song, encode it in base64, and then say the same of it.

Also you did not "independiently create" this assembly text, you disassembled the original binary with a disassembly tool and then separated it into files and gave names to the labels, functions, variables, etc.

**Comment by SpriteMidr** [comment]
Okay! Awesome.
I was just looking for someone to explain it to me!
Thanks!
On 11 Jan 2016 12:22, Kroc Camen <notifications@github.com> wrote:
It is still the equivalent of putting closed source code up for public access
No, it's reverse engineering for archival, educational and journalistic purposes -- which is covered under fair use laws. There is none of Nintendo's original source code in here, nothing. Nintendo's source code is locked up in a safe somewhere or possibly lost forever. Everything here has been built from scratch from reverse engineering the binary. ONLY the original binary is protected by copyright -- the fact that a bunch of text, independently created, processed via a computer algorithm can create the same binary output is inconsequential to copyright.

**Comment by SpriteMidr** [comment]
Thank you for the clarification! :)
On 11 Jan 2016 13:44, wodim <notifications@github.com> wrote:
ONLY the original binary is protected by copyright -- the fact that a bunch of text, independently created, processed via a computer algorithm can create the same binary output is inconsequential to copyright.


I will take a copyright-protected song, encode it in base64, and then say the same of it.

Also you did not "independiently create" this assembly text, you disassembled the original binary with a disassembly tool and then separated it into files and gave names to the labels, functions, variables, etc.
