### ISSUE TITLE
Wild Encounter Error bug page doesn't lead to the right file

### ISSUE THREAD

**Issue by DogShrapnel** [pret/pokecrystal#340]
Just wanted to point out that on the Bugs and Glitches page, the ChoseWildEncounter does not lead to the proper section, either because the main.asm file is shorter than linked, or because the error is
not actually in the main.asm file anymore. This also applies to the ValidateTempMonSpecies section.

**Comment by JimB16** [comment]
I try to update the Links in the next days.
The reason I added some lines of code under the links was to find the place of the bug when it changes over time. I hope that works like I thougt it would.

**Comment by roukaour** [comment]
As of pull request #416 , the wiki pages are superseded by docs/\*.md files.
