### ISSUE TITLE
Some label semi-misnomers:

### ISSUE THREAD

**Issue by luckytyphlosion** [pret/pokecrystal#345]
Not much of an issue, just some things I noticed that should be changed:
- [x] GetMonFrontpic should be something more like "RequestEnemyFrontpic" as it only applies to the enemy and there are certain scenarios when the frontpic isn't needed (minimized, sub). This also applies to GetMonBackpic
- [x] FrontpicPredef should be renamed to something like "GetAnimatedFrontpic", and GetFrontpic should be renamed to "GetMonFrontPic"
- [x] CutAndPasteTilemap doesn't actually cut and paste the tilemap; it converts the 20x18 tilemap into a 32x18 tilemap so it can be HDMA'd.
- [ ] LoadEDTile is entirely errorneous, it should be something like "CopyTilemapAtOnce".

**Comment by yenatch** [comment]
LoadEDTile still needs to be fixed.
