### ISSUE TITLE
Can't compile the ROM

### ISSUE THREAD

**Issue by Toninformatica88** [pret/pokecrystal#348]
I'm using cygwin on a Windows 7 machine, with Python 2.7 installed. I tried to run the "make" command as soon as I downloaded the disassembly and I got this error:

`python gfx.py 2bpp gfx/misc/font_battle_extra.png
Traceback (most recent call last):      
File "gfx.py", line 6, in <module>      
    from extras.pokemontools import gfx, lz     
ImportError: No module named extras.pokemontools`     

I followed every step described inside the INSTALL.md file.

**Comment by yenatch** [comment]
```
git submodule update --init
```

**Comment by Toninformatica88** [comment]
Worked like a charm, thank you!
