### ISSUE TITLE
Recent versions of rgbds no longer creates matching binaries

### ISSUE THREAD

**Issue by FredrIQ** [pret/pokecrystal#356]
As of rgbds commit 1b05c43b979f8cc8c9bd571a7c96f13614724111 (this repository: github.com/rednex/rgbds ), the resulting binary of 'make' no longer match the actual binary.

Note that this repository links to another repo for rgbds, but it redirects to the above now. Also, not only is the result different, the resulting binary doesn't actually work (it runs but doesn't seem to respond to button input)

**Comment by Sanqui** [comment]
Looks like https://github.com/rednex/rgbds/commit/1b05c43b979f8cc8c9bd571a7c96f13614724111 was not backwards compatible by accident.

**Comment by Sanqui** [comment]
#358 fixes this.
