### ISSUE TITLE
Linking fails with error 'Section name "Audio" already in use'

### ISSUE THREAD

**Issue by Flameshadowxeroshin** [pret/pokecrystal#361]
This error occurred while attempting to compile an unmodified version of the current master version of the tree using the current master version of rgbds. The platform was Cygwin 2.8.
[makelog.txt](https://github.com/pret/pokecrystal/files/979588/makelog.txt)

**Comment by Flameshadowxeroshin** [comment]
This issue would be fixed by #360.

**Comment by yenatch** [comment]
Fixed by #389.
