### ISSUE TITLE
Building ROM with Cygwin with given instructions doesn't work?

### ISSUE THREAD

**Issue by MarkSill** [pret/pokecrystal#363]
Following the instructions, I installed Cygwin with default settings and marked `make`, `git`, and `gettext` for installation. (I later also installed `gcc-g++`, because that wasn't installed for some reason.)

`make tools` runs fine, but just regular `make` fails:

```
rgbgfx -p gfx/pics/bulbasaur/normal.gbcpal gfx/pics/bulbasaur/front.png
C:/cygwin64/usr/local/bin/rgbgfx.exe: error while loading shared libraries: libpng16-16.dll: cannot open shared object file: No such file or directory
make: *** [Makefile:101: gfx/pics/bulbasaur/normal.gbcpal] Error 127
```

I set up a fresh Linux VM and tested it out there and it worked just fine. Seems only building with Cygwin doesn't work, or maybe I didn't get something right.

**Comment by NieDzejkob** [comment]
try to install the `libpng` package or similar (the same way you did with `gcc-g++`)

**Comment by yenatch** [comment]
This is a problem with rgbgfx in the 0.2.5 release. The 0.3.1 binary works.

`gcc-g++` should not be required. I meant to add `gcc-core` and forgot, but annoyingly it doesn't look like it creates the `cc` alias.

**Comment by PikalaxALT** [comment]
Try getting `libpng16-devel`.

**Comment by MarkSill** [comment]
I don't know why I missed this in the error message, but it looks like the 0.2.5 release is missing the DLLs it's supposed to come with. Installing `libpng16-devel` didn't fix the problem (same error message), but copying over the DLLs from the 0.3.1 release works (as does the 0.3.1 release itself).
