### ISSUE TITLE
Compilation broken on macOS, due to reliance on md5sum

### ISSUE THREAD

**Issue by Ben10do** [pret/pokecrystal#364]
The Makefile currently depends on `md5sum`, a command line tool that is included in Linux. However, macOS instead includes the BSD `md5` tool, and as such, the resulting ROMs aren't compiled correctly (that is, their checksums are incorrect).

I can see two ways to resolve this:
1. Update the Makefile such that it will use `md5` if `md5sum` isn't installed. `md5 -r` produces checksums in a similar format to `md5sum` (though with one space between the checksum and filename, not two), and as such, shouldn't be tricky to use as a drop-in replacement for compilation. However, it doesn't have an equivalent of the `-c` flag, which may mean that more work is required to verify the checksums.
2. Ask macOS users (perhaps in INSTALL.md?) to use [Homebrew](https://brew.sh) to install `md5sum`, by running: `brew install md5sha1sum`. *For some reason though, it seems to require an extra installation of `openssl`, which seems a bit unnecessary IMO…*

The first option would be preferable, as it would require less to be installed for macOS users.

**Comment by yenatch** [comment]
What about `sha1sum -c`? Same problem?

As for the lz files, maybe it's best if the md5 is crc16 instead and it's just a --match flag in lzcomp.

**Comment by Ben10do** [comment]
Again, `sha1sum` isn't included, but `shasum` is. However, it uses SHA-1 by default (so no extra flags are needed), and it supports the `-c` flag, so it should be usable in-place.
```bash
$ shasum pokecrystal.gbc pokecrystal11.gbc > roms.sha1
$ cat roms.sha1 
f4cd194bdee0d04ca4eac29e09b8e4e9d818c133  pokecrystal.gbc
f2f52230b536214ef7c9924f483392993e226cfb  pokecrystal11.gbc
$ shasum -c roms.sha1 
pokecrystal.gbc: OK
pokecrystal11.gbc: OK
```

There don't seem to be any compatibility concerns with `sha1sum` that I can see:
```bash
$ sha1sum -c roms.sha1
pokecrystal.gbc: OK
pokecrystal11.gbc: OK
```
