### ISSUE TITLE
libsas123 ca-certificates? 

### ISSUE THREAD

**Issue by TrainMan471** [pret/pokecrystal#376]
Hey guys. I've been trying to build this but cant seem to. I am pretty sure it is because I am missing a dependency, but I have checked and everything seems to be there. iI think I need the libsas123 ca - certificates but I have no idea where to find them. Does anyone have any idea? I need them because gettext is not available.This is my output in the terminal:
Trainman471@Wabbafett ~
$ git clone https://github.com/pret/pokecrystal
Cloning into 'pokecrystal'...
remote: Counting objects: 42916, done.
remote: Compressing objects: 100% (427/427), done.
remote: Total 42916 (delta 318), reused 195 (delta 70), pack-reused 42419
Receiving objects: 100% (42916/42916), 30.92 MiB | 1.84 MiB/s, done.
Resolving deltas: 100% (27130/27130), done.
Checking out files: 100% (4638/4638), done.

Trainman471@Wabbafett ~
$ ls
pokecrystal

Trainman471@Wabbafett ~
$ cd pokecrystal

Trainman471@Wabbafett ~/pokecrystal
$ ls
audio          data      home.asm        macros.asm  README.md  unknown
audio.asm      engine    hram.asm        main.asm    roms.sha1  Vagrantfile
battle         event     includes.asm    Makefile    rst.asm    version.asm
compare.sh     extras    INSTALL.md      maps        sram.asm   vram.asm
compare2.sh    gbhw.asm  interrupts.asm  maps.asm    text       wram.asm
constants      gfx       items           menu        tilesets
constants.asm  gfx.py    lib             misc        tools
contents.asm   home      macros          predef      trainers

Trainman471@Wabbafett ~/pokecrystal
$ make
-bash: make: command not found

Trainman471@Wabbafett ~/pokecrystal
$ make pokecrystal.gbc
-bash: make: command not found

Trainman471@Wabbafett ~/pokecrystal
$ git make
git: 'make' is not a git command. See 'git --help'.

Did you mean one of these?
        blame
        merge
        stage

Trainman471@Wabbafett ~/pokecrystal
$ git grab
git: 'grab' is not a git command. See 'git --help'.

Did you mean this?
        grep

Trainman471@Wabbafett ~/pokecrystal
$ gettext
-bash: gettext: command not found

Trainman471@Wabbafett ~/pokecrystal
$ libsasL2-3
-bash: libsasL2-3: command not found

Trainman471@Wabbafett ~/pokecrystal
$ git submodule init
Submodule 'extras' (git://github.com/pret/pokemon-reverse-engineering-tools.git) registered for path 'extras'

Trainman471@Wabbafett ~/pokecrystal
$ git submodule update
Cloning into 'C:/cygwin64/home/Trainman471/pokecrystal/extras'...
Submodule path 'extras': checked out '2ae1ae2f19c842da965cd3db1b0da8bf108ac235'

Trainman471@Wabbafett ~/pokecrystal
$ easy_install pip
-bash: easy_install: command not found

Trainman471@Wabbafett ~/pokecrystal
$ git easy_install pip
git: 'easy_install' is not a git command. See 'git --help'.

Trainman471@Wabbafett ~/pokecrystal
$ git install python
git: 'install' is not a git command. See 'git --help'.

Did you mean this?
        instaweb

Trainman471@Wabbafett ~/pokecrystal
$ git install gcc
git: 'install' is not a git command. See 'git --help'.

Did you mean this?
        instaweb

Trainman471@Wabbafett ~/pokecrystal
$

**Comment by PikalaxALT** [comment]
Those must be obtained from the cygwin installer, in the same manner as by which you obtained `git`.

**Comment by yenatch** [comment]
```sh
$ make
-bash: make: command not found
```
From the install instructions, you need `make` and `gcc-core`. If they don't appear in the installer, try a different mirror. I've noticed some mirrors are missing common packages lately...

`libsasl2` and `ca-certificates` are only needed to make git work because of a mistake the cygwin maintainers made. It looks like git is working, so either they were installed by chance or the mistake was fixed and these packages (and `gettext`) are no longer needed. Installing `gettext` is just a workaround to get these two packages.

**Comment by roukaour** [comment]
This can probably be closed.

**Comment by yenatch** [comment]
It looks like the git dependencies were fixed in cygwin so `libsasl2-3` and `ca-certificates` are no longer needed. You may want to start over following [INSTALL.md](/INSTALL.md). Feel free to reopen if you still have trouble.
