### ISSUE TITLE
help decrypting pictures

### ISSUE THREAD

**Issue by TheRealPiggyWiggy** [pret/pokecrystal#377]
when i try doing this python gfx.py png gfx/pics/chikorita/front.5x5.2bpp.lz
i get this Traceback (most recent call last):
  File "gfx.py", line 5, in <module>
    import png
ImportError: No module named png

**Comment by einstein95** [comment]
Run png.py in the extras/pokemontools folder

**Comment by yenatch** [comment]
i assume you are using a fork since this is no longer necessary

if you have done `git submodule update --init` and still get this error, the fork is probably from before png.py was added to the submodule. you can get png.py from https://github.com/drj11/pypng:

```sh
lynx -source https://raw.github.com/drj11/pypng/master/code/png.py > extras/pokemontools/png.py
```

**Comment by TheRealPiggyWiggy** [comment]
i dont have a png.py

**Comment by TheRealPiggyWiggy** [comment]
im runnig windows 10

**Comment by roukaour** [comment]
This can probably be closed.

**Comment by yenatch** [comment]
If you're still trying to figure this out, reopen and let us know what fork you're using, or just use current pokecrystal.
