### ISSUE TITLE
Assembly takes a long time

### ISSUE THREAD

**Issue by i0brendan0** [pret/pokecrystal#378]
I'm not sure how long it's supposed to take with the new changes you've made since the last time I messed around with PokeCrystal, but I had Cygwin assemble PokeCrystal like over 2 hours ago (I could be exaggerating). It started out fine but I think it's going through compiling every single image. Did I probably do something wrong or is it normal this time around for it to take a while?

**Comment by yenatch** [comment]
Converting all the images is normal, but it should not take more than a few minutes at most. What are your specs?

**Comment by i0brendan0** [comment]
6 GB RAM, 2 GHz AMD 8 Processor. 64bit Cygwin. I was using a resource intensive program when I started but I shut that off when I realized how slow it was. Should I close out of Cygwin and try to remake Crystal?

**Comment by yenatch** [comment]
Probably. I've never heard of it going that slow.

**Comment by i0brendan0** [comment]
Think I got the problem resolved. Now instead of 10-20 seconds per image its like 2-5 in a second.

**Comment by i0brendan0** [comment]
Ok. This is terrible. Its been over an hour and it's still going. I removed the files from before and re-got them thinking that would clear things up as well but it's still taking quite a bit for each picture. I'll leave this closed but it's not taking minutes like yenatch said. It's not their fault, I'm not blaming them. Right now its doing a mix of rgbgfx -h -o and cp commands to gfx pics. Not sure how far a long that is but I almost could swear it's done them before. Idk. I'll let it sit.

**Comment by aaaaaa123456789** [comment]
Try using the `-j` switch. Using `-j 16` cuts down building time massively for me.

Disclaimer: native POSIX environment, not Windows

**Comment by i0brendan0** [comment]
I'm in windows. But I was thinking about the commands, could it be possible that the part of the commands that takes forever is the checking to see if the 2bpp file matches up with the png file? I doubt I will be changing any image file myself, and if I did and the case was that it took forever because of the matching, I would probably delete the 2bpp file so it would convert the new png and put it in. If that makes any sense. Also, after I closed out of it both times, my entire computer would run slowly, the task manager and file explorer especially. It was weird because I had nothing that was using up resources.

**Comment by PikalaxALT** [comment]
We're more concerned with whether the lz compressor is correct (spoiler: it isn't), but yes: it compares each lz file with its ground truth.

**Comment by i0brendan0** [comment]
Is there a way I can turn it off? So it will convert the images only if they aren't already assuming that they've been converted? And lets say I were to change an image, what files or something would I 'delete' so that it would re-convert when I went to make it?

**Comment by yenatch** [comment]
That's already how it works.

**Comment by yenatch** [comment]
```diff
-%.lz: hash = $(shell tools/md5 $(*D)/$(*F) | sed "s/\(.\{8\}\).*/\1/")
 %.lz: %
-	$(eval filename := $@.$(hash))
-	$(if $(wildcard $(filename)),\
-		cp $(filename) $@,tools/lzcomp $< $@)
-%.lz: hash = $(shell tools/md5 $(*D)/$(*F) | sed "s/\(.\{8\}\).*/\1/")
+	tools/lzcomp $< $@
```

**Comment by i0brendan0** [comment]
so take out the -red stuff and in its place put the +green stuff? And then see if it makes it go quicker?

**Comment by i0brendan0** [comment]
Thought I'd give an update. It's been over 30 minutes. Now its on tools/pokemon_animation -f for every pokemon. Each new line is taking a couple seconds. First it started out very well, but soon it slowed down and it makes my entire computer slow down, even after I close out of it. Almost like it gunks up the hard drive or something IDK. I have no idea is it's the compiling that slows everything down or Cygwin. I honestly can't even begin to imagine what the problem is. I can send you a dxdiag of my system to see if it is me and not the compiling. Coming from the last time I compiled PokeCrystal which didn't take but a few minutes.

**Comment by PikalaxALT** [comment]
I'd try running the following command in a Windows command prompt:

`chkdsk /scannow`

If it prompts you to reboot, do so.  Then wait for the computer to test the integrity of the hard drive, and report the results here.

**Comment by i0brendan0** [comment]
Says /scannow is an invalid parameter. Does it matter if I'm running Windows 8.1? o-o

**Comment by i0brendan0** [comment]
So I did /scan instead of /scannow because it didn't work of course. Not sure if this is a result you were looking for. 

C:\Windows\system32>chkdsk /scan
The type of the file system is NTFS.
Volume label is TI10690900F.

Stage 1: Examining basic file system structure ...

  806912 file records processed.

File verification completed.

  10326 large file records processed.

  0 bad file records processed.

Stage 2: Examining file name linkage ...

  976412 index entries processed.

Index verification completed.

  0 unindexed files scanned.

  0 unindexed files recovered.

Stage 3: Examining security descriptors ...
Security descriptor verification completed.

  84751 data files processed.
CHKDSK is verifying Usn Journal...

  37199000 USN bytes processed.

Usn Journal verification completed.

Windows has scanned the file system and found no problems.
No further action is required.

 721456127 KB total disk space.
 517183568 KB in 702254 files.
    395132 KB in 84752 indexes.
         0 KB in bad sectors.
   1127243 KB in use by the system.
     65536 KB occupied by the log file.
 202750184 KB available on disk.

      4096 bytes in each allocation unit.
 180364031 total allocation units on disk.
  50687546 allocation units available on disk.

**Comment by aaaaaa123456789** [comment]
Seems okay to me.

**Comment by i0brendan0** [comment]
I will say I finally got it to compile once. I stopped cygwin after like an hour I think. I had found that my AV software was getting upset that I left a file that I knew was fine alone. So I let it do its thing so it would stop whining and restarted my PC. I thought that was the problem considering it eats up resources When I started cygwin back up it finished very fast. So I'm letting it recompile a new set of files. But now I'm guessing it wasn't my AV. This problem is just terrible. And I have no idea why it's happening to me (not saying it SHOULDN'T happen to me)....

**Comment by i0brendan0** [comment]
So I've come to the conclusion that PokeCrystal is just going to take a while to compile for me. I've gotten past the whole figuring out if there's anything to help me and have been working on my own hack for a couple days. 
 
I would like to know if there is a place where I can get specific help with my PokeCrystal hack (The Celebi Event, picture questions, some other ASM related things). Like I said Pokecommunity is kinda slim on PokeCrystal hackers and I just need a few things. 
 
I am going to close this again as I don't think there's anything to help me. No one else has come forward with this problem and nothing has really helped me so far. I probably just need to get a new computer. So, thank you guys for your help. Can't wait to play my own PokeCrystal hack.

**Comment by yenatch** [comment]
Based on what you've said it sounds like the problem is your antivirus. One thing antivirus software especially hates is executables created by the user, such as the compiled programs in tools/. That could easily lead to much longer execution time. It should be faster after the first build at least.

There isn't a lot of documentation, but we are usually on [irc](https://kiwiirc.com/client/irc.freenode.net/?#pret) and [discord](https://discord.gg/cJxDDVP). You can also make another issue on github if that suits you, since lack of docs is arguably a bug.

**Comment by i0brendan0** [comment]
Yeah. I'm thinking that when I build the rom, I'll shut off my AV for the time being and then turn it on after.
 
I'd rather not clutter up github with hacking questions, I think it's best used for problems with PokeCrystal. But I might go to the discord.
