### ISSUE TITLE
What determines Fisher Guru's prize?

### ISSUE THREAD

**Issue by ltlynx** [pret/pokecrystal#391]
It can be an ether or an elixer, but I don't know what determines it.

**Comment by Pokechu22** [comment]
It seems like the relevant script is in LakeofRageMagikarpHouse.asm:

https://github.com/pret/pokecrystal/blob/77a98f2f44a72601b039982f8298a855cd2c5909/maps/LakeofRageMagikarpHouse.asm#L53-L62

I can't find any code that gives an Ether, which is odd.  (however, the wiki [does say](https://bulbapedia.bulbagarden.net/wiki/Fishing_Brothers#Lake_of_Rage_Fishing_Guru) it gives an ether...)

**Comment by Asday** [comment]
I seem to remember a speedrunner complaining about the inaccuracy of bulbapedia, I think it might have been Werster?  I wish I could find the video in which he says it.

I'd not worry too much if you can't find code for it.  The wiki can be wrong.

**Comment by i0brendan0** [comment]
Is it possible that in gen 4 it's an ether while bulbapedia didn't make the difference that gen 2 is an elixir.

**Comment by Pokechu22** [comment]
It's also possible that it's different in gold/silver.

**Comment by ltlynx** [comment]
Wow, Pokechu22, that's great! So, in Cristal, he only gives elixers. Do you know what happens in Gold/Silver? Because I think that I got an ether in Gold.
