### ISSUE TITLE
Mystery gift

### ISSUE THREAD

**Issue by ltlynx** [pret/pokecrystal#393]
I have two questions about mystery gift.
https://github.com/pret/pokecrystal/blob/master/constants/deco_constants.asm
https://github.com/pret/pokecrystal/blob/master/engine/decorations.asm
https://github.com/pret/pokecrystal/blob/master/engine/mysterygift.asm
https://github.com/pret/pokecrystal/blob/master/engine/mysterygift2.asm

1. How is even possible that sometimes I get a deco item I already own?
2. Are mystery gift received items data and room obtained items located at the same direction in the save? I mean... If I use gameshark in order to unlock the decoration items, is mystery gift data also changed?

Sorry if I bother you, I'm just interested in 100% finish my games and there is some data I can't find.

**Comment by i0brendan0** [comment]
I can tell you for a fact that there is no distinction between deco items recieved in game vs ones from mystery gift. It's all 1 list. Also a deco cheat is not going to affect mystery gift data unless the cheat is broken. As for the duplicate deco items thing, there is no check for the game whether mystery gift or not to decide when a gift has already been given. So you can receive the gift more than once.

**Comment by ltlynx** [comment]
I may have explained myself bad. I know the items get in the same list in terms of ingame playing, but I didn't know if there was a check saved apart for mystery gift or it was the same check for both ingame and mystery gift.
So... Are you sure that mystery gift doesn't check the owned decos? Because most of times I get items instead of decos (I own most of them) and exceptionally I get a repeated decoration.

**Comment by i0brendan0** [comment]
There's no separate save portion for mystery gift deco items and in game deco items. I'm not actually sure about the mystery gift part as I've never used it and don't know how to. I just made the mom buy all of the decorations in my hack.

**Comment by ltlynx** [comment]
How could I contact you for further information about that hack? XD
Then, I'll keep waiting for some information about mystery gift. Thanks for the answers.

**Comment by i0brendan0** [comment]
It's not released or in a stage where I want to release it.

**Comment by ltlynx** [comment]
Would you contact me then?

**Comment by i0brendan0** [comment]
Do you mean to get the thing I used to have mom buy all the items?

**Comment by ltlynx** [comment]
Also I would like to learn how it works, if you don't mind.

**Comment by i0brendan0** [comment]
`pokecrystal/events/mom_phone.asm` is where everything is.
Well it's basically a set of two tables.
```MomItems_1: ; fd136
	momitem      0,   600, MOM_ITEM, SUPER_POTION```
is how the first entry of the first table is. The first table its for recurring items that your mom will never stop buying.
`momitem` is just a macro for the compiler to use to write out the data. `0` is just a placeholder in this case so leave it 0. `600` is the amount of money that mom takes out of your savings when she buys it. `MOM_ITEM` is the type of thing she buys, for dolls it's `MOM_DOLL`. `SUPER_POTION` is what item she buys.
The first entry of the second table goes like this.
```MomItems_2: ; fd15e
	momitem    900,   600, MOM_ITEM, SUPER_POTION```
This table is for items that she buys when you have enough money in your account.
`momitem` macro again. `900` is how much money you need to have before she can buy that item. `600` is how much she spends. `MOM_ITEM` type of thing she buys again. `SUPER_POTION` again the item.
If you choose to add more items to the list, hold off on building the game until a specific pull request is finished. It will get rid of needing to count how many entries of each table their are.

**Comment by ltlynx** [comment]
Very interesting, thank you.

**Comment by roukaour** [comment]
This has been refactored to data/items/mom_phone.asm. Can the issue be closed?
