### ISSUE TITLE
Refactoring (restructuring?)

### ISSUE THREAD

**Issue by mid-kid** [pret/pokecrystal#401]
It's been a while since this project has been considered "done" by many.
Well, I don't really think so. There's still huge chunks of the code left undocumented and a lot of work left that should be done with it.
One of those tasks, I think, is refactoring. A bunch of people, including me, have voiced their concerns about the current state of the organization of files/code in the project. There's a bunch of files in single directories, a bunch of code in main.asm, and other such atrocities that really shouldn't be the case. Apparently this is mostly due to not being sure what goes where when you're still disassembling, but I think now's the right time to fix it for good.
Which leads me to opening this issue. In this issue I'm going to make a checklist of things that could/should be done to fix up the organization of code in this disassembly. I'll be ammending and changing things as they're suggested. You're encouraged to leave any suggestions in this thread.

The big cleanup list:
- [x] Remove all code from main.asm
- Rationale: main.asm should contain only INCLUDES for other files, and define some sections. This will make the file slightly smaller and it's purpose clearer.
- [x] Clean up single-file directories
- Rationale: There is no need to have a directory for a single file.
- [x] Split up the `battle` directory over `engine/battle` and `data/moves`
- Rationale: There is no real reason to have it on the top level.
- [x] Move all data structures to `data` https://github.com/pret/pokecrystal/issues/401#issuecomment-346923049
- Rationale: There's a bunch of easily-modifiable data that can be modified without ever touching any code. This data should be clearly defined as what it is.
- [x] Merge numbered files (like blockdata_N.asm)
- Rationale: Even if they get big, it's much easier to look for specific data in there.
- [x] Fix all the RAM label names. `vLabel` for vram, `wLabel` for wram, `sLabel` for sram.
- Rationale: This makes it a dead giveaway as to where the label belongs.
- [x] Rename some unclear and inaccurate things (see https://github.com/pret/pokecrystal/issues/396 and https://github.com/pret/pokecrystal/issues/412)
- Rationale: Names should make sense while staying as accurate as possible to the original source.
- [x] Change all file names to snake_case (e.g. `correcterrorsinplayerparty.asm`).
- [x] Rename some files to better names (particularly some of those long ones whose name comes directly from the label of the first function inside it).
- [x] Reorganize files inside `engine/` into folders, by category, so that specific content is easier to locate and there's no need to scroll through million files inside `engine/`. Probably same for `engine/events` and `engine/routines` too, and maybe inside `home/` as well.

**Comment by yenatch** [comment]
main.asm shouldn't have all the sections. it would take forever to build. that said, there are a bunch of compilation units buried in subdirectories, which need to be brought up to the top level.

**Comment by mid-kid** [comment]
I would also suggest reorganizing the maps into subdirectories, much like is being done in #386, but with a twist: The `maps` directory would contain `kanto`, `johto` and `shared`, as well as the asm files for the headers. Both `kanto` and `johto` would have a subdirectory for each city/noteworthy location, with the routes being on the top level.

**Comment by mid-kid** [comment]
Another suggestion: Clean up the top-level directory. Some directories, like items or trainers, can have their contents split over `engine`, `data` and `text`.

**Comment by roukaour** [comment]
pokered stores more in its data/ directory than pokecrystal, which makes it easier to find things.

Some content that could be moved to individual data/ files:

* engine/decorations.asm:DecorationAttributes, DecorationNames, and DecorationIDs
* engine/engine_flags.asm:EngineFlags
* engine/events_2.asm:ContestMons
* engine/events_3.asm:TreeMonMaps, RockMonMaps, TreeMons, and RockMons (similar to data/wild)
* engine/facings.asm (the whole thing, it's similar content to data/sprite_engine.asm)
* engine/fruit_trees.asm:FruitTreeItems
* engine/landmarks.asm:Landmarks
* engine/map_triggers.asm (the whole thing, it's just the MapTriggers table)
* engine/mysterygift2.asm:MysteryGiftItems and MysteryGiftDecos
* engine/npctrade.asm:NPCTrades
* engine/overworld.asm:SpriteMons and OutdoorSprites
* engine/phone.asm:PhoneContacts and SpecialPhoneCallList
* engine/save.asm:DefaultOptions
* engine/spawn_points.asm:SpawnPoints
* engine/sprites.asm:SpriteAnimSeqData
* engine/tmhm.asm:TMHMMoves
* engine/time_capsule/conversion.asm:KantoMonSpecials
* engine/time_capsule/conversion.asm:Pokered_MonIndices
* engine/wildmons.asm:RoamMaps
* event/happiness_egg.asm:ChangeHappiness.Actions
* event/mom_phone.asm:MomItems_1 and MomItems_2
* event/overworld.asm:CutTreeBlockPointers
* menu/mon_icons.asm:MonMenuIcons and IconPointers (the Icons INCBINs can go in gfx/)
* Most of items/ can go in data/items/; same goes for trainers/

Pretty much any data table which can have more entries safely inserted wherever, or which corresponds directly to a series of constants defined in constants/*.asm, seems appropriate for data/. (As opposed to tables that don't make sense outside of their code: engine/player_movement:DoPlayerMovement.data_8021e, jumptables of pointers, etc.) I'm iffy about very small data tables like engine/mart.asm:RooftopSaleData1. There's also data that people often want to edit but that's interspersed with code, like everything in engine/color.asm. And data that's not fixed-width, so it needs labels throughout it that the code refers to, like engine/unowndex.asm's UnownWords.

A few other quirks:

* Why the predef/ folder? Seems like these can just go in engine/.
* tilesets/roof.pal and tilesets/roof.asm are mapgroup-related data, not tileset-related.
* There are three maps/blockdata_N.asm files, one for each section, but all the script sections are in maps.asm. Tileset data is also split among tilesets/data_1-8.asm. This makes it more difficult to move data into different sections to fix bank overflow errors, and forces tools like crowdmap to assume there are exactly N data files for these things.
* gfx/misc should not exist.

**Comment by roukaour** [comment]
This is partly handled by pull request #411 . Many data tables have been moved into individual data/\*.asm files, but the overall file hierarchy still needs revising.

**Comment by roukaour** [comment]
@mid-kid progress update:
- "Remove all code from main.asm": done, as of #424
- "Clean up single-file directories": done
- "Split up the battle directory": I'll be doing this some time over the next week
- "Fix all the RAM label names": luckytyphlosion is doing this next
- "Rename some unclear and inaccurate things": done

**Comment by roukaour** [comment]
"Split up the battle directory over engine/battle and data/moves": done as of #437

**Comment by xCrystal** [comment]
May I add these three?

- Changing all file names to snake_case (e.g. ``correcterrorsinplayerparty.asm``).
- Renaming some file to a better name (particularly some of those long ones whose name comes directly from the label of the first function inside it).
- Reorganize files inside ``engine/`` in folders by category, so that specific content is easier to locate and there's no need to scroll through million files inside ``engine/``. Probably same for ``engine/events`` and ``engine/routines`` too, and maybe inside ``home`` as well.

**Comment by mid-kid** [comment]
Added them to the list, as they're pretty reasonable, so they should at least be attempted.

**Comment by Rangi42** [comment]
With #501 merged, this looks ready to be closed.
