### ISSUE TITLE
Explain the scripting language used in maps/

### ISSUE THREAD

**Issue by moonheart08** [pret/pokecrystal#402]
Exactly what it says on the tin. I can't find an explanation anywhere.

**Comment by yenatch** [comment]
Yeah documentation could use some work. The closest thing to a reference other than engine/scripting.asm is [this wiki page](../wiki/Event-scripting-commands), but it doesn't explain the premise.

**Comment by yenatch** [comment]
Actually, I guess the gold/silver compendium explains it relatively well. https://hax.iimarck.us/files/scriptingcodes_eng.htm We should probably adapt this document to pokecrystal since a lot of names have changed.

**Comment by roukaour** [comment]
Pull request #411 adds skeletons for `docs/scripting_commands.md` and `docs/map_scripts.md`, if anyone wants to fill those in with explanations and examples.

**Comment by Rangi42** [comment]
This isn't really a separate issue from "finish writing all the `docs/` files".
