### ISSUE TITLE
INSTALL.md should specify 64-bit Cygwin for Windows

### ISSUE THREAD

**Issue by roukaour** [pret/pokecrystal#407]
If you use 32-bit Cygwin (at least on 64-bit Windows 8.1), then rgbgfx will either build some 2bpp files incorrectly or crash with an "out of memory" error (depending on whether you use the win32 release of rgbds 0.3.2, the win64 release, or build rgbds yourself). After installing Cygwin64 this is no longer a problem.

**Comment by aaaaaa123456789** [comment]
Does this mean that 32-bit Windows users cannot build the ROM at all?

**Comment by roukaour** [comment]
I don't know if the issue was with Cygwin32's 32-bit libpng specifically, or something to do with the mismatch between 32-bit libpng and 64-bit Windows. Can anyone who still uses 32-bit Windows test it?

**Comment by roukaour** [comment]
This is handled by pull request #409 .
