### ISSUE TITLE
delete tileset 0 files

### ISSUE THREAD

**Issue by yenatch** [pret/pokecrystal#408]

**Comment by roukaour** [comment]
There are other unused ones:

* gfx/tilesets/02.png (tileset 02 shares 04.png)
* tilesets/30_collision.bin (tileset 30 shares 24_collision.bin)
* tilesets/30_metatiles.bin (tileset 30 shares 24_metatiles.bin)
* tilesets/32+33+34+35_collision.bin (they all share 36_collision.bin)
* gfx/tilesets/32+33+34+35+36.png (they all share 26.png)

**Comment by yenatch** [comment]
tileset 4 should probably be the one that's unused (`TILESET_BATTLE_TOWER_OUTSIDE`).

they should also be renamed to match the constants. this might make it more obvious which ones are shared once the duplicates are deleted

it looks like tileset 32 is unused but exists as a base for 33-36 (the ruins of alph puzzle room tilesets), so they should share 32_collision.bin

tilesets/data_*.asm should also be combined back into one file

**Comment by roukaour** [comment]
Combined tilesets/data_\*.asm in #411 . Haven't renamed them since crowdmap depends on numeric names (which it also does for the gfx/overworld/\*.png sprites).

**Comment by yenatch** [comment]
don't worry about crowdmap

**Comment by roukaour** [comment]
This is handled by pull request #411 .

**Comment by roukaour** [comment]
Already fixed, please close this.
