### ISSUE TITLE
Many banks are still hard-coded

### ISSUE THREAD

**Issue by roukaour** [pret/pokecrystal#413]
Some have comments which ought to have been used in the first place, e.g. `ld a, $5 ; BANK(UnknBGPals)`. Others are not commented, usually when they're loaded into `[rSVBK]`. Using relevant `BANK()` directives will make it easier for projects to move WRAM around, such as for allowing larger sprite animations or improving the map engine.

**Comment by mid-kid** [comment]
As an add-on to this: There's still a few hardcoded memory addresses hanging around, mostly pointing into WRAM. These should be assgned labels as well.

**Comment by mid-kid** [comment]
A lot of these were fixed in #460. What is the current status of this? Is there anything missing? If it's done, this issue should be closed.

**Comment by Rangi42** [comment]
Yeah, might as well close this. The remaining hard-coded banks are part of the larger problems of (a) hard-coded numbers in less-well-disassembled engine code, and (b) barely-disassembled-at-all mobile code.
