### ISSUE TITLE
Rename various "headers"

### ISSUE THREAD

**Issue by roukaour** [pret/pokecrystal#434]
These don't actually appear at the head of their respective entities. (Compare with musicheader and MapScriptHeader or MapEventHeader, which do.)

- data/emote_headers.asm: `emote_header`
- gfx/sprite_headers.asm: `sprite_header`
- data/pokemon/cry_headers.asm: `cry_header`
- maps/map_headers.asm: `map_header`
- maps/second_map_headers.asm: `map_header_2`
- battle/objects/gfx_headers.asm: `object_gfx`
- tilesets/tileset_headers.asm: `tileset`
- data/items/item_attributes.asm: `item_attribute`

Possible new terms:

- `def`
- `attribute`
- `metadata`

I think "def" or "metadata" works for the ones that are defined solely by their header, like emotes, and "attributes" for things like items, which have many different associated data tables.

(Or just call them by what they are, like "npctrade", "growth_rate", etc.)

**Comment by yenatch** [comment]
yeah i think the simple names are best, like `emote` `overworld_sprite` `pokemon_cry` `map` `map_data` `battle_object_gfx`, `tileset`, `item`

**Comment by roukaour** [comment]
Got it. `map` already exists, so maybe `map_(meta)data` and `map_(meta)data_2`, but the rest will work.
