### ISSUE TITLE
Rename pokemon animation files

### ISSUE THREAD

**Issue by yenatch** [pret/pokecrystal#439]
`anim0.asm` -> `anim.asm`
`anim1.asm` -> `anim_idle.asm`

**Comment by roukaour** [comment]
How about `anim.asm` and `anim_extra.asm`? Matches the top-level files.

**Comment by yenatch** [comment]
those should be renamed too. `appear`is not really a good name but i think `idle` makes sense

**Comment by roukaour** [comment]
anim and anim_idle, then? The main animation doesn't need clarification.

**Comment by yenatch** [comment]
sounds good
