### ISSUE TITLE
Rename and document menus

### ISSUE THREAD

**Issue by yenatch** [pret/pokecrystal#440]
- `MenuDataHeader` -> `Menu`
- `MenuData2` -> `MenuItems`
- figure out the purpose of each flag
- possibly use a macro to define menus
- docs/menus.md (see scripting compendium)
- `loadmenudata` -> `loadmenu`?

**Comment by roukaour** [comment]
With a name as short and generic as `Menu`, they'll also need more meaningful names. Like `.MenuDataHeader_Water` could be `.UnownWaterMenu`, but plenty of plain `.MenuDataHeaders` are left.

**Comment by mid-kid** [comment]
wMenuData2Flags (scrolling):
```
7: Select is functional
6: Start is functional
5: Run function 3 in the structure
4: Show arrows on the right-hand side
3: D-Left is functional
2: D-Right is functional
1: ?????
0: ?????
```

**Comment by roukaour** [comment]
`MenuDataHeader` is a header the same way `musicheader` is: it appears right before the actual data and contains some metadata. Simply renaming `MenuData2` to `MenuData` would make this clear, since there'd commonly be `MenuDataHeader`s containing a pointer to the subsequent `.MenuData`.

**Comment by Rangi42** [comment]
Renaming `MenuDataHeader` to just `Menu` would get confusing because `ThingMenu` is sometimes already a different Thing-menu-related concept, like a routine to draw the menu (example: `BattleMenu` and `BattleMenuDataHeader`).

**Comment by Rangi42** [comment]
Is anything left to be done regarding menus, or can this be closed?

**Comment by mid-kid** [comment]
Don't think so. Time to close.
