### ISSUE TITLE
Remove the `mobile` string equate

### ISSUE THREAD

**Issue by yenatch** [pret/pokecrystal#453]
`mobile` was used for stubbed mobile functions.

```asm
Example: mobile
    ...
```

What it should look like instead:
```asm
Example_Stubbed:
    ret
    ...
```

**Comment by mid-kid** [comment]
I'd prefer a prefix over a suffix.

**Comment by yenatch** [comment]
yeah, do whatever makes sense

**Comment by xCrystal** [comment]
There are three different cases to address: Unreferenced code, single ret functions that are still referenced (these are rare, but I've seen a few at some point), and the kind of stubbed functions mentioned above that may or may not be referenced. I'd probably handle the last two cases in a similar way (e.g. ``Stubbed_`` or ``CommentedOut_`` prefix/suffix), while for unreferenced functions that don't begin with ret I'd use ``Unreferenced_``.

Currently, there appears to be a mix of ``mobile``, ``; XXX`` and ``; unreferenced`` used to address any of those three cases indiscriminately.

**Comment by xCrystal** [comment]
``Label: mobile`` -> ``Stubbed_Label\n ret``.
``Label: ; unreferenced``, ``Label: ; Unreferenced`` and ``Label: ; XXX`` -> ``Unreferenced_Label`` where Label is ``Function1a2b3c`` or ``Data4d5e6f`` except maybe specific cases like the unreferenced predef ``Predef22``.
``; unreferenced``, ``; Unreferenced`` and ``XXX`` without label -> Same as above (create label).
``Unused_Label`` -> Same as above (change ``Unused_`` to ``Unreferenced_``).

Does this look good?

**Comment by yenatch** [comment]
Many unused labels are referenced. Some examples:
```
AI_Smart_Unused2B
CheckUnusedTwoDayTimer
CreditsUnusedCD21
ElmPhoneUnusedText
EnemyMonUnused
ForUnusedCursor
MapRoute34UnusedSignpostText
ReelAction_Unused
Route32CooltrainerMText_UnusedSproutTower
Special_CheckUnusedTwoDayTimer
sTrainerRankingUnused1
sTrainerRankingUnused2
sTrainerRankingUnused3
UnusedGuySpriteGFX
UnusedPhoneScript
UnusedPhoneText
UnusedSfx_Ch5
UnusedSfx_Ch6
UnusedSfx_Ch7
UnusedSfx_Ch8
UnusedTitleBG_GFX
UnusedTitleBG_Palettes
UnusedTitleBG_Tilemap
UnusedTitleFG_GFX
UnusedTitleFG_OAM
UnusedTitleFG_Palettes
wUnusedD102
wUnusedMovementBufferBank
wUnusedMovementBufferPointer
wUnusedPlayerLockedMove
wUnusedTwoDayTimer
wUnusedTwoDayTimerOn
wUnusedTwoDayTimerStartDate
```

I would say that a label should say unreferenced if it's not known what the data is (or it's a function), otherwise it should be unused.

**Comment by xCrystal** [comment]
Yeah, unconciously I was referring more to functions rather than data, jumptable entries or wram labels. Indeed, for those cases there will hardly be a single convention that can apply well to each of them, and most of them will probably look better with a single clean ``; unused`` comment (data), or a ``Unused`` prefix/suffix, which would be more accurate than ``unreferenced``.
