### ISSUE TITLE
Wrap unused code and data in `if _DEAD_CODE/endc`

### ISSUE THREAD

**Issue by roukaour** [pret/pokecrystal#462]
"Dead code" would mean anything that is totally unreferenced, so code that some lookup table points to is not dead even if it's never called. In other words, dead code is anything that could be overwritten with 0s without affecting the game.

This would serve two purposes: to document where dead code is without needing to maintain a parallel document, and to easily undefine `_DEAD_CODE` (maybe via version.asm, like `_CRYSTAL`) and build a smaller ROM. It also avoids the need for `Unused`/`Unreferenced` labels and `unused`/`unreferenced`/`XXX` comments.

(I'd suggest ending these blocks with `endc ; _DEAD_CODE` so both ends are easy to find.)

**Comment by yenatch** [comment]
sure (not version.asm though)

**Comment by roukaour** [comment]
Waiting for #456 and #459 to be merged before doing this.

**Comment by Rangi42** [comment]
This is more appropriate for a fork that optimizes/improves the code.
