### ISSUE TITLE
Move some gfx/ files into their relevant data/ subdirectories

### ISSUE THREAD

**Issue by roukaour** [pret/pokecrystal#463]
We have a top-level text/ directory, but it's not literally for all text: map scripts have their own text in maps/, tables of names and move+item descriptions are in data/, various small text strings go with their related code, etc.

We can do the same for gfx/. Some of the subdirectories have obvious counterparts in data/, and editing some *$thing* involves updating each file in data/*$thing*/ and gfx/*$thing*/.

Suggestions:

* gfx/battle_anims/ → data/battle_anims/gfx/
* gfx/emotes/ → data/emotes/ (goes with data/emotes.asm)
* gfx/footprints/ → data/pokemon/footprints/
* gfx/icon/ → data/icons/ (goes with data/icon_pointers.asm)
* gfx/pokemon/ → data/pokemon/pics/
* gfx/sprites/ → data/sprites/ (goes with data/sprites.asm)
* gfx/tilesets/ → alongside the other tilesets/ files, wherever they end up
* gfx/trainers/ → data/trainers/pics/

**Comment by yenatch** [comment]
in the japanese games text was mixed with code. in the localizations most text was replaced with `text_jump`/`TX_FAR`. text/ is an artifact of that

i dont think text/ is big enough to be justified. the remainder should be split up into data/ (or the reverse). i cant really think of any reasons to fragment gfx/

**Comment by roukaour** [comment]
Speaking of version.asm, `VERSION` appears to be left over from the G/S divide. The constant is only used for the `checkver` command; and that command is only used in BillsHouse.asm to ask about Growlithe or Vulpix. Gold asked about Growlithe, Silver about Vulpix; and Crystal was based on Gold (see: default rival name, leftover OAM data for title screen Ho-Oh, etc). And in fact `checkver` [returned](https://hax.iimarckus.org/files/scriptingcodes_eng.htm#Marke18) 0 in Gold and 1 in Silver.

Anyway: can this constant be relocated and renamed so its meaning is more clear? Something like `SILVER_VERSION` or `GS_SILVER`, and treated like other "leftover" constants (`SAFARI_BALL`, `MOON_STONE_RED`, `SPRITE_ANIM_INDEX_GS_INTRO_SPARKLE`, etc). Right now it looks related to the different release versions of Crystal itself.

(This would leave `_CRYSTAL EQU 1` as the only content of version.asm, but IMO that should be moved directly into includes.asm—or whatever it gets called—and version.asm eliminated just like constants.asm.)
