### ISSUE TITLE
VRAM labeling is incomplete

### ISSUE THREAD

**Issue by TheMostCuriousThing** [pret/pokecrystal#466]
[`vram.asm`](https://github.com/pret/pokecrystal/blob/master/vram.asm) defines labels generic to the GBC, with no information specific to pokecrystal.

These labels are offset by the [`tile` string](https://github.com/pret/pokecrystal/blob/master/macros.asm#L25), `+ LEN_2BPP_TILE *`. This allows tile offsets to be written as tile coords—for example, `vTiles0 tile $73` is seven tiles "down" & three tiles "right" from the start of the first part of the tilemap.

VRAM is also offset by the [`bgcoord` macro](https://github.com/pret/pokecrystal/blob/master/macros/coords.asm#L18).

This rabbit hole potentially goes much deeper, since the same principles used to label VRAM could label offsets into (for example) [WRAM's `TileMap`](https://github.com/pret/pokecrystal/blob/master/wram.asm#L325), which itself is referenced by the [`coord` macro](https://github.com/pret/pokecrystal/blob/master/macros/coords.asm#L5).

*However*, in many cases, hardcoded [tile] coords are either a) single-use, or b) more intuitive as numbers than labels/constants defined elsewhere. As a result, the scope of this issue is hard to pin down.

**Comment by Rangi42** [comment]
Filling vram.asm with feature-specific labels would be more cumbersome than the current solution, offsets to six main labels. When or if rednex/rgbds#201is resolved, we can replace the `tile` macro (not to mention other improvements, like replacing `coord`, `maskbits`, etc.)
