### ISSUE TITLE
Possibly rename some tilesets

### ISSUE THREAD

**Issue by roukaour** [pret/pokecrystal#467]
* `house_1` → `house` (the others are `players_house` and `kurts_house`)

or:

* `kurts_house` → `house_2` (it's used for many "traditional" houses in Violet and Ecruteak)

---

* `gym_1` → `gym` (other Gyms also use `train_station` and `olivine_gym`)

or:

* `train_station` → `gym_2` (it's only used for `CeladonGym`, `ViridianGym`, `FightingDojo`, and `GoldenrodMagnetTrainStation`, and `SaffronTrainStation`)
* `olivine_gym` → `gym_3` or `lances_room` (it's only used for `OlivineGym`, `GoldenrodBikeShop`, and `LancesRoom`)

---

* `power_plant` → `facility` (like pokered) (it's used for `PowerPlant`, `RuinsOfAlphResearchCenter`, `TeamRocketBaseB2F`, `TeamRocketBaseB3F`, `TrainerHouseB1F`, `SilphCo1F`, and `MrPokemonsHouse`)

**Comment by xCrystal** [comment]
Positive about the changes. Better to have a generic name than a more specific but only partly inclusive name.

**Comment by roukaour** [comment]
Any preference for which changes?

**Comment by xCrystal** [comment]
``house_1``, ``house_2``, ``gym_1``, ``gym_2``, ``gym_3``, and ``facility``. Sorry, I didn't even notice the other alternatives.

**Comment by roukaour** [comment]
Other misnomers:

- `game_corner`: GoldenrodGameCorner, CeladonGameCorner, OlivineCafe, CeladonCafe, VermilionGym, SafariZoneMainOffice
- `gym_1`: VioletGym, AzaleaGym, GoldenrodGym, MahoganyGym, BlackthornGym, WillsRoom, KogasRoom, BrunosRoom, KarensRoom
- `lab`: ElmsLab, OaksLab, EarlsPokemonAcademy, FuchsiaGym, DragonShrine
- `lighthouse`: OlivineLighthouse, FastShip
- `power_plant`: `facility`
- `sprout_tower`: SproutTower, BurnedTower1F, TinTower, EcruteakGym, CianwoodGym, PewterGym
- `underground`: GoldenrodUndergroundWarehouse, GoldenrodDeptStoreB1F, TeamRocketBaseB1F, OlivinePortPassage, VermilionPortPassage, UndergroundPath, SaffronGym
- `whirl_islands`: DarkCave, MountMortar, WhirlIslands, RockTunnel, SilverCaveRoom1

Also, there's `TILESET_PARK` and `TILESET_ILEX_FOREST`; should either be `TILESET_NATIONAL_PARK` or `TILESET_FOREST`.

**Comment by mid-kid** [comment]
[7:53 PM] p-p-pfero: `kurts_house` >>>> `house_2`.
[7:53 PM] p-p-pfero: `train_station` >>>> `gym_2`.
[7:53 PM] p-p-pfero: Basically, don't do numbers in filenames, they're forgettable
[7:54 PM] p-p-pfero: As for the tilesets that are used in different totally unrelated places, their most notable or otherwise differentating place is good as a name.
[7:55 PM] p-p-pfero: So basically the first option for all of the 3 things you mentioned is fine, and maybe `olivine_gym` → `bike_shop`.
