### ISSUE TITLE
More local constants for jumptable indexes

### ISSUE THREAD

**Issue by roukaour** [pret/pokecrystal#468]
engine/pokegear.asm already has `DEXSTATE_` constants for its jumptable of possible states. #456 adds some for the pack, stats screen, trainer card, and trade animations; however, there are probably more interfaces that would benefit from state constants.

**Comment by mid-kid** [comment]
How far are we into this? Can this be quantified?
I see a lot of places where this is already done correctly, but I'm not sure if that's all of them.
Can we make a list of the missing ones? If not, I don't really see a point to the issue.

**Comment by Rangi42** [comment]
This is an open-ended principle for future code refactoring, so it's addressed [on the wiki](../wiki/Code-cleanup).
