### ISSUE TITLE
Rename _Special_BugContestJudging to _BugContestJudging in PR #456

### ISSUE THREAD

**Issue by xCrystal** [pret/pokecrystal#473]
This targets #456 after it merged #459

``_Special_BugContestJudging`` is not an ``special``, but was accidentally edited when renaming ``BugContestJudging`` to ``Special_BugContestJudging``. Therefore, ``_Special_BugContestJudging`` should be renamed to ``_BugContestJudging``.

Also ``HOF_Predef_AnimateFrontpic`` should be renamed to ``Predef_HOF_AnimateFrontpic`` for consistent prefix order.

**Comment by roukaour** [comment]
Done and done. Note that for PR-specific issues you can comment directly on the problematic lines.
