### ISSUE TITLE
Code inside gfx/

### ISSUE THREAD

**Issue by xCrystal** [pret/pokecrystal#474]
``gfx/load_pics.asm`` and the code inside ``gfx/overworld_font.asm`` should probably be moved to ``engine/`` to make the ``gfx/`` directory contain only graphics and their respective ``INCLUDE``s. 

For example, ``gfx/mail.asm`` contains the ``INCLUDE``s to files inside ``gfx/mail/`` but the code to load the graphics is at ``engine/mail_2.asm``. Idem for ``gfx/icons.asm``, ``gfx/sprites.asm``, etc.

**Comment by roukaour** [comment]
Done; load_pics.asm, font.asm, overworld_font.asm, and fishing.asm all had some code.
