### ISSUE TITLE
EVENT_GAVE_KURT_APRICORNS and the EVENT_DRAGON_SHRINE_QUESTION_2 are misnamed

### ISSUE THREAD

**Issue by surskitty** [pret/pokecrystal#481]
They're used by the Goldenrod Underground, the Dragon Shrine, the Fast Ship SS Aqua, and the Bug Catching Contest.

**Comment by Rangi42** [comment]
They should have generic names like `EVENT_LOCAL_1` to `EVENT_LOCAL_8`. ("The first eight flags are reset upon reloading the map.")
