### ISSUE TITLE
Move some gfx/*.asm files elsewhere

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#483]
- [gfx/footprints.asm](/pret/pokecrystal/blob/master/gfx/footprints.asm) → data/pokemon/footprints.asm
- [gfx/icons.asm](/pret/pokecrystal/blob/master/gfx/icons.asm) → data/pokemon/menu_icons.asm

Both of these files contain fixed-size 2bpps that are treated as an array, and fetched with an offset times their corresponding constant. The gfx/footprints.asm entries correspond to Pokémon ID constants, just like other data/pokemon/ tables; and menu_icons.asm corresponds to the `ICON_*` constants.

- [gfx/tilesets.asm](/pret/pokecrystal/blob/master/gfx/tilesets.asm) → data/tileset_data.asm

This is not just graphics: it contains Collision, Metatiles, and GFX INCLUDEs/INCBINs.

- [gfx/pokemon/\*.asm](/pret/pokecrystal/blob/master/gfx/pokemon/) → data/pokemon/anims/\*.asm (like [Polished Crystal](/Rangi42/polishedcrystal/tree/master/data/pokemon/anims))

**Comment by mid-kid** [comment]
`gfx/load_pics.asm` → `engine/load_pics.asm` (unless we can make an `engine/gfx/` with multiple files)

But I honestly don't see the point of moving files that do nothing more than listing the contents of `gfx/` into `data/`. I know pic_pointers have already moved, but still.

**Comment by Rangi42** [comment]
Most other graphics INCBINs are close to their related code (e.g. gfx/evo/bubble.2bpp in engine/evolution_animation.asm), so there's no question about where to put them. Similar to how most text is mixed together with its code.

Isolated groups of related graphics INCBINs are an exception to the rule. Again, that's similar to text: the Pokédex entries are on their own, and even get their own .o file.

However, the isolated text groups aren't all in text/ or even in data/text/; that's just for the generic ones. Pokédex entries go in data/pokemon/dex_entries/\*.asm, item descriptions in data/items/descriptions.asm, etc.

I think the same applies to the isolated graphics groups. They behave similarly to tables of pointers, in that you update them in sync with the tables and other data files. And the only rule for which INCBINs get a top-level gfx/\*.asm file seems to be "if there are a lot of them at once". The bottom of engine/slot_machine.asm could be moved into gfx/slots.asm, but there'd be no reason to.

And regardless of whether we leave a few asm files gfx/ or move them into data/, there shouldn't be any actual code in them (that goes for gfx/font.asm and gfx/mail.asm).

**Comment by mid-kid** [comment]
I'd still go as far as to say at least gfx/pics.asm and gfx/sprites.asm need to stay, as they're essentially isolated graphics banks. I'd argue gfx/font.asm should stay, too, since it's another generic place for graphics of all kinds.

Yes, all of this despite the fact that data/common_text/ exists. Why? Because gfx/ are huge and often very closely-related, much unlike text, which was probably separated later down the line to make localization easier.

**Comment by Rangi42** [comment]
Okay so let's make exceptions for them, and move the two with asm code into engine/. That leaves five files. The two I particularly think belong in data/ are footprints.asm and icons.asm, because they have fixed-size files that are accessed via offsets to an initial pointer. That makes them data as much as gfx. Compared to sprites.asm or even emotes.asm, which aren't necessarily organized in any way.
