### ISSUE TITLE
Use new features of rgbds 0.3.7

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#485]
New features to apply throughout the code:

- `~` works for bytes, so we can do `~X` instead of `$ff ^ X`
- `HIGH()` and `LOW()` work for constants
- `BANK(@)` gets the current bank; `BANK("Section Name")` is also valid (some labels can thus be removed)
- `\` continues lines, like in C or Python, which could help clean up long macros (`trainer`, `npctrade`) and implement new ones (like for data/trainers/attributes.asm or data/pokemon/base_stats/\*.asm)
- rgbgfx adds "support for colored images"

**Comment by aaaaaa123456789** [comment]
The syntax for the current bank is `BANK(@)`, not `BANK()`.

The rationale behind this is that `BANK()` would have been new syntax, while `BANK(@)` is just the same syntax as for any other symbol.

**Comment by Rangi42** [comment]
This is an open-ended principle for future code refactoring, so it's addressed [on the wiki](../wiki/Code-cleanup).
