### ISSUE TITLE
Rename ENGINE_BUG_CONTEST_ON

### ISSUE THREAD

**Issue by SatoMew** [pret/pokecrystal#490]
This flag is used by Japanese Crystal to hide the Mobile menu and Mobile Stadium entries on the main menu before Elm receives the Mystery Egg (the Mobile System GB's activation status isn't reset on freshly created save files that overwrite old ones, only when the save data is deleted from the title screen).

I propose the name `ENGINE_MAIN_MENU_MOBILE_HIDDEN` as it is not used anywhere else.

https://github.com/pret/pokecrystal/blob/82a05a1752b476caab8951fe03f539dcc1a63669/constants/engine_flags.asm#L25
https://github.com/pret/pokecrystal/blob/b35eb72290b964b98844afbe741bb7ede34b9ef3/maps/ElmsLab.asm#L343

**Comment by Rangi42** [comment]
PR #476 introduces a `STATUSFLAGS_BUG_CONTEST_ON_F` constant that will also need renaming if this is done.

**Comment by SatoMew** [comment]
@Rangi42 To clarify my choice of words: from the player's perspective, if they go to the main menu and start a new game, they will be presented with the Mobile System GB Mobile Profile screen instead of the gender choice screen but their access to the mobile features on the main menu is restricted until they fulfill the requirement.

Thus, the flag is used to artificially hide the entries from the player despite the Mobile System GB being activated; if it's not (because it's their first playthrough, they deleted the old save file, or do not have a Mobile Adapter GB), then setting the flag is irrelevant because the entries will still be hidden, as is the case in Western Crystal.
