### ISSUE TITLE
Rename NotApplicableName

### ISSUE THREAD

**Issue by SatoMew** [pret/pokecrystal#492]
The Japanese ROMs of Gold/Silver and Crystal have [an actual name for this scrapped location](https://tcrf.net/Pokémon_Gold_and_Silver/Unused_Text#Location_Names) (`$92794` in Japanese Crystal) so it should be called `HauntedHouseName`.

https://github.com/pret/pokecrystal/blob/878092004956418bfd77bfdb9fc9dd7f640f80d2/data/maps/landmarks.asm#L132

**Comment by Rangi42** [comment]
But in English the name is "N/A", and `NotApplicableName` is a good label for pointing to `db "N/A@"`.

If it were referred to in any beta/unused capacity that looks like it was meant for a haunted house, then a second `HauntedHouseName` label would make sense. Kind of like the `PokemonProfGroup` label that's identical to `WillGroup` in data/trainers/parties.asm, but data/trainers/party_pointers.asm demonstrates the labels meaning.

**Comment by SatoMew** [comment]
Would a comment suffice then? Something like:

`; meant to be HAUNTED HOUSE (オバケやしき) according to the Japanese version`

**Comment by Rangi42** [comment]
Sounds more appropriate for [the Japanese disasm](https://github.com/PikalaxALT/pokekuristaru). Since this isn't a translation error, it's not "meant to" be HAUNTED HOUSE; it's just an interesting tidbit about a different ROM than the one built by pokecrystal.

**Comment by SatoMew** [comment]
I would agree with you about it not being a localization (not translation) error if the game wasn't already riddled with them but https://github.com/pret/pokecrystal/commit/9a7da21006c2c51780424af3410ff8d7d0b59e61 is enough to let people know of what it is about 😄
