### ISSUE TITLE
Text label style (data/text/)

### ISSUE THREAD

**Issue by xCrystal** [pret/pokecrystal#498]
Currently, in data/text/common_*.asm and data/text/battle.asm, there seems to be a mix between ``Text_*`` labels and ``*Text`` labels, and ``BattleText_*`` labels and ``*Text`` labels, respectively. Not talking about the ``UnknownText_*`` labels that haven't been named yet or the context specific labels that have their own formatting for convenience, but all the other generic text labels. Particularly, in battle.asm, there is a 50/50 mix of both styles and there doesn't seem to be any correlation between when one style is used over the other.

So I guess it could be something to go through at some point, and, fow anyone labeling more text, to stick to the same style (I'd suggest the ``*Text`` style since it seems to be the dominant one for scripts and everything else)

**Comment by Rangi42** [comment]
There should be one consistent style for labels of actual text, and one for labels that just `text_jump` to the real text.

**Comment by Rangi42** [comment]
This is an open-ended principle for future code refactoring, so it's addressed [on the wiki](../wiki/Code-cleanup).
