### ISSUE TITLE
PNGs all need four indexed colors

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#502]
This makes sense for Pokémon and trainer sprites, since they need to distinguish which colors are light and dark. But for most other graphics (tilesets, overworld sprites, etc), it would be convenient if the PNG colors were inspected directly, with #000000, #555555, #AAAAAA, and #FFFFFF recognized as the four hues of a 2bpp. Common graphics editors including MS Paint and paint.net don't let you rearrange colors within the index, or even distinguish between different PNG color formats.

**Comment by Kroc** [comment]
A more directly visual way to see the graphics in the repo would be appreciated. Your Python scripts could process the images by looking at the colour codes rather than indexes so that any tool (even MSPaint) could be used. To save processing time, PNGs could be cached out to the bps files the assembler uses.

**Comment by Rangi42** [comment]
@Kroc was your comment intended for a different repo? pokecrystal already stores all graphics as .png files, not .2bpp or .2bpp.lz, and GitHub displays PNGs in its online interface. (*polished*crystal stores the 2bpp.lz files themselves, which makes the initial build faster, but is less convenient than .pngs for editing.)

You're right that a custom script might be the way to go here. Prior to `rgbgfx`, pokecrystal used `gfx.py` to convert .png to .1bpp/.2bpp. They switched because `rgbgfx` is faster, but maybe it could be replaced by a custom tool implemented in C. (Like how `tools/scan_includes.c` is used instead of `rgbasm -M` for listing dependencies; sure `rgbasm` and `rgbgfx` are pre-existing tools, but custom ones can provide speed and feature advantages.)

A hypothetical `tools/png2bpp.c` would probably depend on libpng and zlib, and they would need adding to the list of required Cygwin packages if so.

**Comment by yenatch** [comment]
rgbgfx already does this

**Comment by Kroc** [comment]
You could use Golang or Rust to build static binaries that wouldn't rely on Cygwin.

**Comment by Rangi42** [comment]
You're right! Thanks for the pointer.

> The resulting colors and their palette indices are determined differently depending on the input PNG file:
> • If the file has an embedded palette, that palette's color and order are used.
> • If not, and the image only contains shades of gray, rgbgfx maps them to the indices appropriate for each shade. Any undetermined indices are set to respective default shades of gray. For example: if the bit depth is 2 and the image contains light gray and black, they become the second and fourth colors - and the first and third colors get set to default white and dark gray. If the image has multiple shades that map to the same index, the palette is instead determined as if the image had color.
> • If the image has color (or the grayscale method failed), the colors are sorted from lightest to darkest.

– [rgbgfx docs](https://rednex.github.io/rgbds/rgbgfx.1.html)

So if a file is edited and then saved as as a non-indexed PNG, assuming all the pixels are the right four shades of gray, there shouldn't be a problem.

MS Paint appears to save PNGs with color mode 6 (each pixel is an RGBA tuple), which rgbgfx is OK with. paint.net lets you choose the bit depth when resaving, but its auto-detection seems to have been messing up the palette. I'll note that in any guides about editing tilesets.
