### ISSUE TITLE
Question about how Shiny Pokemons palette's are determined?

### ISSUE THREAD

**Issue by Hecatoncheires** [pret/pokecrystal#508]
Hello! As the topic states, I had some confusion about how these games determine a Pokémon's shiny palette.

Before I ran into Pokecrystal, I had heard that Shiny Pokémon's palette's were simply shifted in code from the pokemon's current palette, to the next available one. Or, that if that resulted in an ugly shiny, they'd specifically give those few cases a specific palette, such as black colored charizard.

And, that seems pretty logical to me, but with using Pokecrystal, I see that all of the Pokemon have a specific shiny palette in their graphical files, just like they do for their normal one. And I'm not sure if that's just something Pokecrystal introduced to make the process easier, or how the real games did it?

Since I was hoping to use the prior method to generate some "official" looking shinies for new fakemon for my game, I was just wondering if someone could help shine some light on exactly how they work. 

Thank you!

**Comment by mid-kid** [comment]
The shiny palettes are actually hardcoded into the game, if that's what you're asking. What that person probably meant is that when a pokemon is shiny, it simply uses the next palette in the palette table, which just happens to be the shiny palette. See `data/pokemon/palettes.asm`

**Comment by Hecatoncheires** [comment]
Yes, whether or not the creators deliberately created the shiny colors for gen.2/3 Pokemon, or whether it was done through a coded process, was what I wanted to know. 

And even though it's a bit disappointing to learn they picked them themselves, as it relates to my project, it does very much answer my question. Thanks a lot!
