### ISSUE TITLE
make warning from gcc

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#527]
```
lzcomp.c: In function ‘optimize’:
lzcomp.c:312:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if (commands -> value != next -> value) break;
            ^
lzcomp.c:313:7: note: here
       case 3:
       ^~~~
```

**Comment by aaaaaa123456789** [comment]
The fallthrough is intentional. If you guys want to shut the warning up somehow, be my guests :P

**Comment by Pokechu22** [comment]
You should be able to write [`__attribute__ ((fallthrough))`](https://gcc.gnu.org/onlinedocs/gcc/Statement-Attributes.html) to disable it in specific cases, or disable the warning entirely.
