### ISSUE TITLE
No module named extras.pokemontools?

### ISSUE THREAD

**Issue by ApolloMaster** [pret/pokecrystal#536]
Hi! i'm new to dissasemblies and ASM in general, so my sincerest apologies if this is a really stupid question, but when trying to change the palette of my player character, i'm following a tutorial entitled Pokecrystal for Dummies in which it tells me to execute the command `python gfx.py png gfx/folderyouwant/fileyouwant.2bpp.lz`, in my case of course this means `python gfx.py png gfx/player/chris.2bpp.lz`. I try this command and it gives me the error message: `Traceback (most recent call last):
  File "gfx.py", line 6, in <module>
    from extras.pokemontools import gfx, lz
ImportError: No module named extras.pokemontools
`. I'm not sure what this means, so any help is appreciated! Thanks in advance!

**Comment by mid-kid** [comment]
You forgot `--recursive` when cloning.
To fix: `git submodule update --init --recursive`
If you downloaded a zip instead, try reading INSTALL.md again.

**Comment by yenatch** [comment]
The tutorial is likely out of date since all the images are already png and gfx.py has been removed.

**Comment by ApolloMaster** [comment]
Well that seemed to work at first, but then it gave me this:
`python gfx.py png gfx/player/chris.2bpp.lz
Traceback (most recent call last):
  File "gfx.py", line 264, in <module>
    main(**get_args().__dict__)
  File "gfx.py", line 254, in main
    method(filename, **args)
  File "gfx.py", line 225, in to_png
    decompress(filename, **kwargs)
  File "gfx.py", line 234, in decompress
    lz_data = open(filename, 'rb').read()
IOError: [Errno 2] No such file or directory: 'gfx/player/chris.2bpp.lz'
`. Again, really sorry if this is super easy and i'm just as smart as a bag of rocks but this is confusing.
If it helps, the code it gave me with your solution was this: `git submodule update --init --recursive
Submodule 'extras' (git://github.com/pret/pokemon-reverse-engineering-tools.git) registered for path 'extras'
Cloning into '/home/myname/pokecrystal/extras'...
Submodule path 'extras': checked out '2ae1ae2f19c842da965cd3db1b0da8bf108ac235'
`

**Comment by mid-kid** [comment]
>No such file or directory: 'gfx/player/chris.2bpp.lz'
Consider reading error messages.
That said, like @yenatch said above, you don't need to convert the file to png, since it's already saved as png. Just edit the png normally.

**Comment by ApolloMaster** [comment]
Well that would be the case but i'm trying to edit the player palette, as i said before. And there's no .pal file for the player so as far as i know this is the only way.

**Comment by ApolloMaster** [comment]
Well i think i do unless i'm missing something, as that seems like the only way for me to edit the palettes of the player. And yes i was stupid, i checked the files and the only one that ends in `.lz` is `chris_back`, so i corrected that but now all it gives is a blank space and puts me back at `@DESKTOP-UES1BA0 ~/pokecrystal`. I tried giving the "chris.png" sprite a palette and it continued to be the orange it is in the base game.

**Comment by mid-kid** [comment]
Even if you got this to work it wouldn't edit the player's palette, as the palette isn't stored in a .2bpp file (it's stored in a .pal file). When an image in this repo is grayscale it's usually a clear indicator that the palette isn't defined by that image. The male player shares their palette with Cal, and as such the palette is defined by gfx/trainers/cal.png. Edit it with an editor that supports editing png palettes (I recommend using GIMP's Palettes dialog. Under Windows->Dockable Dialogs->Colormap).
The same applies for the female. She shares her palette with falkner.

**Comment by ApolloMaster** [comment]
Ah, okay. Thank you! Sorry to inconvenience you both, that was really silly of me! I greatly appreciate your help, thank you so much!
