### ISSUE TITLE
Rename text commands

### ISSUE THREAD

**Issue by mid-kid** [pret/pokecrystal#575]
Text commands are used as part of the scriptable text engine. `TX_START` simply means a `@`-terminated string follows, which may contain as many characters and/or control characters as it wants.

There's a lot of such "text commands", ranging from running an asm script to playing a sound. These are used interchangeably in "text scripts" with control characters such as `para`, `line`, `cont` and such. To clear up confusion about which is which, I'd love to get all of the text commands that aren't already, prefixed with `text_`. This doesn't work as well for every single text command, so we should figure out what to rename some of the commands to. Maybe it's a good idea to make some exceptions, for example for the `sound_` "text commands".

**Comment by Rangi42** [comment]
[docs/text_commands.md](../blob/master/docs/text_commands.md) lists all the current script and command macros with brief descriptions. A summary:

- `TX_START` == `text_start`
- `TX_RAM` == `text_from_ram` *address*
- `TX_BCD` == `text_bcd` *address*, *flags*
- `TX_MOVE` == `text_move` *address*
- `TX_BOX` == `text_box` *address*, *height*, *width*
- `TX_LOW` == `text_low`
- `TX_WAIT_BUTTON` == `text_waitbutton`
- `TX_SCROLL` == `text_scroll`
- `TX_START_ASM` == `start_asm`
- `TX_NUM` == `deciram` *address*, *bytes*, *digits*
- `TX_EXIT` == `interpret_data`
- `TX_SOUND_DEX_FANFARE_50_79` == `sound_dex_fanfare_50_79`
- `TX_DOTS` == `limited_interpret_data` *n*
- `TX_LINK_WAIT_BUTTON` == `link_wait_button`
- `TX_SOUND_DEX_FANFARE_20_49` == `sound_dex_fanfare_20_49`
- `TX_SOUND_ITEM` == `sound_item`
- `TX_SOUND_CAUGHT_MON` == `sound_caught_mon`
- `TX_SOUND_DEX_FANFARE_80_109` == `sound_dex_fanfare_80_109`
- `TX_SOUND_FANFARE` == `sound_fanfare`
- `TX_SOUND_SLOT_MACHINE_START` == `sound_slot_machine_start`
- `TX_STRINGBUFFER` == `text_buffer` *id*
- `TX_DAY` == `current_day`
- `TX_FAR` == `text_far` *address*

At least some like `interpret_data` and `limited_interpret_data` are complete misnomers. I agree that most should be `text_*` except for the `sound_*` ones. The docs should also make clear the difference between text commands and control character convenience macros, and explain some subtleties:

- `text` is actually a convenience macro for a command, not a control character: `text_start` immediately followed by some text. You'll often see a command like `text_from_ram` followed by `text_start` and then `line`, `para`, or `cont`, but on the occasions when a command occurs mid-line it's just followed by `text`, not `text_start` and then `text`.
- Clarify that `done` ends a string *and* stops processing commands, while `"@"` just ends the string, and you need a second `"@"` for `DoTextUntilTerminator` to end the command processing.

Many labels in [home/text.asm](../blob/master/home/text.asm) could be renamed to make all this clearer too.

Other possible edits:

- Introduce a `text_end` macro that expands to `"@@"` or just `"@"`. So this:

```
UnknownText_0x1bd429::
	text "<PLAYER> traded"
	line "@"
	text_from_ram wMonOrItemNameBuffer
	text " for"
	cont "@"
	text_from_ram wStringBuffer2
	text ".@@"
```

would become this:

```
UnknownText_0x1bd429::
	text "<PLAYER> traded"
	line "@"
	text_from_ram wMonOrItemNameBuffer
	text " for"
	cont "@"
	text_from_ram wStringBuffer2
	text "."
	text_end
```

or this:

```
UnknownText_0x1bd429::
	text "<PLAYER> traded"
	line "@"
	text_from_ram wMonOrItemNameBuffer
	text " for"
	cont "@"
	text_from_ram wStringBuffer2
	text ".@"
	text_end
```

**Comment by Rangi42** [comment]
`done` expands to `db "<DONE>"` aka `db $57`, not `db "@"` aka `db $50`. You'd be adding Coin Case glitches everywhere. :P

`PlaceNextChar` calls `CheckDict` to interpret control characters, and has a separate terminating case that checks for `"@"`. Independently, `DoTextUntilTerminator` interprets text commands, and has its own terminating case that checks for `"@"`. It's a case of two constants that happen to have the same value. So never mind `text_end` being `"@@"`, but `text_end` being `"@"` I think makes sense. (And/or a `TX_END EQUS "@"` constant to use within code like the `DoTextUntilTerminator` check.)

**Comment by Rangi42** [comment]
Thanks for the feedback. I'd like to follow the pattern of other text commands, and introduce a `TX_END` constant and a `text_end` macro that expands to `db TX_END`.

---

So, I'm double-checking the uses of `"@@"` more closely and see two kinds of uses.

Sometimes it really does look functionally equivalent to `done`, like here:

```
_OakText2::
	text "This world is in-"
	line "habited by crea-"
	cont "tures that we call"
	cont "#MON.@@"
```

(Although not byte-equivalent, of course, so we can't search+replace `"@@"` with `done` and reproduce the ROM.)

There the first `@` is interpreted by `PlaceNextChar` and ends the string started by `text`, and the second `@` is interpreted in a text-command context as `TX_END` by `DoTextUntilTerminator` and ends the command stream. (I don't know why Game Freak chose not to use `done` in cases like this.)

Other times I see `"@@"` occurring outside the context of an ongoing string. Like here:

```
UnknownText_0x1bc14f::
	text_from_ram wStringBuffer1
	text " grew to"
	line "level @"
	deciram wCurPartyLevel, 1, 3
	text "!@"
	sound_dex_fanfare_50_79
	text_waitbutton
	db "@@"
```

Was this excessive `@` use on Game Freak's part? Because as far as I can tell the first `@` is already interpreted as `TX_END` by `DoTextUntilTerminator`, and the second one is never reached.

Also, even in the first type of instance, is `done` really an appropriate substitute for `"@@"`? Because [this](https://github.com/pret/pokegold/blob/master/data/text/common_3.asm#L330-L334) was a well-known bug in G/S that didn't properly terminate the string. What am I missing?

**Comment by mid-kid** [comment]
To me, it just looks like general sloppiness, caused because of inexperience/confusion about the text scripting system in general, just like we are. :P
```
    text "lorem ipsum@@"
```
Should become
```
    text "lorem ipsum@"
    text_end
```

and
```
    text_waitbutton
    db "@@"
```
should become
```
    text_waitbutton
    text_end
    text_end
```
To highlight the redundancy.

**Comment by Rangi42** [comment]
How do these renames sound, @mid-kid ?

- `text_from_ram` → `text_ram`
- `start_asm` → `text_asm`
- `deciram` → `text_num`
- `interpret_data` → `text_exit`
- `limited_interpret_data` → `text_dots`
- `link_wait_button` → `text_linkwaitbutton` (matches `text_waitbutton`)
- `current_day` → `text_today`
- Introduce `TX_END EQU $50` and `text_end` for `db TX_END`
- Apply `text_end` wherever it's relevant (don't mix up the two roles of `"@"`)

**Comment by mid-kid** [comment]
This sounds good. Though I'd consider `text_decimal` instead of `text_num` if someone ever wants to make a `text_hex` or something.

**Comment by mid-kid** [comment]
Also `text_exit` is too ambiguous when `text_end` exists as well. What's the meaning of `text_exit` (I haven't looked at its code)?

**Comment by mid-kid** [comment]
Yeah, `text_pause` and `text_dots` sound fine. Might I suggest documenting this behavior in the appropriate docs/ file?

**Comment by Rangi42** [comment]
PR #577 handles this; please review, particularly for the `"@"` / `text_end` distinction.
