### ISSUE TITLE
MIDI importer

### ISSUE THREAD

**Issue by yenatch** [pret/pokecrystal#58]
A MIDI importer would be a boon to anyone looking to edit music sanely.

**Comment by oliveratutexas** [comment]
Get anywhere with this? Need any help?

**Comment by froggestspirit** [comment]
https://hax.iimarckus.org/topic/7113/
Not the most user friendly, but arguably a little better, as it has real time playback, and emulation of the sound engine. It still has a few bugs though.

**Comment by yenatch** [comment]
We could hack up pokeruby's mid2agb to spit out pokecrystal music. I think we'll also want a way to generate soundfonts for midi editors. Failing that .xm or .ftm converters might be useful.

**Comment by froggestspirit** [comment]
I want to update my program a bit, but I'm not sure when i'd get around to it. The only thing about midi, is that it doesn't cater towards the commands pokecrystal has, so a form of emulating editor is probably good at least for the finishing touches.

**Comment by Rangi42** [comment]
> When we are developing original “Gold/Silver”, the music was created by the machine called Amiga. Then, converted to MIDI data and lastly, reconverted to make as a Game Boy sound.
>
> I, myself programmed the original music. Some of the tracks were created straight to Game Boy sound, so MIDI data won’t exist. Therefor I believe it was very difficult to represent the old Game Boy music.

— Junichi Masuda

Of course a MIDI-to-asm converter would be useful for hacks, but unfortunately we can't use it for the pokecrystal build (unlike the png-to-bpp conversion).

**Comment by Rangi42** [comment]
We have [GB Note](https://hax.iimarckus.org/topic/7113/) for editing asm music with a proper audio UI, and [MIDI2GSC](http://www.mediafire.com/file/je58y68i7us1ud6/GSCImport+Midi2GSC.rar) + [gs2c.py](https://github.com/Rangi42/polishedcrystal/blob/master/utils/gs2c.py) for basic MIDI to asm conversion. Not all of the music asm commands could ever be matched by raw MIDI data, so this is not feasible as a build tool, only as utilities for manually creating music.
