### ISSUE TITLE
`farcall` and `farjump` namespace collision.

### ISSUE THREAD

**Issue by mid-kid** [pret/pokecrystal#580]
`farcall` is an assembly macro, while `farjump` is a map scripting command. These names are very similar, which can cause confusion. I propose renaming `farjump`, to for example `farsjump`, like its `farscall` counterpart.

**Comment by Rangi42** [comment]
All the `farX` macros pair up with `X` macros:

- `farcall` with `call` (both for asm)
- `farscall` with `scall` (both for event scripts)
- `farjump` with `jump` (both for event scripts)

If someone implements a far-jumping assembly routine, the appropriate macro would be `farjp`.

**Comment by aaaaaa123456789** [comment]
It might be worth renaming both `jump` and `farjump` to `sjump` and `farsjump` for clarity and symmetry with `(far)?scall`, and to remove a newbie trap that has caught many.

**Comment by Rangi42** [comment]
This does make sense; but there are also the event commands `jumptext` and `farjumptext`. `jumptext` is widely used in map scripts and would be awkward to rename now, but then we'd have a mix of `*jump*`s and `*sjump*`s in events.

I'd like to get at least brief descriptions of each command into [docs/event_commands.md](docs/event_commands.md), which could have a clarification on top that they're completely separate from [assembly instructions](docs/assembly_programming.md).

**Comment by mid-kid** [comment]
Ah, yeah, that'd be good.

**Comment by Rangi42** [comment]
Sure, but then there's still the asymmetry of `(far)sjump SomeScript` versus `(far)jumptext SomeText`.

I only see two people in the pret+pret2 chat history confused about using `farjump` in assembly anyway; and having some basic command docs for newbies to start with would help avoid that.

**Comment by mid-kid** [comment]
I mean, I agree, but I believe this'd also help. I'm not particularly bothered by the `jumptext` thing but if you want to change it to `textjump` I won't object.
Should we create a separate issue for event command docs, or add it to this issue?

**Comment by aaaaaa123456789** [comment]
I'll point out that I ran into the same confusion back in 2016. And it's not too easy to debug, sadly, since both `farcall` and `farjump` are macros, meaning that neither shows up in the debugger.

**Comment by Rangi42** [comment]
I can live with `jumptext`/`jumptextplayer` being different from `sjump`/`farsjump`.

No need for an open issue about the incomplete docs; almost all of them still need to be written. (Any volunteers?)

**Comment by aaaaaa123456789** [comment]
I personally don't mind `(far)?sjump` being the odd one out either, as the rest of the jumping commands are clearly scripting macros (since a `jumptext` macro would make no sense as inline assembly).

**Comment by Rangi42** [comment]
Right, so only `jump` → `sjump` and `farjump` → `farsjump` will change. Feel free to open a PR.

**Comment by Rangi42** [comment]
So what's the verdict on renaming `jump` + `farjump` to `sjump` + `farsjump`? It can be taken care of at the same time as #540.

**Comment by mid-kid** [comment]
I'm OK with this.
