### ISSUE TITLE
Document Farfetch'd's pitfall

### ISSUE THREAD

**Issue by aaaaaa123456789** [pret/pokecrystal#594]
If Pokémon names are lowercased, data/names.asm needs one further update: since `"FARFETCH'D"` is 10 characters, but `"Farfetch'd"` is 9 (due to `'d` being a single character), a padding `@` is necessary (`"Farfetch'd@"`).  
Otherwise, all further Pokémon names become off by one character, dropping the leading character of the name (`Meganium` → `eganium`) and also appending the first character of the next Pokémon's name to those that are 10 characters long (`Typhlosion` → `yphlosionT`, `Feraligatr` → `eraligatrS`).

**Comment by ketsuban** [comment]
It's already mentioned on [the wiki page for adding a new species](https://github.com/pret/pokecrystal/wiki/Add-a-new-Pok%C3%A9mon#2-give-it-a-name) but a mention on [the design flaws page](../blob/master/docs/design_flaws.md) may be appropriate.

**Comment by Rangi42** [comment]
See https://github.com/pret/pokecrystal/wiki/Tips-and-tricks
