### ISSUE TITLE
Improvements for the "Bugs and Glitches" documentation page

### ISSUE THREAD

**Issue by aaaaaa123456789** [pret/pokecrystal#595]
Several things in the [Bugs and Glitches](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md) page could be improved. I'm making an issue here instead of a pull request because I expect a lot of debate to come out of this.

Header titles are copied straight from that page. The numbering is my own to be able to more easily refer to each section in this issue.

---

## (A) Overall fix: Link battle compatibility

Many of the sections of the document list that fixing a bug would break link battle compatibility. As of the time of writing, these sections are:

* [Thick Club and Light Ball can make (Special) Attack wrap around above 1024](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#thick-club-and-light-ball-can-make-special-attack-wrap-around-above-1024)
* [Metal Powder can increase damage taken with boosted (Special) Defense](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#metal-powder-can-increase-damage-taken-with-boosted-special-defense)
* [Reflect and Light Screen can make (Special) Defense wrap around above 1024](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#reflect-and-light-screen-can-make-special-defense-wrap-around-above-1024)
* [Moves with a 100% secondary effect chance will not trigger it in 1/256 uses](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#moves-with-a-100-secondary-effect-chance-will-not-trigger-it-in-1256-uses)
* [Belly Drum sharply boosts Attack even with under 50% HP](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#belly-drum-sharply-boosts-attack-even-with-under-50-hp)
* [Confusion damage is affected by type-boosting items and Explosion/Self-Destruct doubling](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#confusion-damage-is-affected-by-type-boosting-items-and-explosionself-destruct-doubling)
* [Moves that lower Defense can do so after breaking a Substitute](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#moves-that-lower-defense-can-do-so-after-breaking-a-substitute)
* [Counter and Mirror Coat still work if the opponent uses an item](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#counter-and-mirror-coat-still-work-if-the-opponent-uses-an-item)
* [A Disabled but PP Up–enhanced move may not trigger Struggle](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#a-disabled-but-pp-upenhanced-move-may-not-trigger-struggle)
* [A Pokémon that fainted from Pursuit will have its old status condition when revived](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#a-pokémon-that-fainted-from-pursuit-will-have-its-old-status-condition-when-revived)
* [Lock-On and Mind Reader don't always bypass Fly and Dig](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#lock-on-and-mind-reader-dont-always-bypass-fly-and-dig)
* [Beat Up can desynchronize link battles](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#beat-up-can-desynchronize-link-battles)
* [Beat Up works incorrectly with only one Pokémon in the party](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#beat-up-works-incorrectly-with-only-one-pokémon-in-the-party)
* [Beat Up may trigger King's Rock even if it failed](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#beat-up-may-trigger-kings-rock-even-if-it-failed)
* [Present damage is incorrect in link battles](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#present-damage-is-incorrect-in-link-battles)
* [Dragon Scale, not Dragon Fang, boosts Dragon-type moves](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#dragon-scale-not-dragon-fang-boosts-dragon-type-moves)

All of these pages could link to a section describing the various alternatives available: fixing the bug (breaking link compatibility), fixing it for local battles only, or even (if someone wants to do the research) sending a custom game ID over the link and fixing the bug for the custom ROM only.

A simple example snippet of how to fix a bug only for local battles could be included. For instance, for the Belly Drum bug:

```diff
 BattleCommand_BellyDrum:
 ; bellydrum
-; This command is buggy because it raises the user's attack
-; before checking that it has enough HP to use the move.
-; Swap the order of these two blocks to fix.
+	ld a, [wLinkMode]
+	cp LINK_COLOSSEUM
+	jr z, .skip_initial_check
	call BattleCommand_AttackUp2
	ld a, [wAttackMissed]
	and a
	jr nz, .failed

+.skip_initial_check
 	callfar GetHalfMaxHP
 	callfar CheckUserHasEnoughHP
 	jr nc, .failed
+
+	ld a, [wLinkMode]
+	cp LINK_COLOSSEUM
+	jr nz, .skip_new_check
+	push bc
+	call BattleCommand_AttackUp2
+	pop bc
+	ld a, [wAttackMissed]
+	and a
+	jr nz, .failed
+.skip_new_check
```

## (B) [Moves with a 100% secondary effect chance will not trigger it in 1/256 uses](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#moves-with-a-100-secondary-effect-chance-will-not-trigger-it-in-1256-uses)

While the use of `100 percent` in the `cp 100 percent` line makes sense in context, it is suboptimal. These pages are a great place to teach people how to write optimal code, too — people learn by example, so give good examples to begin with. This instruction should be replaced with `inc a`, which would be entirely equivalent (because `100 percent` is `$ff`); a comment could be added explaining why this works.

## (C) [Counter and Mirror Coat still work if the opponent uses an item](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#counter-and-mirror-coat-still-work-if-the-opponent-uses-an-item)

There's no need whatsoever to use `jp` in the `jp .failed` line; the relevant functions are very short. This snippet should use `jr` instead.

## (D) [Lock-On and Mind Reader don't always bypass Fly and Dig](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#lock-on-and-mind-reader-dont-always-bypass-fly-and-dig)

The fix described here is a lousy hack, which leaves clutter all over the codebase. The proper fix is to delete both the function and all its callsites, removing the now completely useless `jr nz, <something>` checks after said calls (and even the jump targets themselves, if needed).

## (E) [Beat Up may fail to raise Substitute](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#beat-up-may-fail-to-raise-substitute)

The code given in the fix is suboptimal. Game Freak made the same mistake, but we don't need to repeat it. The proper way of writing this fix would be:

```diff
 	cp EFFECT_MULTI_HIT
 	jr z, .multihit
 	cp EFFECT_DOUBLE_HIT
 	jr z, .multihit
 	cp EFFECT_POISON_MULTI_HIT
 	jr z, .multihit
-	jp EndMoveEffect
+	cp EFFECT_BEAT_UP
+	jp nz, EndMoveEffect

 .multihit
 	call BattleCommand_RaiseSub
 	jp EndMoveEffect
```

## (F) [Experience underflow for level 1 Pokémon with Medium-Slow growth rate](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#experience-underflow-for-level-1-pokémon-with-medium-slow-growth-rate)

Much like in section **(B)** here, this code snippet is suboptimal. Replacing `cp 1` with `dec a` and removing the `xor a` instruction slightly further below saves two bytes and two cycles. It would be worthwhile to take the opportunity to write optimal code (and explain in comments what's going on, if needed), since people use these snippets as references quite often.

## (G) Overall fix: update references to `items/item_effects.asm`

Three of the sections in the document refer to this non-existent file:

* [Moon Ball does not boost catch rate](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#moon-ball-does-not-boost-catch-rate)
* [Love Ball boosts catch rate for the wrong gender](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#love-ball-boosts-catch-rate-for-the-wrong-gender)
* [Fast Ball only boosts catch rate for three Pokémon](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#fast-ball-only-boosts-catch-rate-for-three-pokémon)

The correct location of this file is now [`engine/items/item_effects.asm`](https://github.com/pret/pokecrystal/tree/master/engine/items/item_effects.asm). These links should be fixed to point to the right location.

## (H) [Moon Ball does not boost catch rate](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#moon-ball-does-not-boost-catch-rate)

While the fix described here is correct, it leaves a completely useless `MOON_STONE_RED` constant in the codebase. Deleting the (no longer needed) constant should be part of the fix.

## (I) [Daisy's grooming doesn't always increase happiness](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#daisys-grooming-doesnt-always-increase-happiness)

This fix is a lousy hack. It should be at least labelled as a workaround (which it is). A proper fix would use a special value for the end of the list (e.g., zero, which is invalid anyway), and test for this value in the routine.

## (J) [Magikarp length limits have a unit conversion error](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#magikarp-length-limits-have-a-unit-conversion-error)

First of all, in a remarkable display of irony, this section has unit conversion errors: 1600mm are almost 5' 3" on the dot (the actual value is 5 feet 2.9921 inches), but the comments in the code fix claim that 1600mm are 5' 2". (The section also claims that 1616mm are 5' 3", when they would convert to 5' 4" if rounded to nearest, but this is far less egregious, since 1616mm = 63.6220 inches.)

Moreover, since the conversion from millimeters to inches implies a division by 25.4, the resulting values are extremely coarse, and thus rewriting this section meaningfully is impossible (the best way of seeing this is to notice that the second and third checks are ⅝ of an inch apart, meaning that there's no way to properly write these checks using whole amounts of inches).  
Thus, the only "real" fix for this system that would actually preserve the original (Japanese) game's behavior would be calculating the lengths in standard units and only converting to feet and inches (potentially with decimal places) when displaying the lengths.

## (K) [Battle transitions fail to account for the enemy's level](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#battle-transitions-fail-to-account-for-the-enemys-level)

First of all, this section has a bug. In the first snippet, the new code does `ld de, MON_LEVEL - MON_HP` followed by `add hl, de`. However, since the `ld a, [hli]` line shortly above increments `hl`, `hl` points to `wPartyMon<N>HP + 1` when this line is reached. The result is an off-by-one error, causing `hl` to point to `wPartyMon<N>Level + 1` (i.e., `wPartyMon<N>Status`) instead. The fix is straightforward (`ld de, MON_LEVEL - MON_HP - 1`).

Also, this function contains a lot of less-than-ideal code. As mentioned in sections **(B)** and **(F)** above, it's a good idea to write our own code (i.e., the code we add) as well as possible, since people take it as a reference. The relevant cases are as follows:

* The `ld de, MON_LEVEL - MON_HP` line only needs to load `e`, since `d` is already zero due to `ld de, PARTYMON_STRUCT_LENGTH - 1` above. (This is the same line mentioned in the bug above.) A similar case can be made for replacing `ld de, 0` with `ld e, d` right below, but that's part of the code that was already there, so it may be going out of scope.
* The new `SetTrainerBattleLevel` function contains a `bit 0, a` line early on. That check can be done in half the bytes and the cycles with `rra` (and `ret c`) instead.
* `.loop1` is not a good label name. There's no need for the numeral here (there are only three loops in the function, and the other two have proper names), and besides, we _know_ what this loop does (it's our own code), so we can give it a proper label.
* `cp $ff` can be replaced by `inc a` for a one byte and one cycle save.

## (L) [A "HOF Master!" title for 200-Time Famers is defined but inaccessible](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#a-hof-master-title-for-200-time-famers-is-defined-but-inaccessible)

It's hard to tell if the intention was to display "HOF Master!" _on_ the 200th HOF or _after_ the 200th HOF. The proposed fix corresponds to the former case. The fix for the latter case is to edit the `HallOfFame` function in the same file:

```diff
	ld hl, wHallOfFameCount
	ld a, [hl]
-	cp HOF_MASTER_COUNT
+	cp HOF_MASTER_COUNT + 1
	jr nc, .ok
	inc [hl]
```

It would be good to show both fixes and explain the difference, since which fix is chosen determines the meaning of the `HOF_MASTER_COUNT` constant. (Make sure that people know that they can apply either fix, but not both!)

## (M) [Playing Entei's Pokédex cry can distort Raikou's and Suicune's](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#playing-enteis-pokédex-cry-can-distort-raikous-and-suicunes)

This is another case of bad code, but one that particularly stands out since the inefficiency is completely gratuitous. The `call` + `ret` sequence should be replaced with a `jp`.

## (N) [Two tiles in the `port` tileset are drawn incorrectly](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#two-tiles-in-the-port-tileset-are-drawn-incorrectly)

It takes a great deal of effort to spot the tiles in question, and even more to spot the visual errors. They should be highlighted somehow.

## (O) [`ScriptCall` can overflow `wScriptStack` and crash](https://github.com/pret/pokecrystal/tree/master/docs/bugs_and_glitches.md#scriptcall-can-overflow-wscriptstack-and-crash)

This is a case where the fix is very far from harmless. Under the unmodified engine, attempting to call a script when the stack depth is maxed out can crash the game. With this fix, the call is _completely ignored_, which is essentially exchanging an old bug for a new one.

There's obviously no fix for having a stack depth limit (since memory is limited), but this should be explained, not tucked under the rug with a "fix" that isn't. Since reaching this condition indicates a script design error, most developers would want to be informed of the error (with a debug message of some sort, and potentially freezing the game so the player cannot progress from the bugged state), not have their script calls silently ignored.

**Comment by aaaaaa123456789** [comment]
While I agree that this page is not a programming tutorial, it remains true that people will copy the proposed fixes wholesale before thinking about them. Some cases of poor quality are particularly evil (section **(D)** comes to mind), since people will not only copy the given code, but also mimic it in later fixes, degrading the quality of the codebase as a whole. A page talking about these optimizations might help (I might even make one myself someday), but there's no reason to write bad code when better code requires minimal effort, particularly when this code is going to be copied and pasted by dozens of people (you know this will happen).

Regarding the Magikarp lengths in section **(J)**, the rewrite is obviously out of scope, but it would be a good idea to _mention_ that nothing short of a rewrite will completely redeem that function. The fact remains that 1600mm and 1616mm are less than an inch apart.

As for Daisy's happiness mods in section **(I)**, the fix should at least be labelled as a workaround.

**Comment by i0brendan0** [comment]
I'd also like to mention the "Pokédex entry banks are derived from their species IDs section." in the design flaws file. The fix is "Use dba instead of dw in PokedexDataPointerTable, and modify the code that accesses it to match." but it doesn't say what "modify the code that accesses it to match" actually means.
