### ISSUE TITLE
Question about Wild Pokémon Slots

### ISSUE THREAD

**Issue by nariga** [pret/pokecrystal#597]
Hello, first of all sorry for my poor English.

what do I need to do in [constants / pokemon_data_constants.asm](https://github.com/pret/pokecrystal/blob/master/constants/pokemon_data_constants.asm) to decrease the amount of wild pokemon slots in the grass and water maps? 
(from 7 to 5 on the grass, for example?)

I would like to try to make the probabilities more difficult, thus creating a more difficult game, etc.

Do I also need to edit the wild pokemon encounter percentages?
I still do not have much experience with more complex editions.

Thanks and congratulations for the excellent tutorials posted here so far.

**Comment by mid-kid** [comment]
You seem to have missed this: https://github.com/pret/pokecrystal/wiki/Add-a-new-wild-Pok%C3%A9mon-slot

I'd like to point out that this isn't the place for questions. Please join our [Discord](https://discord.gg/6EuWgX9) if you have any further questions.

**Comment by nariga** [comment]
Oh, Thanks! Helped me a lot!

 And excuse me for my mistake.
