### ISSUE TITLE
Fix typo for MOBILE STADIUM text menu

### ISSUE THREAD

**Issue by joneslee85** [pret/pokecrystal#604]
The Mobile Stadium feature is disabled by default on non-Japanese version, however it is still can be enabled through GameShark code *010576CF* 

![add](https://user-images.githubusercontent.com/135605/53696220-09bd0d80-3e19-11e9-9ad3-ace38a52f266.png)

The spelling of `STUDIUM` is clearly wrong, it should be `STADIUM`. The fix is pretty trivial. 

Please see PR pret/pokecrystal#605

**Comment by Rangi42** [comment]
Is merely enabling the MOBILE STUDIUM menu item sufficient to make whole feature work with Pokémon Stadium? If so, then I think [the wiki's unused content page](https://github.com/pret/pokecrystal/wiki/Useful-unused-data-and-routines) would be an appropriate place to briefly mention how to enable the the menu item (in asm, not via GameShark) and correct the typo, and link to some explanation or demo of the Mobile Stadium connectivity. If the feature cannot be so easily enabled, then a complete tutorial to do so would be helpful. Either way, the misspelling itself is not a useful "bug" to document, IMO.

**Comment by coltongit** [comment]
This could be something to add to the wiki, at least. I'll do so when I'm at my PC.
