### ISSUE TITLE
Incorrect Sound Effect plays when you trigger Rival/Sage event on 3F

### ISSUE THREAD

**Issue by Monkiikong** [pret/pokecrystal#630]
In the Sprout Tower 3F map when you trigger the even that plays audio for the battle between the sage and the rival the second sound effect plays the elevator sound instead of a second tackle sound.

**Comment by mid-kid** [comment]
Did you change anything in the ROM? If so, this isn't an issue with the disassembly and you should request help in the discord channel.

**Comment by Monkiikong** [comment]
It's in the code.

[SproutTower3F.asm](https://github.com/pret/pokecrystal/blob/master/maps/SproutTower3F.asm)

Line 28 and 32.

**Comment by mid-kid** [comment]
This code is the exact same as the original game's. Try it out, if it happens and it sounds wrong, it's a bug that belongs in [docs/bugs_and_glitches.md](https://github.com/pret/pokecrystal/blob/master/docs/bugs_and_glitches.md)

**Comment by mid-kid** [comment]
But it frankly sounds to me like the `SFX_` constant is just confusingly named. This is the only place where this SFX is used outside of an elevator. So maybe it could do with a rename.

**Comment by Monkiikong** [comment]
From a few videos of gameplay I've seen that the sound effect is supposed to be a second tackle.

https://youtu.be/Z7FaaUu-TNg?t=3080

https://youtu.be/i6Q-Lb8cjdI?t=548

**Comment by mid-kid** [comment]
This disassembly builds the exact same ROM as the original game, so if it doesn't happen in the videos, it won't happen here either.

**Comment by Monkiikong** [comment]
Oh I see where I've gotten confused. Just realized this isn't the polished crystal repo my bad.

**Comment by Monkiikong** [comment]
Still seems odd it's named the same as the other sound effects but plays a different sound.

**Comment by mid-kid** [comment]
Nah, it plays the same as the other times `SFX_ELEVATOR` is used. You're probably thinking of the "ding-dong" sound, this isn't that.

**Comment by Monkiikong** [comment]
Ah ok I see now. The confusion stems from the fact that the sound that played in Polished was the ding dong sound. Anyway I'll close this.
