### ISSUE TITLE
Tutorial "Add a new Pack Pocket" lacks an important part.

### ISSUE THREAD

**Issue by Maesejesus** [pret/pokecrystal#633]
Hi. The tutorials in the Wiki section are invaluable to me and I have learnt a lot from them, and first of all I want to thank everybody involved with them!

But I'd like to inform that the tutorial about adding a new Pack Pocket will lead to game crashing bugs, because it doesn't have in mind that when changing in which pocket Apricorns are stored, whenever you want to create special Poke Balls with Kurt, the game will still look in the default Item Pocket.

To fix this one needs to go to the file **engine/events/kurt.asm** and change the term "**wNumItems**" in lines 178, 215, 346, 360 and 385 with the correct pocket. in this case "**wNumBerries**", which is used in the tutorial. By swapping just that, Kurt custom ball script will work as intended.

I thought I could edit the tutorial instead of opening this issue, but maybe it would have been a bit rude.

**Comment by mid-kid** [comment]
The wiki is open for edit to everyone, so if you know how to fix it, please apply your newfound knowledge to it, so everyone can benefit.
If it were rude to edit it, it wouldn't be open like this in the first place ;)

**Comment by Maesejesus** [comment]
I edited the tutorial. The change itself is small and easy to understand, so I hope my edit is good enough.

**Comment by Rangi42** [comment]
Glad you noticed this, thanks! I went ahead and made that section shorter, similar to how the Physical/Special split tutorial condenses many identical edits into one diff.

**Comment by Maesejesus** [comment]
When writing it I have a doubt if I should simply say "Replace X for Y" in all five times it appears throughout the file, and leave it at that, but I ended going for the longer version because I thought it would be more complete. But yeah, the shortened section you made covers the same in less space.

Another little thing I'd like to point out is in the "Add a new type" tutorial. When you add a new type, the move Conversion 2 gets  screwed and can glitch or crash your game. I haven't seen a solution for this, and other people's hacks that adds a new type tend to ditch the move entirely for this reason. Conversion 1 seems to work well, though.

I guess I can add a line at the end of the tutorial warning about it, and advice to remove it from any Pokémon's moveset, or change it into another type of move entirely.

**Comment by ketsuban** [comment]
It'd be better to find out what causes it to break and add the fix to the tutorial; can you go into more detail as to what happens? Essentially all of the functionality for Conversion 2 is in its [move effect](https://github.com/pret/pokecrystal/blob/master/engine/battle/move_effects/conversion2.asm), and at a cursory glance I don't see anything that would cause problems when adding a new type.

**Comment by Rangi42** [comment]
I would suspect the `maskbits NUM_TYPES` part, but `cp TYPES_END` should prevent it from randomly picking any invalid types:

```
.loop
	call BattleRandom
	maskbits NUM_TYPES
	cp UNUSED_TYPES
	jr c, .okay
	cp UNUSED_TYPES_END
	jr c, .loop
	cp TYPES_END
	jr nc, .loop
```
