### ISSUE TITLE
Building failing with rgbds v0.3.8

### ISSUE THREAD

**Issue by dannye** [pret/pokecrystal#635]
```
[...]

pokecrystal.gbc: FAILED
pokecrystal11.gbc: FAILED
pokecrystal-au.gbc: FAILED
sha1sum: WARNING: 3 computed checksums did NOT match
Makefile:62: recipe for target 'compare' failed
make: *** [compare] Error 1

daniel@daniel-XPS-13-9360 ~/gb/pokecrystal $ md5sum pokecrystal.gbc
fe31197a7d9b2b21d3d4068a0cda6da5  pokecrystal.gbc

daniel@daniel-XPS-13-9360 ~/gb/pokecrystal $ md5sum pokecrystal11.gbc
ecf6d83ba8e0b0362d5e2b6407e5b1b8  pokecrystal11.gbc

daniel@daniel-XPS-13-9360 ~/gb/pokecrystal $ md5sum pokecrystal-au.gbc
d03a932e2de614e952792e9d194471b6  pokecrystal-au.gbc

daniel@daniel-XPS-13-9360 ~/gb/pokecrystal $ cat roms.sha1 
f4cd194bdee0d04ca4eac29e09b8e4e9d818c133 *pokecrystal.gbc
f2f52230b536214ef7c9924f483392993e226cfb *pokecrystal11.gbc
a0fc810f1d4e124434f7be2c989ab5b5892ddf36 *pokecrystal-au.gbc
```

Anyone else getting this?

This was after a `make clean` and a fresh `sudo make CFLAGS=-O2 install` with rgbds v0.3.8

**Comment by Rangi42** [comment]
The Travis CI badge on the readme says Build: Passing; and for me `make compare` prints `OK` for all three, and `rgbasm -V` prints `v0.3.8`.

**Comment by dannye** [comment]
I'm dumb.

In audio/sfx.asm I saw all these dangling `togglesfx` commands (command $df):
https://github.com/pret/pokecrystal/blob/master/audio/sfx.asm#L1042-L1046

and I saw this dangling `db $fd`:
https://github.com/pret/pokecrystal/blob/master/audio/sfx.asm#L3162-L3166

and I replaced it with `togglesfx`
