### ISSUE TITLE
More tutorials?

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [pret/pokecrystal#642]
I think more tutorials would be a nice idea. A few I came up with
Most wanted:
Add a new Phone Contact
Add a new trainer
Add a new NPC with Phone Number
Add a new Trainer with Phone Number
Add a new Room Decoration

Wanted:
Add a new NPC
Add a new Region
Add a new Cry
Add a new Pokemon Center

just barely wanted:
Add a new Badge

Don't really care about these:
Add a new Pokeball
Add a new key item
Add a new Potion
Add a new PC option
Add a new PokeDex page
Add a new Cave
Add a new Mail

**Comment by Rangi42** [comment]
Some of those already exist; look closely at the wiki. As for the rest, you can write them yourself, or add suggestions to the "To do" section.
