### ISSUE TITLE
Minor cleanup issues

### ISSUE THREAD

**Issue by aaaaaa123456789** [pret/pokecrystal#643]
I've been trying to build a reasonably clean ROM from pokecrystal (basically take the repo as it is, remove the weird hacks that only exist in order to match the original exactly, apply the various fixes from the docs, etc.), and I've stumbled upon a few minor hiccups. I'll keep adding them here as I find them.

- [x] `gfx/pokedex/question_mark.2bpp` requires a `rgbgfx += -h` rule in the Makefile. This isn't noticeable in the stock repo because the image is never rebuilt due to a pre-compressed image with a matching hash.
- [x] The footprint correction code in the design flaws document will lead to broken footprints. This is because it fails to account for the fact that footprints are now four tiles apart from each other instead of two. Adding an `add a, a` instruction after the `swap a` that is shortly before the quoted snippet fixes the issue.

**Comment by Rangi42** [comment]
The purpose of `engine/gfx/color.asm:SGBBorder_MorePalPushing` is to copy data from `SGBBorderMap` to VRAM. The SGB border is 32x28-tile interlaced tile IDs and attribute bytes. The middle of the data has a large blank space for the Game Boy screen, which is omitted from `SGBBorderMap`. So `SGBBorder_MorePalPushing` copies `BG_MAP_WIDTH`×5×2 bytes; then `SCREEN_HEIGHT` times, it copies 5×2 bytes, clears `SCREEN_WIDTH`×2 bytes, and copies another 5×2 bytes; then copies another `BG_MAP_WIDTH`×5×2 bytes. Also then it clears $100 bytes and copies 16 palettes of bytes from `SGBBorderPalettes`, which has to come right after `SGBBorderMap`.

Anyway, the relevant lines should be using the right gfx constants and multiplication (particularly `ld bc, 20 tiles` is incorrect, it's `BG_MAP_WIDTH`×5×2 bytes); and the function names are inaccurate.

**Comment by Rangi42** [comment]
The `C9` at the end of `gfx/diploma/page2.tilemap` is not an end byte; it should be a stray `ret ; unused` after the 20x18 tilemap.

**Comment by xCrystal** [comment]
Lines 784, 790, 926, and 932 of [engine/overworld/events.asm](https://github.com/pret/pokecrystal/blob/master/engine/overworld/events.asm) are ``PLAYEREVENT_`` constants.
Also, values returned in register a across [engine/overworld/player_movement.asm] subroutines (https://github.com/pret/pokecrystal/blob/master/engine/overworld/player_movement.asm) are indexes to the ``PlayerMovement.pointers`` table of engine/overworld/events.asm, which could perhaps use some constants.

**Comment by mid-kid** [comment]
`wBuffer1` on line 135 of [engine/pokemon/move_mon.asm](https://github.com/pret/pokecrystal/blob/master/engine/pokemon/move_mon.asm) should be `wEvolutionOldSpecies`.

**Comment by xCrystal** [comment]
It seems like the content of https://github.com/pret/pokecrystal/blob/master/home/movement.asm from line 131 onwards should be better moved to a different file. For example, to a new https://github.com/pret/pokecrystal/blob/master/home/menu2.asm file or to https://github.com/pret/pokecrystal/blob/master/home/menu.asm in a different section.

**Comment by bbbbbbbbba** [comment]
[This check](https://github.com/pret/pokecrystal/blob/5cdf4f9ae0cb6884472d9f7ca3926e610345c3ba/engine/battle/core.asm#L6809) isn't supposed to be a RisingBadge check, but a GlacierBadge check. It is also bugged (usage of stale register `a`), so the stat boost may not work under certain cases. A complete write-up can be found [here](https://glitchcity.info/wiki/Special_Defense_badge_boost_glitch).

**Comment by aaaaaa123456789** [comment]
The comments in the fishing functions (engine/events/fish.asm, lines 4 and 26) have their registers swapped. The functions return the species in `d` and the level in `e`.

**Comment by aaaaaa123456789** [comment]
engine/math/print_num.asm, line 9: the comment is misleading; the bit is set if the number is *left*-aligned.

**Comment by Rangi42** [comment]
@aaaaaa123456789 When I add `gfx/pokedex/question_mark.2bpp: rgbgfx += -h` to the Makefile, the build is nonmatching.

**Comment by mid-kid** [comment]
@Rangi42 The checksum on the `question_mark.2bpp.lz.xxxxxx` file is wrong, you should fix that.
