### ISSUE TITLE
Using this repo as a template corrupts some binary files

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#644]
In data/tilesets/\*_metatiles.bin, `FF` becomes `CB 99`. There may be others.

**Comment by mid-kid** [comment]
The other files are in gfx/pokegear/\*.tilemap.rle

**Comment by mid-kid** [comment]
I've just tried removing the `* text eol=lf` from the .gitattributes, but that doesn't seem to do the trick. I wonder why github is treating these files like something they're not, even though that isn't the case in the web interface?

**Comment by Rangi42** [comment]
For now I've just disabled templating for pokered and pokecrystal.

**Comment by coltongit** [comment]
Maybe this is a bug with GitHub itself and not the repos.

**Comment by mid-kid** [comment]
Considering nobody's tried reporting it to github proper yet, this bug serves as a tracker for that.

**Comment by Rangi42** [comment]
Templates don't preserve the commit history of the original, which would prevent users from pulling upstream changes. So we shouldn't use templates even if this binary issue were fixed.
