### ISSUE TITLE
Function names and comments aren't in English

### ISSUE THREAD

**Issue by aaaaaa123456789** [pret/pokecrystal#645]
File: engine/pokemon/european_mail.asm

Should be easy to locate; the file is short.

**Comment by mid-kid** [comment]
I've been aware of this for quite a long time, I thought it was cute.

**Comment by aaaaaa123456789** [comment]
Truth be told, I've known about them for three years; I never thought to make an issue before.

That being said, it seems to me that if the codebase is in English, these labels should be as well...

**Comment by mid-kid** [comment]
The only function lacking an english label/comment is the `English->French/German` conversion. I think adding an english label/comment for that would be enough.

I guess it's useless to have the labels in other languages there, and it's not something I'd want to see in other code, but like I said, it's the only language-related set of functions and I see no real reason to remove them either. Call that stockholm syndrome if you will, heh. ¯\\_(ツ)_/¯

**Comment by Rangi42** [comment]
The European labels are cute, but confused me until I looked more closely at the code, particularly since a single routine works to convert back and forth between Spanish/Italian and English.

**Comment by mid-kid** [comment]
I would keep the translated labels alongside the english ones but okay.

**Comment by aaaaaa123456789** [comment]
"Cute" but non-functional labels are pretty much clutter. They can easily confuse people who don't speak the relevant languages, too — not everyone speaks natively a language descended from western Europe, and people who don't may not even recognize Italian, French, German or Spanish.

I can't see a single good reason to keep them.
