### ISSUE TITLE
.gitignore does not include Mac files (.DS_STORE)

### ISSUE THREAD

**Issue by GreenAndEievui** [pret/pokecrystal#657]

**Comment by Asday** [comment]
For future reference, if you're on a silly OS that creates garbage files everywhere, you can avoid inflicting your issues on others by editing `.git/info/exclude`, with the exact same syntax as `.gitignore`.

**Comment by mid-kid** [comment]
This "silly OS" is pretty common, so it makes sense to ignore these files. ~~Especially considering many people using/forking this repo use git for the first time.~~

**Comment by Asday** [comment]
> This "silly OS" is pretty common

Unfortunately.  :laughing:
