### ISSUE TITLE
Miscellaneous fixes, part 2

### ISSUE THREAD

**Issue by aaaaaa123456789** [pret/pokecrystal#658]
There's no reason to have a `BANK` attribute in this section, since it's already handled by the linkerscript: https://github.com/pret/pokecrystal/blob/master/sram.asm#L221

**Comment by aaaaaa123456789** [comment]
This subfunction, `.CopyName`, is horribly misnamed; all it does is `bc += NAME_LENGTH`, making `bc` point to the next OT name in the party.
https://github.com/pret/pokecrystal/blob/master/mobile/mobile_12_2.asm#L149

**Comment by aaaaaa123456789** [comment]
https://github.com/pret/pokecrystal/blob/master/engine/events/lucky_number.asm#L151
`-6` should be `MON_SPECIES - MON_ID`

**Comment by aaaaaa123456789** [comment]
https://github.com/pret/pokecrystal/blob/master/engine/pokemon/search.asm#L247  
The `1` in the label seems odd, considering no other label in the entire game contains the string `BoxAddressTable`.

**Comment by aaaaaa123456789** [comment]
https://github.com/pret/pokecrystal/blob/master/home/farcall.asm#L48  
This function name is deceptive; while it _is_ used by the farcall code, it doesn't perform a far jump, but rather a regular `jp hl`.

**Comment by mid-kid** [comment]
We already have `_hl_` in the home bank, and unlike that one, this one is only used by the farcall code, and is located in between it.
I think the name makes proper sense.

**Comment by Rangi42** [comment]
How about `FarCall_hl`, or `_hl_FarCall`? That way `call FarCall_hl` or `call _hl_FarCall` would be clear, and wouldn't make it seem useful on its own.

**Comment by mid-kid** [comment]
`FarCall_hl` already exists.

**Comment by Rangi42** [comment]
`_hl_for_FarCall`?

**Comment by aaaaaa123456789** [comment]
Or make it explicit: `FarCall_DoHLJump`  
The longer name makes it clear that it's pointless to use on its own...

**Comment by aaaaaa123456789** [comment]
`hFF8C` should be `hSRAMBank`. While it's only used by mobile code, that's clearly its purpose.

**Comment by aaaaaa123456789** [comment]
In `Unreferenced_Functione5d9` (https://github.com/pret/pokecrystal/blob/master/engine/pokemon/bills_pc_top.asm#L264):

* `wc608` → `wBoxPartialData`
* `ld bc, 0` (shortly after `.loop`): the 0 represents the distance between the box's mons and the first mon's species. Perhaps `sBoxMon1Species - sBoxMons`? (In which case, `ld bc, 1 + MONS_PER_BOX + 1` above could be `ld bc, sBoxMons - sBox` and `ld bc, MONS_PER_BOX * (BOXMON_STRUCT_LENGTH + NAME_LENGTH)` later on could be `ld bc, sBoxMonNicknames - sBoxMons`.)

**Comment by aaaaaa123456789** [comment]
Also, perhaps rename the function? `Unreferenced_LoadBoxMonListing` should be fine, since what it does is copy an array of mini-structs into `wBoxPartialData` (which only contain species, nickname, level and gender — without any sort of count or terminator)...

**Comment by coltongit** [comment]
`bugs_and_glitches.md` has old names for the needed bugfix for `Five-digit experience gain is printed incorrectly`. The names have changed to `_BoostedExpPointsText` and `_ExpPointsText` respectively since the last time that section was modified.
`_ABoostedStringBuffer2ExpPointsText=`_BoostedExpPointsText`
`_StringBuffer2ExpPointsText`=`_ExpPointsText`
If any of you were wondering what goes where

**Comment by aaaaaa123456789** [comment]
https://github.com/pret/pokecrystal/blob/master/engine/events/halloffame.asm#L452

Should be `ld [wStringBuffer2 + MON_NAME_LENGTH - 1], a`

**Comment by coltongit** [comment]
> This subfunction, `.CopyName`, is horribly misnamed; all it does is `bc += NAME_LENGTH`, making `bc` point to the next OT name in the party.
> https://github.com/pret/pokecrystal/blob/master/mobile/mobile_12_2.asm#L149

It'd make more sense to have this function be named `.PointToNextOTName`.

**Comment by coltongit** [comment]
`.PointToNextOTNameInParty` would work too

**Comment by coltongit** [comment]
`Function384d5` in engine/battle/ai/items.asm could be named `EnemyUsedFullHealUnused`
