### ISSUE TITLE
Miscellaneous fixes, part 3

### ISSUE THREAD

**Issue by coltongit** [pret/pokecrystal#663]
Continues #658.
`Function384d5` in engine/battle/ai/items.asm could be named `EnemyUsedFullHealUnused`, as this uses the old constant for Full Heals from RBY
Also, what the heck does `Function3851e` in the same file do?

**Comment by ISSOtm** [comment]
That function checks if the enemy mon's current HP is exactly a certain fraction of its max HP. Which fraction is passed by its parameter (ie. param 2 => return Z set if enemy mon is at *exactly* half its max HP)

**Comment by coltongit** [comment]
That could be renamed to `CheckEnemyHPFraction` as discussed in the Discord.

**Comment by coltongit** [comment]
`Function39990` in `engine/battle/read_trainer_party.asm` could be named `LoadTrainerName` as that is what it seems to do

**Comment by ISSOtm** [comment]
No, [that function](https://github.com/pret/pokecrystal/blob/083d51fd588d9752b8f7c5d104cffc3896d51b5b/engine/battle/read_trainer_party.asm#L383) does `ld de, wStringBuffer1` then `ld bc, NAME_LENGTH`, but that's it.

**Comment by coltongit** [comment]
> No, [that function](https://github.com/pret/pokecrystal/blob/083d51fd588d9752b8f7c5d104cffc3896d51b5b/engine/battle/read_trainer_party.asm#L383) does `ld de, wStringBuffer1` then `ld bc, NAME_LENGTH`, but that's it.

Then what could be a usable name for it?

**Comment by ISSOtm** [comment]
There's no really good name for it because it doesn't really do anything. It could be `LoadXXXParams` if we had context on what XXX was (= what the calling code did), but there is none of that.
Maybe `LoadUnknownParams`? But that's really generic, and could lead to conflicts with other functions.

**Comment by coltongit** [comment]
`LoadTextParams`, perhaps?

**Comment by ISSOtm** [comment]
What text? For all we know, it could be an OT comparison function, for example

**Comment by Rangi42** [comment]
Please use issues for noting changes to make, and Discord chat for working out what changes should actually be made.
