### ISSUE TITLE
GDC Sprites

### ISSUE THREAD

**Issue by Super4ng** [pret/pokecrystal#667]
I made touched up sprites for crystal, they are nearly perfectly ready, might need a little work but they are at least 95% finished if anyone would like to use them.
[https://www.mediafire.com/file/afg67yru33b3h3o/Crystal_Sprites.zip/file](url)

**Comment by Rangi42** [comment]
This project is meant to replicate the original, 100% unmodified Pokémon Crystal ROMs. If you want to modify it, create your own [fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) or just share the graphics like [here](https://hax.iimarckus.org/topic/197/).
