### ISSUE TITLE
Identify as many unnamed labels as possible

### ISSUE THREAD

**Issue by coltongit** [pret/pokecrystal#672]
Not only will this help with moddability, but it'll also help with the overall readability of the code. Just about any unnamed label (excluding mobile functionalities) would be helpful in fixing this issue. This will expand on the work in PRs #670 and #671.

**Comment by mid-kid** [comment]
Open-ended issue, already handled in [code cleanup](https://github.com/pret/pokecrystal/wiki/Code-cleanup#meaningless-temporary-labels).
Closing...
