### ISSUE TITLE
Miscellaneous fixes, part... 4?

### ISSUE THREAD

**Issue by aaaaaa123456789** [pret/pokecrystal#676]
At [line 131 in `home/time.asm`](https://github.com/pret/pokecrystal/blob/master/home/time.asm#L131), tabs are used to horizontally align text with the line immediately below. As much as Python has attempted to convince people that tabs are four spaces, they are of course not, and thus this line is clearly not aligned to the one below it, as GitHub itself (which uses proper tabs) will show.

**Comment by coltongit** [comment]
So you'd rather:
`; day     hr    min    sec`
instead of:
`;				  day     hr    min    sec`
The former would still make sense but in less tabs

**Comment by Rangi42** [comment]
You can't assume tabs are a certain width; even in the browser that's configurable via `tab-size` in user CSS. So tabs should only be for indenting opcodes, not aligning lines vertically.

IMO the whole line is redundant given the self-explanatory WRAM names. And in my default Chrome configuration, they don't even line up:

![image](https://user-images.githubusercontent.com/35663410/72991444-05e30280-3dc0-11ea-964c-88e21eb16bfa.png)

**Comment by Rangi42** [comment]
The `; S` `; M` `; H` `; DL` comments on further lines in this routine are also unnecessary.

**Comment by Rangi42** [comment]
The four "padding" bytes in base data used to be two pointers to the front and back pics. This was the case in pokered and pokegold-spaceworld, and it explains why `GetBaseData` in home/mon_data.asm loads `UnknownEggPic` into `wBasePadding` for `EGG`.
