### ISSUE TITLE
Some bugs are commented in the source code

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#677]
Should we remove "; BUG" comments entirely; add them for every bug; or leave them as-is?

In-source comments are a convenient way to remind people working with some particular function that it has a bug, especially for one- or two-line fixes. On the other hand, it's redundant with bugs_and_glitches.md, and makes the fix diffs artificially longer. And bugs with long fixes involving entire custom routines probably don't belong as source comments.

**Comment by mid-kid** [comment]
I think commented bugs help a lot while reading through the source, as they allow you to better understand what's going on, instead of having to figure out whether what is written is a mistake or not. You're not going to be checking docs/bugs_and_glitches.md constantly to see if the function you're reading has a problem or not.

That said, I don't want to pollute the source code with fix comments, that's just stupid. Instead, I propose standardizing on a format that refers to `docs/bugs_and_glitches.md` for the actual fix, something like:
```
; BUG: Short description
; See docs/bugs_and_glitches.md
```
Where `Short description` should match the title used in `docs/bugs_and_glitches.md`.

Of course, this implies some maintenance burden to keep things in-sync, but aside from the up-front work I don't think that's significant enough, and would allow for cleaner diffs in the md file, while still having the convenience of references in the source itself.

**Comment by Rangi42** [comment]
May as well use the same short descriptions for BUG comments and for the table of contents links.

**Comment by aaaaaa123456789** [comment]
I'd say this is worth it for longer bugs. For very simple bugs, the current approach is very straightforward.

After all, this is self-documenting:

```
ClearWRAM::
; Wipe swappable WRAM banks (1-7)
; Assumes CGB or AGB

	ld a, 1
.bank_loop
	push af
	ldh [rSVBK], a
	xor a
	ld hl, WRAM1_Begin
	ld bc, WRAM1_End - WRAM1_Begin
	call ByteFill
	pop af
	inc a
	cp 8
	jr nc, .bank_loop ; Should be jr c
	ret
```

**Comment by mid-kid** [comment]
The "current approach" is barely an approach at all given how it's applied inconsistently and in very different manners. As usual, I'm fine with anything as long as there's a consistency I can follow while making improvements.

**Comment by vulcandth** [comment]
When exploring this project for the first time; I first noticed the bug comments while reviewing the code, and only saw the docs/bugs_and_glitches.md later. I agree that you don't necessarily NEED the full description and fix in comments; but a note that the next section has a bug is still very helpful as a user of this project, imo. Just a small input from me; for what little it may be worth :).

**Comment by Rangi42** [comment]
I might revise them to have `BUG:` comments, but not have commented-out fixes, even when the fixes are only one or two lines. That way users would learn to check bugs_and_glitches.md for fixes, which would be necessary anyway for nontrivial amounts of new code.

**Comment by aaaaaa123456789** [comment]
> I might revise them to have `BUG:` comments, but not have commented-out fixes, even when the fixes are only one or two lines. That way users would learn to check bugs_and_glitches.md for fixes, which would be necessary anyway for nontrivial amounts of new code.
> 
> One benefit would be avoiding fix diffs like this:
> 
> ```diff
> -    ; BUG: something is broken. Uncomment 'inc a' to fix.
> -    ; inc a
> +    inc a
> ```

I like this idea. It seems clear enough, and it encourages documentation discovery.

**Comment by mid-kid** [comment]
Another benefit I really like about this being that you can just `grep BUG:` across the codebase to see what isn't fixed. I generally disagree with the notion that *everything* in the document should be fixed, but having an overview is nice.

**Comment by vulcandth** [comment]
This seems like something easy enough I could do to contribute; I can sift through all the documented BUGs and BUG comments and standardize them across the codebase. 

For example:
```diff
GetPokedexEntryBank:
-; This function is buggy.
-; It gets the wrong bank for Kadabra (64), Tauros (128), and Sunflora (192).
-; Uncomment the line below to fix this.
+; BUG: Heavy Ball uses wrong weight value for three Pokémon
+; See docs/bugs_and_glitches.md
	push hl
	push de
	ld a, [wEnemyMonSpecies]
-	; dec a
	rlca
	rlca
	maskbits NUM_DEX_ENTRY_BANKS
	ld hl, .PokedexEntryBanks
	ld d, 0
	ld e, a
	add hl, de
	ld a, [hl]
	pop de
	pop hl
	ret
```

Then the Documentation should be changed to something like this:


### Heavy Ball uses wrong weight value for three Pokémon

The GetPokedexEntryBank function gets the wrong bank for Kadabra (64), Tauros (128), and Sunflora (192).

**Fix:** Edit `GetPokedexEntryBank` in [engine/items/item_effects.asm](https://github.com/pret/pokecrystal/blob/master/engine/items/item_effects.asm):

```diff
 GetPokedexEntryBank:
-; BUG: Heavy Ball uses wrong weight value for three Pokémon
-; See docs/bugs_and_glitches.md
 	push hl
 	push de
 	ld a, [wEnemyMonSpecies]
+	dec a
 	rlca
 	rlca
 	maskbits NUM_DEX_ENTRY_BANKS
 	ld hl, .PokedexEntryBanks
 	ld d, 0
 	ld e, a
 	add hl, de
 	ld a, [hl]
 	pop de
 	pop hl
 	ret

 .PokedexEntryBanks:
 	db BANK("Pokedex Entries 001-064")
 	db BANK("Pokedex Entries 065-128")
 	db BANK("Pokedex Entries 129-192")
 	db BANK("Pokedex Entries 193-251")
```

**Comment by aaaaaa123456789** [comment]
I'd say that keeping short descriptions of what the bugs are is useful and shouldn't be removed.

**Comment by vulcandth** [comment]
@aaaaaa123456789 
> I'd say that keeping short descriptions of what the bugs are is useful and shouldn't be removed.

Are you talking about the removal of this line in my example?
```diff
-; It gets the wrong bank for Kadabra (64), Tauros (128), and Sunflora (192).
```
Because I would be moving that info to docs/bugs_and_glitches.md as noted above. I feel like `BUG: Heavy Ball uses wrong weight value for three Pokémon` is good enough for a short description; and the other bit would be considered a "further explanation" and better off in the docs. I feel like the code shouldn't be cluttered with too many comments. A simple searchable "BUG: _bug title_" is good enough.

**Comment by aaaaaa123456789** [comment]
Yes, I'm talking about that line. Reading that line, I can fix the bug without looking up any documentation; it's obvious from looking at the code why that is happening, particularly given the numbers mentioned there.

**Comment by Rangi42** [comment]
My preference would be for the code comments to have single-line `; BUG: Description` comments where the description is the same as the heading in bugs_and_glitches.md. There's no need for every bug to specify "See docs/bugs_and_glitches.md"; the readme already points people to the docs. (Perhaps it could be changed to "[Documentation](https://pret.github.io/pokecrystal/) (includes [known bugs and glitches](https://pret.github.io/pokecrystal/bugs_and_glitches.html))" to emphasize that.)

**Comment by Rangi42** [comment]
So this is all we would need for the Heavy Ball bug:

```asm
GetPokedexEntryBank:
; BUG: Heavy Ball uses wrong weight value for three Pokémon
	push hl
	push de
	ld a, [wEnemyMonSpecies]
	rlca
	rlca
	maskbits NUM_DEX_ENTRY_BANKS
	ld hl, .PokedexEntryBanks
	ld d, 0
	ld e, a
	add hl, de
	ld a, [hl]
	pop de
	pop hl
	ret
```

**Comment by Rangi42** [comment]
By the way, if you edit the ```` ```diff ```` blocks in bugs_and_glitches.md, please make sure to put a space in front of lines which don't start with `+` or `-`. That means things like `<space><tab>add hl, de`.

**Comment by mid-kid** [comment]
+1 to just a single-line comment. That's both the most consistent and the easiest to standardize on. If the title isn't descriptive enough, the title should be modified, both in the `; BUG:` comment, *and* in the docs.

I'm not sure about not mentioning `docs/bugs_and_glitches.md`, however. *Very* few people will know to look there, especially if new, and the titles on their own might be a bit confusing if they don't know where to read a detailed explanation of the bug (some just aren't very trivial to explain).

In a perfect world I'd say yeah - referring people to the docs file in every instance is redundant, but we live in a world where the overwhelming majority of people won't ever know the documentation folder exists, much less go look in there for this specific info.

So I'm a bit undecided about that part.

**Comment by Rangi42** [comment]
How about an FAQ entry for "How do I fix the commented `BUG`s?"

**Comment by mid-kid** [comment]
my gut feeling tells me using a faq as an excuse not to do something is a bad idea and that few people read the FAQ, though I'd love to see stats about it - current stats say it's visited less than even the Links page on the wiki, which is the 10th most visited page.

But on the other hand it might be enough to put it either in the FAQ or somewhere visible on the wiki, so I guess we can do that and see if we get people wondering about it. Alternatively, would you be ok with a `BUG: Description (docs/bugs_and_glitches.md)` format?

**Comment by Rangi42** [comment]
Yeah, keeping it to a single line would be fine with me. `BUG: Short description (see docs/bugs_and_glitches.md)` would match the `(see)` comments for relating constants and data tables.

**Comment by vulcandth** [comment]
I started working on this last night. It's a bit to go through. I hope to have a pull request within the next week. When i'm done you can review the pull request and let me know what you think. I expect you'll want some adjustments as I had to use my best judgement on some things.

**Comment by mid-kid** [comment]
Don't worry, I'm glad anyone is taking this up at all.

**Comment by vulcandth** [comment]
Circling back around to this; I suppose I should probably do this to go with the other bigger repo changes (ex. #905). I'll re-start on this tonight.

**Comment by coltongit** [comment]
One thing I was also noticing about this: Should design flaws be given comments similar to these bugs in the code?
```
DESIGN FLAW: The 6-bit caught level can only record up to level 63``` for example

**Comment by aaaaaa123456789** [comment]
I'd say it makes little sense, because there's no local fix to them. That one requires a data struct redesign, for instance.
