### ISSUE TITLE
Return of the miscellaneous fixes

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#681]
- data/radio/pnp_hidden_places.asm:PnP_HiddenPlaces is misidentified. Those are not maps *hidden* from the Places & People show, they're the *only* maps whose landmarks will get described. (Obvious in retrospect since maps don't have names.) Some are just weird choices, e.g. Route 22 for Viridian City, or Cerulean Police Station for Cerulean City.

**Comment by coltongit** [comment]
Basically every map should be rechecked and verified against the game itself to see if the name is correct for said maps. Would be something PR #631 could do.

**Comment by mid-kid** [comment]
There are no names for the maps in the game. All of that has been named by us. If you know any specific names that should be fixed, point those out.

**Comment by Rangi42** [comment]
Resolved by #682 .
