### ISSUE TITLE
Redundant comments superseded by labels

### ISSUE THREAD

**Issue by aaaaaa123456789** [pret/pokecrystal#693]
There are many, many comments that come from the times everything was called `Function123` and `wcafe`. I'm just kickstarting this issue with the one case I just found, but there's probably a ton.

- [x] https://github.com/pret/pokecrystal/blob/master/wram.asm#L2402

**Comment by Rangi42** [comment]
engine/pokemon/wildmons.asm has some over-detailed comments:

```
	and a
	jr z, .nowildmon ; = 0
	cp NUM_POKEMON + 1 ; 252
	jr nc, .nowildmon ; >= 252
	and a ; 1 <= Species <= 251
```

```
; Don't trigger an encounter if we're on water.
	call CheckOnWater
	jr z, .DontEncounterRoamMon
```

And some that should use named constants:

```
	ld a, 7 ; length of the roam_struct
```

```
	ld bc, 5 + 4 * 2 ; Location of the level of the 5th wild Pokemon in that map
```

**Comment by aaaaaa123456789** [comment]
- [ ] `engine/battle/used_move_text.asm`:8 is a completely pointless comment, and one that is likely to be wrong as soon as anyone modifies the code one bit.

**Comment by aaaaaa123456789** [comment]
- [ ] `engine/battle_anims/bg_effects.asm`, lines 1513 and 1516 — self-explanatory

**Comment by aaaaaa123456789** [comment]
- [ ] `engine/battle/effect_commands.asm`:1111 contains a blank comment
