### ISSUE TITLE
Dawn of the Planet of the Miscellaneous Fixes

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#694]
Two instances of this in engine/pokemon/stats_screen.asm:

```
; ???
	ld [wcf64], a
	ld a, [wcf64]
	and %11111100
	or 1
	ld [wcf64], a
```

`or 1` should be `or PINK_PAGE`. (The first three lines are pointless since we know `a` is 0, and `ld a, [wcf64]` would be pointless anyway, but the `and %11111100` is meant to mask out the page number.)

Also `wcf64` has some bit-packed values; 0+1 are the page number, 4, 5 and 6 control something about sprite animations.

**Comment by Rangi42** [comment]
Three `__enumdir__ = +1` should be simplified to `__enumdir__ = 1`.

**Comment by Rangi42** [comment]
@mid-kid How about putting `ds` statements in home/header.asm to confirm each rst/interrupt section is 8 bytes, and as a hint that small code/data can go there like any other ROM space?

**Comment by mid-kid** [comment]
Then you thwart the linker's ability to automatically place things there. Unlike the header, it's actually fine for things to be allocated here.

**Comment by aaaaaa123456789** [comment]
`ds` statements are great if you do manual allocation, since they let you track small amounts of free space easily. If you're using the linker to automatically allocate things, though, they are very problematic.

**Comment by Rangi42** [comment]
Revert 5728d0141793d832476b3f7b5c0844166fa7c242's edit to the `CheckTypeMatchup` bug; go back to the 2c6690d10deb309102e7b69f77f973d12e4afb50 version.

**Comment by Rangi42** [comment]
Check the rgbds version and fail if it's below the required one.

**Comment by mid-kid** [comment]
`MIRAGE_MAIL` is called `MewMail` in `data/items/descriptions.asm`

**Comment by Rangi42** [comment]
In `BattleAnim_ClearCGB_OAMFlags`, the role of `and $f0` is to force the sprites' palette to `PAL_BATTLE_OB_ENEMY` (0) (it's meant for a successful Poké Ball). It could be:

```
and ~(PALETTE_MASK | VRAM_BANK_1) ; PAL_BATTLE_OB_ENEMY
```

with an explanatory comment.

**Comment by aaaaaa123456789** [comment]
It's not immediately obvious; I'd write `PAL_BATTLE_OB_ENEMY = 0` in the comment.

**Comment by Rangi42** [comment]
Also, in general we can use `~` now instead of `$ff ^` or `$ff -`. And `- 1` instead of `+ -1`.
