### ISSUE TITLE
War for the Planet of the Miscellaneous Fixes

### ISSUE THREAD

**Issue by entrpntr** [pret/pokecrystal#700]
(presumably the correct sequel to #694)

There is some variability in whether DAYCARE or DAY_CARE is used in various constant definitions. (Personally, I think DAYCARE looks better, and it is the more used of the two.)
```
$ grep -nr "const.*DAYCARE\|DAYCARE.*EQU" . | wc -l
      28
$ grep -nr "const.*DAY_CARE\|DAY_CARE.*EQU" . | wc -l
      15
```

**Comment by Rangi42** [comment]
There is a hyphen in "DAY-CARE", but either is OK.

**Comment by Lhivorde** [comment]
The macro `menu_coords` is currently defined in /macros/data.asm, but it would make more sense for it to be defined in /macros/coords.asm.

**Comment by Lhivorde** [comment]
In the function `InitScrollingMenuCursor` (in /engine/menus/scrolling_menu.asm) theres a subfunction:
```
.asm_24763
	ret
```
Is there any reason not to rename it to `.ret` or something similar?

**Comment by mid-kid** [comment]
There's many like these. Feel free to point them out and suggest names and/or make a pull request.

**Comment by Rangi42** [comment]
There's never a reason for `.asm_XXXX` labels, we just haven't fixed them all yet. `python3 utils/unnamed.py pokecrystal.sym` will list them all.

**Comment by Rangi42** [comment]
In `PokegearPhoneContactSubmenu`, `ld bc, hBGMapAddress + 1` should be `bccoord -2, -2, 0`.

**Comment by Rangi42** [comment]
The `add_tm` macros can be simplified:

```
add_tm: MACRO
if !DEF(TM01)
TM01 EQU const_value
    enum_start 1
endc
    const TM_\1
    enum \1_TMNUM
ENDM
```

**Comment by Rangi42** [comment]
`hSecondsBackup` is written three times but never read: twice `[hSecondsBackup] = [rLY]` in `_ResetWRAM`, once `[hSecondsBackup] = [hSeconds]` at the end of `VBlank0`. Maybe rename it `hUnusedBackup`.

**Comment by Rangi42** [comment]
Most coordinate-related macros take X and then Y, but `dsprite` is the exception:

```
dsprite: MACRO
; y tile, y pxl, x tile, x pxl, vtile offset, attributes
	db (\1 * 8) % $100 + \2, (\3 * 8) % $100 + \4, \5, \6
ENDM
```

To avoid confusion, I think it can be renamed to `dbsprite` and take the argument order "X tile, Y tile, X pixel, Y pixel", just like `dbpixel`, `ldpixel`, `anim_obj`, etc.

**Comment by mid-kid** [comment]
I think X tile/Y tile+X/Y offset is rather dumb when you're working with object positions, so if anything I'd change it to be absolute positions + 8 for X and +16 for Y.

**Comment by Rangi42** [comment]
That would be fine too; but let's make it a separate PR from this one, with fewer-arg support for `dbpixel`, `ldpixel`, `dsprite`, and any other such macros all at once. (`anim_obj` already works like that, with legacy support for the tile+pixel argument format.)

**Comment by Rangi42** [comment]
(Eventually these would all be good candidates for a generic `pxcoord` function macro.)
