### ISSUE TITLE
Miscellany~

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#709]
- [x] macros/scripts/trade_anims.asm refers to engine/trade/animation.asm; it should say engine/movies/trade_animation.asm
- [x] Haircut brothers' probability comments are wrong in data/events/happiness_probabilities.asm
- [x] Document the home/map.asm:`ReadObjectEvents` bug
- [x] Correct `8 - a` comments to `-8 - a` in engine/gfx/sprites.asm
- [x] Identify `hFFBF`/`hFFC0`/`hFFC1`/`hFFC2` (see Polished Crystal)
- [x] `$7F` in `InitGenderScreen` should be `" "`
- [x] Pass `-p 0x00` to rgblink as well as rgbfix
- [x] Various 26s in engine/events/print_unown.asm should be `NUM_UNOWN`
- [x] Options menu needs a `NUM_OPTIONS` constant; and `ld c, $10` should be `SCREEN_HEIGHT - 2` (likewise for the textbox size 18x16)
- [x] `wCreditsUnusedCD21` is not unused, it's high byte of `dw` `wCreditsPos` (see https://github.com/TheFakeMateo/rgbs/issues/5)
- [x] PlayersHouse2F's `.SetSpawn` callback does not set a spawn point; it should be called `.SetUpTileDecorations`.

**Comment by entrpntr** [comment]
As noted on the discord, rgbds v0.3.9 users of pokecrystal get the following error as of 9076d63:  `Expected constant expression: '__RGBDS_MINOR__' is not constant at assembly time.`

ISSOtm proposed this addition to make the error message less vague: `IF !DEF(__RGBDS_MINOR__) FAIL "Cannot detect RGBDS version; if using 0.3.9 please upgrade to 0.4.0" ENDC`

**Comment by mid-kid** [comment]
Just add `!DEF(__RGBDS_MINOR__)` to the expression.

**Comment by entrpntr** [comment]
Very minor, but since `hSecondsBackup` was renamed to `hUnusedBackup`, would it make sense to do something similar for `$FFA1` as well? It's only written to [here](https://github.com/pret/pokecrystal/blob/ed44d1cdb7e2f389be56a0158f8ce857e02a76b3/engine/overworld/events.asm#L816) and never read from, as far as I can tell. This makes `hMenuReturn` look like it is 2 bytes in that code, when it's only 1.

No idea on what the rename would be; maybe `hUnusedMenuReturn2`? Kinda long, and not sure it's an improvement.

**Comment by Rangi42** [comment]
Sounds good. There are some similar cases too.

- [ ] `ldh [hMenuReturn + 1], a`: give this a label, e.g. `hUnusedFFA1` (like `wCreditsUnusedCD21`) (in engine/overworld/events.asm)
- [ ] `[hRandom + 0]` should be `[hRandomAdd]`; `[hRandom + 1]` should be `[hRandomSub]` (in engine/events/odd_egg.asm)
- `[hMGJoypadPressed + 2]` should have its own label within the `hMG*` union (engine/link/mystery_gift.asm). Its use:

```
	ldh a, [hMGJoypadPressed + 2]
	ld d, a
	ldh a, [rTIMA]
	ldh [hMGJoypadPressed + 2], a
	sub d
	cp $12
	jr c, .asm_104ffd
	set 0, e
	jr .asm_104fff
.asm_104ffd
	res 0, e
```

**Comment by Rangi42** [comment]
```
Joypad::
; Replaced by Joypad, called from VBlank instead of the useless
; joypad interrupt.

; This is a placeholder in case the interrupt is somehow enabled.
	reti
```

should be "Replaced by UpdateJoypad"

**Comment by Rangi42** [comment]
```
SetUpMenu::
	call DrawVariableLengthMenuBox ; ???
	call MenuWriteText
	call InitMenuCursorAndButtonPermissions ; set up selection pointer
	ld hl, w2DMenuFlags1
	set 7, [hl]
	ret
```

Why is this commented "???"?

**Comment by Rangi42** [comment]
Two `$0`s in `SpawnPlayer` should be `PLAYER`.

**Comment by Rangi42** [comment]
This issue will continue to track miscellaneous fixes; use `- [ ]` checkboxes or thumbs-up reactions to mark completed ones.

**Comment by entrpntr** [comment]
A couple small things from going through the core battle code for pokegold:

- `AddLastMobileBattleToLinkRecord` should be probably be renamed? It doesn't appear to be specific to mobile battles.
- The sole, convoluted purpose of `sLinkBattleResults` seems to be in acting as an offset 12 bytes from `sLinkBattleStats` (it's more obvious in Gold/Silver, since the address overlaps with the Active Box struct). The 12 bytes appear to reflect the "opponent" part of the `link_battle_record` struct, whereas the other 6 bytes reflect the "record" part. You can see constant values of 6, 12, and 18 scattered throughout the routine (as well as 5 and 17). No specific proposal, but I'm assuming there's room for improving clarity here.

**Comment by entrpntr** [comment]
The wram addresses in the comments for [these lines](https://github.com/pret/pokecrystal/blob/2d3a94b7c4ba033bdbfa382611a18b71a68349d4/wram.asm#L2854-L2862) are all 1 too high.

**Comment by Rangi42** [comment]
Regarding the happiness probabilities:

```
older = $00 - $4b = 30%
      = $4c - $cb = 50%
      = $cc - $ff = 20%

young = $00 - $99 = 60%
      = $9a - $e5 = 30%
      = $e6 - $ff = 10%

daisy = $00 - $fe = 99.6%
```

**Comment by Rangi42** [comment]
`Unreferenced_Function24b8f` = `Unreferenced_StartMenu_PrintSafariGameStatus` (obviously goes with `StartMenu_PrintBugContestStatus`).

**Comment by entrpntr** [comment]
Probably worth labeling a bit of unused memory. `wPlayerLightScreenCount`, `wEnemySafeguardCount`, `wEnemyLightScreenCount`, `wEnemyReflectCount` are used for labels in the following places:
- [engine/gfx/color.asm](https://github.com/pret/pokecrystal/blob/673b39642b4b0dd17bd51c45ecb504e4d228111b/engine/gfx/color.asm#L280-L300)
- [engine/gfx/sgb_layouts.asm](https://github.com/pret/pokecrystal/blob/d47c5603674414e6afeb34693d6255cfb9dece65/engine/gfx/sgb_layouts.asm#L336)

Doesn't make much sense in the code as is; such that any more insight is needed, this memory is not shared with the above battle counters in the US Gold/Silver releases (residing $100 bytes lower than in Crystal, at `$c602`/`$c605`/`$c606`/`$c607` instead). Guessing it should be unioned in some way and labeled as unused.

**Comment by entrpntr** [comment]
Couple other cleanups that can go with the related recent changes in engine/battle/ai/scoring.asm:

- BASE_STAT_LEVEL (± X): [link 1](https://github.com/pret/pokecrystal/blob/5f197c53f47e19b860df7c92bd1971f2a73f1156/engine/battle/ai/scoring.asm#L2150-L2153)
- NUM_MOVES: [link 1](https://github.com/pret/pokecrystal/blob/5f197c53f47e19b860df7c92bd1971f2a73f1156/engine/battle/ai/scoring.asm#L1048-L1049), [link 2](https://github.com/pret/pokecrystal/blob/5f197c53f47e19b860df7c92bd1971f2a73f1156/engine/battle/ai/scoring.asm#L1514-L1516)

**Comment by Rangi42** [comment]
Report:

> I think in vanilla Crystal, `PokegearPhone_DeletePhoneNumber` copies an extra phone number
> recently put a byte after `wPhoneList` and noticed that when deleting an existing phone number, that byte got copied into the list
> guessing it never presented itself because afaik that byte was normally unused, so copying an extra zero was okay
