### ISSUE TITLE
Proposal: Deal with std scripts in a similar fashion as specials

### ISSUE THREAD

**Issue by mid-kid** [pret/pokecrystal#723]
Currently, std scripts have two arrays: `engine/events/std_scripts.asm:StdScripts` and `constants/std_constants.asm`. This, unfortunately also means every one of them has a different name.
Since these "standard scripts" are more often than not used as a jump or call target, rather than raw values (very much akin to `predef` and `special`), I think it's a good idea to treat them the same way. That means: for each entry, create a label, and when used, defer the calculation of the constant offset to the linker, by using these labels in the macro. This way, you avoid confusion and make the definitions and usage of them easy to `grep` for.

**Comment by Rangi42** [comment]
For example, `jumpstd ReceiveItemScript` instead of `jumpstd receiveitem`.

**Comment by Rangi42** [comment]
Should we bother defining legacy macros for the previous std script constants?

**Comment by mid-kid** [comment]
I think defining them as `oldconstant EQUS "NewLabel"` should work, and isn't too inconvenient. We still support fully unmodified "old" map scripts, breaking this would pretty much make that compatibility useless.
