### ISSUE TITLE
Rename SPRITE_BUENA to SPRITE_BEAUTY?

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#732]
This was done for pokegold, and would make sense here; other named NPCs that use generic sprites, like Mania (rocker) or Mr. Fuji (gramps), don't get the sprite named after them.

If is is changed, should SPRITE_BUENA be added to the legacy macros?

**Comment by mid-kid** [comment]
If renames to things that also exist in crystal happen to pokegold, they should also be updated in pokecrystal. The less differences there's between the repos, the better.
The question is, is this sprite the same one, or a different one?
And yeah, add a legacy constant.

**Comment by Rangi42** [comment]
Yes, it's the same sprite. I'll add it to #731.
