### ISSUE TITLE
Automatically generate the "stadium" data

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#744]
Gold, Silver, and Crystal all have a binary blob of data at the very end of the ROM, apparently related to Stadium 2. In G/S it's 520 bytes; in Crystal it's 544. The format is as follows:

1. A 24-byte prefix only in Crystal:
   1. ASCII "`base`"
   2. Two bytes `01 00`
   3. An 18-byte sequence that's identical among the three final ROMs (1.0, 1.1, and AU) and among the two debug ROMs (1.0 and 1.1) but differs between the final and debug ROMs (it's unclear what it means; maybe it's related to Mobile Stadium)
2. An 8-byte header:
   1. ASCII "`N64PS3`" (presumably for "Nintendo 64 Pokémon Stadium 3", since Stadium G/S was the third Stadium release in Japan)
   2. A two-byte version marker that's unique to each ROM (possibly a checksum of the entire ROM, or of all the subsequent Stadium data?)
3. 512 bytes of actual Stadium data. This looks like it corresponds to the banks of the ROM prior to having the Stadium data patched over it. There are 128 ROM banks, so 4 Stadium bytes per bank. They appear to be local checksums: the byte `FE` corresponds to empty ROM space that's entirely `00`s.

For completeness' sake, it would be nice to reverse-engineer the checksum algorithm and write a tool to run between `rgblink` and `rgbfix` to patch the Stadium data onto the ROM.

Note that these checksums do not appear to be verified by Stadium 2; the hack Crystal Clear removed this binary data, but is still compatible with Stadium 2.

**Comment by mid-kid** [comment]
Posting WIP script that calculates most of the checksums in stadium2.bin, based on a provided ROM:
```python
#!/usr/bin/env python3

from sys import argv

file = bytearray(open(argv[1], "rb").read())

# Clear checksums and data
for i in range(0x220):
    file[0x1FFDE0 + i] = 0
file[0x14E] = 0
file[0x14F] = 0

# Fill static footer values
header = [
    0x62, 0x61, 0x73, 0x65, 0x01, 0x00, 0xBF, 0x6B, 0x40, 0x11, 0x00, 0x22, 0x00, 0x3A, 0xF3, 0x38,
    0x18, 0xFF, 0xFF, 0x0F, 0x07, 0x10, 0x68, 0x07, 0x4E, 0x36, 0x34, 0x50, 0x53, 0x33
]
for i, x in enumerate(header):
    file[0x1FFDE0 + i] = x

# Calculate all checksums
sums = []
for x in range(0x100):
    count = 0xFEFE
    for y in range(0x2000):
        count += file[x * 0x2000 + y]
    file[0x1FFDE0 + 0x20 + 2 * x + 0] = (count & 0xFF00) >> 8
    file[0x1FFDE0 + 0x20 + 2 * x + 1] = (count & 0x00FF) >> 0
    sums.append(count & 0xFFFF)

print(" ".join(("%04X" % x) for x in sums))

# TODO: Calculate 0x1E and 0x1F values
```

**Comment by Rangi42** [comment]
I can port that to C once it's complete.

**Comment by Rangi42** [comment]
All "version marker" `0x1E-0x1F` byte values:

- pokegold: `E8 6E`
- pokesilver: `79 50`
- pokegold_debug: `9D 4A`
- pokesilver_debug: `F8 A1`
- pokecrystal: `59 94`
- pokecrystal11: `7D 43`
- pokecrystal_debug: `FC 4C`
- pokecrystal11_debug: `89 C1`
- pokecrystal_au: `1F 52`

**Comment by Rangi42** [comment]
So far I have no idea how those `0x1E-0x1F` bytes are derived. In the meantime, should we add a tool for the bank checksums, and just hard-code those bytes per ROM as tool arguments in the Makefile?

**Comment by Rangi42** [comment]
`CRYSTAL_ps3_010309r.bin` vs `CRYSTAL_ps3_010312r.bin` differ in only one ROM byte.

- The byte at offset `0x9E47B` (`27:647B`): `0A` → `05` (−5)
- The checksum for the second half of bank $27: `875C` → `8757` (−5)
- The checksum for bank $7F, which contains the other checksums: `1CA9` → `1CA4` (−5)
- The 0x1E-0x1F value: `E9 60` → `84 49`
- (also the `rgbfix` 0x14E-0x14F ROM header checksum: `5B 5F` → `5A D4`)

**Comment by mid-kid** [comment]
After googling and learning about CRC for a bit, I found a program called "CRC RevEng". I decided to run it on the stadium files, after stripping away everything but the halfbank checksum table, and writing the 0x1E-0x1F checksum at the end of the file, going by the assumption that this was a checksum of the checksum table.
And lo and behold, there's a result!
```
$ ./reveng -w 16 -f -s stadium2{,_11,_au,_jp}.bin
width=16  poly=0xe1c3  init=0x7f7f  refin=true  refout=true  xorout=0x0000  check=0x6e3b  residue=0x0000  name=(none)
```

After googling and messing around, I cobbled together the following snippet by reversing the bits on the `poly` and `init` result:
```python
file = open("stadium2check.bin", "rb").read()

table = []
polynomial = 0xc387
for x in range(256):
    k = x
    crc = 0
    for y in range(8):
        if (crc ^ k) & 1:
            crc = (crc >> 1) ^ polynomial
        else:
            crc >>= 1
        k >>= 1
    table.append(crc & 0xFFFF)

crc = 0xfefe
for byte in file:
    crc = (crc >> 8) ^ table[(crc & 0xFF) ^ byte]
print("%04X" % crc, "%04X" % (crc ^ 0xffff))
```
This manages to calculate the 0x1E-0x1F checksum fine for every single released ROM that contains this data, so I've amended this to the script above.
