### ISSUE TITLE
Length of section?

### ISSUE THREAD

**Issue by 0x3DD3CE** [pret/pokecrystal#753]
I added some maps and their scripts but I got this.

layout.link(111): Sections would extend past the end of ROMX

What have I done wrong/extra?

Any help will be appreciated!

**Comment by mid-kid** [comment]
https://github.com/pret/pokecrystal/blob/master/FAQ.md#section-is-too-big-or-unable-to-place-section-in-bank
The github issue tracker isn't for questions or help hacking. Feel free to join the Discord or IRC.
