### ISSUE TITLE
Identify 2D menu constants

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#757]
PR #756 identifies some 2D menu data, but the roles of the bitflag constants are not known yet.

**Comment by mid-kid** [comment]
w2DMenuFlags1 is mostly known and documented in both `docs/menu.md` and `wram.asm`, it just needs constants and for w2DMenuFlags2 to be documented. Also, the relationship of this vs `_2DMenu` is unknown.

**Comment by Rangi42** [comment]
These were identified as part of https://github.com/pret/pokegold/pull/120, which will be ported to pokecrystal after review+merge.
