### ISSUE TITLE
Bug: CheckOwnMonAnywhere should also check wBreedMon1 and wBreedMon2

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#763]
Currently you cannot unlock Ho-Oh if one of the legendary beasts is in the Day-Care.

**Comment by mid-kid** [comment]
Is this truely a bug? I mean it's true that this is the only place other than the PC where you can store your mon, besides stadium or just trading it away (or the temporary slot in the jp-only trade corner of the PCC), but the mon technically isn't in your possession while in the day care, it's in custody of the caretakers, and you have to pay to retrieve it.

**Comment by Rangi42** [comment]
Interesting point. I wonder if the search routine was written that way on purpose, or if they wrote the daycare code later and forgot to update it?

**Comment by iimarckus** [comment]
The fact that it’s Crystal code is what makes me lean more towards oversight.
