### ISSUE TITLE
Bug: Some NPCs have inconsistent overworld sprites

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#764]
- UnionCaveB2F.asm: `TrainerCooltrainermNick` uses `SPRITE_ROCKER`, not `SPRITE_COOLTRAINER_M`
- LakeOfRage.asm: `TrainerFisherAndre` and `TrainerFisherRaymond` use `PAL_NPC_BLUE`, not `PAL_NPC_GREEN`
- FastShipCabins_SE_SSE_CaptainsCabin.asm: `TrainerPsychicRodney` uses `SPRITE_SUPER_NERD`, not `SPRITE_YOUNGSTER`
- Route44.asm: `TrainerBirdKeeperVance1` uses `PAL_NPC_GREEN`, not `PAL_NPC_BLUE`
- Route44.asm: `TrainerPokemaniacZach` uses `PAL_NPC_GREEN`, not `PAL_NPC_BLUE`
- Route13.asm: `TrainerHikerKenny` uses `PAL_NPC_RED`, not `PAL_NPC_BROWN`
- FuchsiaPokecenter1F: `FuchsiaPokecenter1FNurseScript` uses `PAL_NPC_GREEN`, not `PAL_NPC_RED`
- NationalParkBugContest.asm and Route36NationalParkGate.asm: `BugCatchingContestant1AScript` and `BugCatchingContestant1BScript` (`BUG_CATCHER DON`) uses `SPRITE_YOUNGSTER` and `PAL_NPC_RED`, not `SPRITE_BUG_CATCHER` and `PAL_NPC_BROWN`
- NationalParkBugContest.asm and Route36NationalParkGate.asm: `BugCatchingContestant2AScript` and `BugCatchingContestant2BScript` (`BUG_CATCHER ED`) uses `SPRITE_YOUNGSTER` and `PAL_NPC_GREEN`, not `SPRITE_BUG_CATCHER` and `PAL_NPC_BROWN`
- NationalParkBugContest.asm and Route36NationalParkGate.asm: `BugCatchingContestant3AScript` and `BugCatchingContestant3BScript` (`COOLTRAINERM NICK`) uses `SPRITE_ROCKER` and `PAL_NPC_BLUE`, not `SPRITE_COOLTRAINER_M` and `PAL_NPC_RED`
- NationalParkBugContest.asm and Route36NationalParkGate.asm: `BugCatchingContestant4AScript` and `BugCatchingContestant4BScript` (`POKEFANM WILLIAM`) uses `PAL_NPC_BROWN`, not `PAL_NPC_RED`
- NationalParkBugContest.asm and Route36NationalParkGate.asm: `BugCatchingContestant5AScript` and `BugCatchingContestant5BScript` (`BUG_CATCHER BENNY`) uses `SPRITE_YOUNGSTER` and `PAL_NPC_RED`, not `SPRITE_BUG_CATCHER` and `PAL_NPC_BROWN`
- NationalParkBugContest.asm and Route36NationalParkGate.asm: `BugCatchingContestant7AScript` and `BugCatchingContestant7BScript` (`PICNICKER CINDY`) uses `PAL_NPC_BLUE`, not `PAL_NPC_GREEN`
- NationalParkBugContest.asm and Route36NationalParkGate.asm: `BugCatchingContestant8AScript` and `BugCatchingContestant8BScript` (`BUG_CATCHER JOSH`) uses `SPRITE_YOUNGSTER` and `PAL_NPC_RED`, not `SPRITE_BUG_CATCHER` and `PAL_NPC_BROWN`
- NationalParkBugContest.asm and Route36NationalParkGate.asm: `BugCatchingContestant9AScript` and `BugCatchingContestant9BScript` (`YOUNGSTER SAMUEL`) uses `PAL_NPC_GREEN`, not `PAL_NPC_BLUE`

**Comment by iimarckus** [comment]
Regarding Nick, don’t forget that in the SW97 prototype he was the player’s brother, and his unique sprite (for a Cooltrainer) is probably a remnant of that role.

He has another inconsistency: his palette is red in Union Cave and blue in the Bug‐Catching Contest.
