### ISSUE TITLE
Rename wKickCounter

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#766]
It controls variations of many different moves (charge attacks, multi-hit attacks, etc), not just Triple Kick.

**Comment by mid-kid** [comment]
`wMultihitCounter`?

**Comment by Rangi42** [comment]
It's used by any animation that has `anim_if_param_equal`, which includes `BattleAnim_ThrowPokeBall` (`anim_if_param_equal MASTER_BALL, .MasterBall`, etc). So, `wBattleAnimParam`? (About as vague as `wScriptVar`.)

**Comment by Rangi42** [comment]
...lol, we already define `wBattleAnimParam` as an alias for `wKickCounter` (aka `wPresentPower` as well).
