### ISSUE TITLE
BUG: Heavy Ball has wrong result for Kadabra(64)/Tauros(128)/Sunflora(192)

### ISSUE THREAD

**Issue by SnDream** [pret/pokecrystal#769]
`GetPokedexEntryBank` in **item_effects.asm** is buggy.

```
GetPokedexEntryBank:
	push hl
	push de
	ld a, [wEnemyMonSpecies]
	; dec a      ; BUG: Get wrong bank for Kadabra(64)/Tauros(128)/Sunflora(192)
	rlca
	rlca
	maskbits NUM_DEX_ENTRY_BANKS
	ld hl, .PokedexEntryBanks
	ld d, 0
	ld e, a
	add hl, de
	ld a, [hl]
	pop de
	pop hl
	ret
```

Other functions like `GetDexEntryPointer` or `PokedexShow_GetDexEntryBank` execute `dec a` and works correctly.

The bug changed the weight of Tauros to 3392.3lb ("ED" in Sunkern's species name), and make catch rate for 40 (should be -20).

I can't find any documents that records this bug, could someone add it to Bugs and Glitches?

**Comment by Rangi42** [comment]
Congratulations, that's another bug only discovered due to the disassembly! And it means that 4 out of 7 Apricorn Balls were bugged.
