### ISSUE TITLE
Unknown Symbol "wc296"

### ISSUE THREAD

**Issue by lorulians** [pret/pokecrystal#770]
While following the custom Old Pokedex Order tutorial, trying to build a new ROM gives me this error:

```error: main.asm(184) -> engine/pokedex/pokedex_2.asm(101): Unknown symbol "wc296"```
```error: main.asm(183) -> engine/pokedex/pokedex.asm(1556): Unknown symbol "wc296"```
```error: main.asm(183) -> engine/pokedex/pokedex.asm(1540): Unknown symbol "wc296"```
```Linking failed with 3 errors```
```make: *** [Makefile:124: pokecrystal.gbc] Error 1```

If I remove the lines with `wc296` the ROM builds fine, but then the numbers of Pokemon don't look right. I've looked through the issues and have found similar unknown symbol issues, but none seem to have anything that could help me with this issue in particular.

**Comment by iimarckus** [comment]
That tutorial is out of date, `wc296` was renamed to `wUnusedBCDNumber` in revision 45e3f6aca90dc4dee962f5aafe4eb5590122361c.

**Comment by lorulians** [comment]
Oh, okay, thank you :D!
