### ISSUE TITLE
Create "data/overworld/" for "tileset-related" data

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#774]
`data/tilesets/` is solely for grouping all the `*_collision.asm` and `*_metatiles.bin` files. I'm thinking of adding `data/overworld/` to group these current files:

- `collision_permissions.asm`
- `events/collision_stdscripts.asm`
- `events/field_move_blocks.asm`

(A while ago in b5a7e7de3e6b75e95967edd28b9c2af5959cd136 I did something similar, but it went overboard and factored out some pointer tables that are more convenient with their related code in `engine/`, so 11dc805de0118e8276936ad12a0222e88adbe336 reverted it.)

Thoughts? Is there a better name than `data/overworld/`? Note that pokered keeps this sort of data in `data/tilesets/`, but (a) it has a lot more such data, (b) its metatiles.bin equivalents are in `gfx/blocksets/`, and (c) it has no unified "collision" data.

**Comment by mid-kid** [comment]
If there's a `data/overworld` it should correspond to whatever's used in `engine/overworld`. I believe that applies to the files you've listed, but I'm sure there's more.

**Comment by Rangi42** [comment]
Not quite. Here are those three files' current `INCLUDE`s:

- main.asm:206:`INCLUDE "data/collision_permissions.asm"`
- engine/events/overworld.asm:274:`INCLUDE "data/events/field_move_blocks.asm"`
- engine/events/std_collision.asm:26:`INCLUDE "data/events/collision_stdscripts.asm"`

And the files in engine/overworld/ have `INCLUDE`s for files in data/decorations/, data/wild/, data/sprites/, some data/maps/, and even data/items/pocket_names.asm.

If "data/overworld" is an inaccurate name, it could be "data/collision". Obviously accurate for two of the three files, and even for field_move_blocks.asm, that's dependent on the blocks using `COLL_CUT_TREE` or `COLL_WHIRLPOOL`.
