### ISSUE TITLE
Australian debug ROM

### ISSUE THREAD

**Issue by Sonic-The-Hedgehog-LNK1123** [pret/pokecrystal#787]
Are there any plans to disasm the Australian debug ROM?

I noticed the following ROM is missing from the disassembly:

* CRYSTAL_ps3_australia_010710d.bin `sha1: bff2d430d70ada56b15392db85cc48eef3acf7b9`

**Comment by mid-kid** [comment]
There isn't really anything to disassemble, because the AU version hardly changes a couple of lines of text.
You can generate the hash you're describing with these commands:
```
make tidy
make RGBASMFLAGS='-D_CRYSTAL11 -D_CRYSTAL_AU -D_DEBUG' pokecrystal_au_base=dbg crystal_au
```

IIRC it was decided it was redundant to add the ROM to the build configurations, due to this.

**Comment by Sonic-The-Hedgehog-LNK1123** [comment]
I see it's somewhat redundant. But, having build configurations for 5 out of 6 ROMs just feels incomplete to me.

I suggest that this configuration either added or that it will be stated somewhere it won't be added.

**Comment by Rangi42** [comment]
There were dozens of leaked builds; no need to list the ones that won't be added. US 1.0 and 1.1 are the "main" ROMs so they get debug builds.
