### ISSUE TITLE
Rename GetFarHalfword to GetFarWord?

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#796]
`GetFarHalfword` "retrieves a halfword from a:hl, and returns it in hl." This is potentially confusing because 16-bit values as stored in `hl` are generally referred to as "words". (`dw`, `GetFarWRAMWord`, `hMGExchangedWord`, "`bigdw: MACRO ; big-endian word`")

@aaaaaa123456789 @mid-kid

**Comment by Caverns4** [comment]
This did in fact confuse me. I never used the code because I thought "Wouldn't that just be the same thing as "getFarByte" except it eats hl? GetFarWord would be better I think.

**Comment by Kroc** [comment]
Does the documentation / readme say anywhere that to 8-bit systems a "word" is 16-bits, not 32 ("long") or 64 ("quadword"|"longlong")?

**Comment by Rangi42** [comment]
Yes, Pan Docs and rgbds docs refer to 16-bit words.
