### ISSUE TITLE
Bug: Town Map does not place the cursor on the Fast Ship icon

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#812]
From SatoMew:

Possible oversight in `TownMap_InitCursorAndPlayerIconPositions`:

```
.FastShip:
    ld [wPokegearMapPlayerIconLandmark], a
    ld a, LANDMARK_NEW_BARK_TOWN
    ld [wPokegearMapCursorLandmark], a
    ret
```

Should be:

```
.FastShip:
    ld [wPokegearMapPlayerIconLandmark], a
    ld a, LANDMARK_FAST_SHIP
    ld [wPokegearMapCursorLandmark], a
    ret
```

Original:

![image](https://user-images.githubusercontent.com/35663410/111055313-b25bca00-8442-11eb-8a6d-c0c43a7a028a.png)

Intended:

![image](https://user-images.githubusercontent.com/35663410/111055315-b687e780-8442-11eb-927f-9c7047a4db0a.png)

**Comment by coltongit** [comment]
Fixed in #850
