### ISSUE TITLE
Add list macros to allow checking lengths of uneven lists

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#815]
Tables with fixed-width entries now have their sizes checked:

```
PokemonNames::
	table_width NAME_LENGTH - 1, PokemonNames
	db "BULBASAUR@"
	db "IVYSAUR@@@"
	db "VENUSAUR@@"
	...
	db "LUGIA@@@@@"
	db "HO-OH@@@@@"
	db "CELEBI@@@@"
	assert_table_length NUM_POKEMON
```

However, lists of uneven names, each ending with `"@"`, cannot be checked in the same way:

```
MoveNames::
	db "POUND@"
	db "KARATE CHOP@"
	db "DOUBLESLAP@"
	...
	db "ROCK SMASH@"
	db "WHIRLPOOL@"
	db "BEAT UP@"
```

```
RoamMaps:
; there are NUM_ROAMMON_MAPS entries
	; start map, ...other maps
	roam_map ROUTE_29, ROUTE_30, ROUTE_46
	...
	roam_map ROUTE_46, ROUTE_45, ROUTE_29
	db -1 ; end
```

I propose adding `list_start`, `li`, and `assert_list_length`. `list_start` and `assert_list_length` would be like `table_width` and `assert_table_length`. `li` would be like `db` (name chosen for brevity, and to be like HTML `<li>`).

```
list_start: MACRO
list_index = 0
ENDM

li: MACRO
list_index = list_index + 1
	db \1
ENDM

assert_list_length: MACRO
assert list_index == \1
ENDM
```

```
MoveNames::
	list_start MoveNames
	li "POUND@"
	li "KARATE CHOP@"
	li "DOUBLESLAP@"
	...
	li "ROCK SMASH@"
	li "WHIRLPOOL@"
	li "BEAT UP@"
	assert_list_length NUM_ATTACKS
```

```
;; the roam_map macro would increment list_index itself

RoamMaps:
	list_start RoamMaps
	; start map, ...other maps
	roam_map ROUTE_29, ROUTE_30, ROUTE_46
	...
	roam_map ROUTE_46, ROUTE_45, ROUTE_29
	assert_list_length NUM_ROAMMON_MAPS
	db -1 ; end
```

**Comment by Rangi42** [comment]
@aaaaaa123456789 @dannye any suggestions for these macros' names or behavior?

**Comment by dannye** [comment]
Sounds like a great idea to me.
Do you imagine there being any scenario where the `db \1` in `li` is not sufficient, other than scenarios that already use a specialized macro for the table?

**Comment by Rangi42** [comment]
No, I think all the uneven tables are either `db "string@"`, or a more complex data structure that already has a defining macro.

In case some table entries want to split their item into pieces, like `db "CHAR", "MAN", "DER", "@"`, then `li` can just do:

```
li: MACRO
    rept _NARG
        db \1
        shift
    endr
list_index = list_index + 1
ENDM
```

Which is one of the things rgbds 0.5.0 will simplify:

```
li: MACRO
    db \#  ; expands to all macro args, comma-separated
list_index = list_index + 1
ENDM
```

**Comment by aaaaaa123456789** [comment]
I'd perhaps want to incorporate the delimiter/terminator into the macro, because an entry without a delimiter is just as bad as a missing entry.
