### ISSUE TITLE
Document unused trainers

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#819]
Some trainers' event flags + parties are unused. They include:

- `SWIMMERF`: `LISA`, `JILL`, `MARY`, `KATIE`, `TARA`, `JODY`
- `SWIMMERM`: `HAL`, `PATON`, `DARYL`, `WALTER`, `TONY`, `RICK`, `JAMES`, `LEWIS`

**Comment by SatoMew** [comment]
There's also:

- `FIREBREATHER`: `DICK`, `NED`
