### ISSUE TITLE
"Remove the artificial save delay" has incorrect code

### ISSUE THREAD

**Issue by MasterDriverRex** [pret/pokecrystal#833]
I initially found your tutorial on ["Remove the artificial save delay"](https://github.com/pret/pokecrystal/wiki/Remove-the-artificial-save-delay) a little confusing because it refers to incorrect text at two points.

Section 2 contains the following code boxes:

-Text_SavingDontTurnOffThePower:
-	; SAVING… DON'T TURN OFF THE POWER.
-	text_far UnknownText_0x1c456d
-	text_end

-UnknownText_0x1c456d::
-	text "SAVING… DON'T TURN"
-	line "OFF THE POWER."
-	done

These should be, for save.asm and common_3.asm respectively,

SavingDontTurnOffThePowerText:
	text_far _SavingDontTurnOffThePowerText
	text_end

_SavingDontTurnOffThePowerText::
	text "SAVINGâ€¦ DON'T TURN"
	line "OFF THE POWER."
	done

Section 5 contains a similar error:

-Text_AlreadyASaveFile:
-	; There is already a save file. Is it OK to overwrite?
-	text_far UnknownText_0x1c45a3
-	text_end

-UnknownText_0x1c45a3::
-	text "There is already a"
-	line "save file. Is it"
-	cont "OK to overwrite?"
-	done

These should be:

AlreadyASaveFileText:
	text_far _AlreadyASaveFileText
	text_end

_AlreadyASaveFileText::
	text "There is already a"
	line "save file. Is it"
	cont "OK to overwrite?"
	done

**Comment by MasterDriverRex** [comment]
I dunno how to make "insert code" work for this...my apologies.

**Comment by Pokechu22** [comment]
Use 3 backticks instead of one when you have multiple lines of code.

**Comment by Idain** [comment]
Feel free to edit the tutorial so that it includes the latest version of those steps.

**Comment by aaaaaa123456789** [comment]
It might be easier to just mention which labels to rename, since your large post is unreadable.

**Comment by Idain** [comment]
I took some of my free time to update the tutorial. If someone sees something that can be fixed, feel free to edit it.

https://github.com/pret/pokecrystal/wiki/Remove-the-artificial-save-delay
