### ISSUE TITLE
Cannot "make" Crystal - rgbasm error.

### ISSUE THREAD

**Issue by AlternisDim20** [pret/pokecrystal#835]
I'm trying to "make" Crystal, but when I try, the following error appears:
```
rgbasm -o rgbdscheck.o rgbdscheck.asm
make: rgbasm: Command not found
make: *** [Makefile:86: rgbdscheck.o] Error 127
```
I've tried to follow the confusing [RGBDS instructions](https://rgbds.gbdev.io/install/source); I've cloned the RGBDS repo to my system (git clone https://github.com/gbdev/rgbds), then entered the new /rgbds/ directory, ran "git checkout v0.5.1" and "make", which resulted in "DEFS=-Dlr.type=ielr -Dparse.lac=full -Dparse.error=verbose -Dapi.token.raw=true".

But the above error still persists. I have no idea what to do.

**Comment by Kongo761** [comment]
Did you use "sudo make install" after "make" in /rgbds/?
