### ISSUE TITLE
[wiki Issue] Can't finish adding NB player gender from Rangi's fork

### ISSUE THREAD

**Issue by FieryMewtwo** [pret/pokecrystal#836]
When I was trying to add the NB character code from Rangi42/pokecrystal, I realized that the way that oam.asm works is different between the two repos. I can't figure out what was changed to do it myself, and I'm not very experienced with disassembly hacking or assembly(about a 5 out of 10 understanding or so)

I would do this on Discord, but I "accidentally" got my token stolen and my account locked. Discord isn't being helpful about it, and I really don't want to make an alt.

**Comment by FieryMewtwo** [comment]
![image](https://user-images.githubusercontent.com/77066742/120041288-f7b97d80-bfd5-11eb-9b79-dbe36982a1fe.png)

**Comment by FieryMewtwo** [comment]
![image](https://user-images.githubusercontent.com/77066742/120042132-837fd980-bfd7-11eb-8f59-bb216c47a35b.png)

**Comment by Asday** [comment]
Copy paste code in code fences, don't screenshot it.

Also, just ask on discord dude.  This is not really an issue, and the fact that _you_ don't want to make a discord account doesn't make it one.
