### ISSUE TITLE
Replacing Suicune with Entei works in most places except Cianwood City.

### ISSUE THREAD

**Issue by FirstTimeN00b** [pret/pokecrystal#841]
Hello, I have begun the process of swapping Suicune with Entei in Crystal. Mostly seems to be a case of swapping the names in most encounters. This has worked in the burned tower but when it comes to the Cianwood encounter, Suicune has not been replaced with Entei but a blue player sprite.

The issue would be found it in the CianwoodCity.asm file I would assume.

Edit (I have also found this to be the case on the route 42 encounter yet the Tin Tower is fin)

**Comment by aaaaaa123456789** [comment]
This is not an issue with the repository, as its goal is to reconstruct the code for the original game, not to modify it.

**Comment by iimarckus** [comment]
Yes, questions about editing should go to discord.
