### ISSUE TITLE
Edit the GitHub Actions workflow to only run under pret

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#856]
Personal forks of pokecrystal (and gold, red, and yellow) shouldn't keep running a `make compare` CI build that will almost certainly fail.

**Comment by Idain** [comment]
That explains why it always fails for me. Huh.

**Comment by mid-kid** [comment]
We alread have `github.repository_owner == 'pret'` checks in the actions.yml file, this should be trivial.
