### ISSUE TITLE
"Stadium 2 Checksums" section has duplicate attributes

### ISSUE THREAD

**Issue by aaaaaa123456789** [pret/pokecrystal#857]
The section is both fixed in its header (`ROMX[$7DE0], BANK[$7F]`) and fixed in place by the linker script. While these settings don't conflict, it's a bad idea to specify the same attributes twice. Only one should remain — preferrably the linker script, since that's where all other sections are fixed in place.

**Comment by Rangi42** [comment]
The space reserved for the Stadium checksums would never be relocated, only removed, so it doesn't need to be capable of floating.

**Comment by Rangi42** [comment]
The rst and interrupt sections also have their addresses redundantly hard-coded. Since they're already consistently like that, I'm going to close this.
