### ISSUE TITLE
docs/pic_animations.md says that `dorepeat` starts from 0...

### ISSUE THREAD

**Issue by aaaaaa123456789** [pret/pokecrystal#859]
...but it really starts from 1.

**Comment by aaaaaa123456789** [comment]
...nevermind, it _does_ start from 0, but in a confusing way, since the jump points at the command _after_ the loop start marker. I guess this is only really relevant if someone mismatches `setrepeat`/`dorepeat` commands. Maybe it should be made clearer in the documentation?

**Comment by Rangi42** [comment]
```diff
-Repeats from command #I (starting from 0)
+Repeats from command #I (with the first command being #0)
```

Then I think it's clear enough just by considering the commands' indexes, e.g. articuno:

```
	frame 5, 08  ; 0
	setrepeat 2  ; 1
	frame 1, 10  ; 2
	frame 2, 10  ; 3
	frame 3, 10  ; 4
	dorepeat 2   ; 5 - repeats from 2 to here
	frame 5, 12  ; 6
	endanim      ; 7
	; visible index sequence is 0, 2, 3, 4, 2, 3, 4, 2, 3, 4, 6
	; visible frames are thus 5, 1, 2, 3, 1, 2, 3, 1, 2, 3, 5
```
