### ISSUE TITLE
Bug: A hatching Unown egg would not show the right letter

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#862]
`GetEggFrontpic` and `GetHatchlingFrontpic` use `wBattleMonDVs`, but that's not initialized. They should use the `wCurPartyMon`th `wPartyMon#DVs` instead.

**Comment by mid-kid** [comment]
You'd this would've been noticed sooner lol.

**Comment by Rangi42** [comment]
Shockslayer found it, I doubt anyone else had Unown eggs. :P

**Comment by Idain** [comment]
I think this issue can be closed now, don't you think @Rangi42 ?

**Comment by Rangi42** [comment]
Yep! (If a PR commit says "Fixes #N", it will automatically close issue N on merge.)

**Comment by Idain** [comment]
I didn't know that. Thanks for the info!
