### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by legendstrike** [pret/pokecrystal#864]
Everything went fine until I tried to install the ROM (with Cygwin). There, I encountered the error "No rule to make target jN". How do I fix this and build the ROM?

**Comment by Rangi42** [comment]
GitHub issues are for pokecrystal itself. Please ask for support on Discord #pokecrystal (see the README for a link). Also provide more details, like just what commands you entered to get that error message.

**Comment by aaaaaa123456789** [comment]
Make sure to copy commands exactly! `make j12` isn't the same as `make -j12`.
