### ISSUE TITLE
Add legacy music command names to the docs

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#873]
These are used in many custom songs, so it would be helpful to see the correspondence between legacy and modern music commands.

**Comment by Idain** [comment]
I thought the documentation inside the code was enough, but it's not a bad idea for those who want it in a more readable format.

**Comment by mid-kid** [comment]
I'd delegate this to the wiki or comments in the legacy macros file. I wouldn't bother documenting a format people shouldn't use anymore, especially once https://github.com/pret/pokecrystal/issues/759 is implemented.

**Comment by coltongit** [comment]
> I'd delegate this to the wiki or comments in the legacy macros file. I wouldn't bother documenting a format people shouldn't use anymore, and instead implement #759 to quell the only reason people would use the old format.

So have PR #950 close this issue as well?

**Comment by coltongit** [comment]
Addressed in https://github.com/pret/pokecrystal/wiki/Add-audio-scripts-to-use-modern-audio-files-with-legacy-pokecrystal, edit as you wish

**Comment by coltongit** [comment]
With the new edits to the article above, it felt best to solve this issue the way it now describes. This issue may be closed along with #759 once the wiki page itself is approved.

**Comment by mid-kid** [comment]
Please give rangi a chance to reply. She may still want to resolve this in a different manner.

**Comment by coltongit** [comment]
And that I'm OK with

**Comment by coltongit** [comment]
Any updates on this? Still looking for Rangi's input on this one

**Comment by Rangi42** [comment]
Isn't there a wiki article for this now?

**Comment by coltongit** [comment]
Yep, it was added in the same wiki article as #759. If you feel that's sufficient we can close this issue
