### ISSUE TITLE
Change how `*_WILDDATA_LENGTH` constants' values are represented

### ISSUE THREAD

**Issue by Idain** [pret/pokecrystal#874]
Currently, these values are represented as it follows:

```asm
 GRASS_WILDDATA_LENGTH EQU 2 + (1 + NUM_GRASSMON * 2) * 3
 WATER_WILDDATA_LENGTH EQU 2 + (1 + NUM_WATERMON * 2) * 1
```
But they don't represent how the bytes in an encounter table are organized. For example, let's look at Sprout Tower 2F's encounter table:

```asm
	def_grass_wildmons SPROUT_TOWER_2F
	db 2 percent, 2 percent, 2 percent ; encounter rates: morn/day/nite
	; morn
	db 3, RATTATA
	db 4, RATTATA
	db 5, RATTATA
	db 3, RATTATA
	db 6, RATTATA
	db 5, RATTATA
	db 5, RATTATA
	; day
	db 3, RATTATA
	db 4, RATTATA
	db 5, RATTATA
	db 3, RATTATA
	db 6, RATTATA
	db 5, RATTATA
	db 5, RATTATA
	; nite
	db 3, GASTLY
	db 4, GASTLY
	db 5, GASTLY
	db 3, RATTATA
	db 6, GASTLY
	db 5, RATTATA
	db 5, RATTATA
	end_grass_wildmons
```

`def_grass_wildmons` redefines constants and uses another macro inside, `map_id`, which takes two (2) bytes; after that, three (3) bytes are declared in the table to represent encounter rates and finally it declares three sets of seven encounters per time of day, with each encounter taking two bytes [(`NUM_GRASSMON` * 2) * 3]. Something similar happens with water encounter tables, but instead of using three bytes for encounter rates it only uses one (1) and therefore there's only one encounter table [(`NUM_WATERMON` * 2) * 1].

My suggestion is to change these constants to reflect better how bytes are handled, as follows:

```diff
-GRASS_WILDDATA_LENGTH EQU 2 + (1 + NUM_GRASSMON * 2) * 3
-WATER_WILDDATA_LENGTH EQU 2 + (1 + NUM_WATERMON * 2) * 1
+GRASS_WILDDATA_LENGTH EQU 2 + 3 + ((NUM_GRASSMON * 2) * 3)
+WATER_WILDDATA_LENGTH EQU 2 + 1 + ((NUM_WATERMON * 2) * 1)
```

What do you think?

**Comment by Rangi42** [comment]
Good idea! I'd just omit the extra parentheses, and probably the `* 1` too:

```
GRASS_WILDDATA_LENGTH EQU 2 + 3 + NUM_GRASSMON * 2 * 3
WATER_WILDDATA_LENGTH EQU 2 + 1 + NUM_WATERMON * 2
```

Similar changes would be done in gold, red, and yellow.

**Comment by Idain** [comment]
I put `* 1` to make more clear that it's only one encounter table, especially to those trying to understand the code.

**Comment by Rangi42** [comment]
I think it would be more confusing to someone who's new to asm, since they'd wonder if multiplying by one actually makes a difference.

**Comment by Idain** [comment]
In that case I think there are other instances in the code where some numbers are multiplied by one and they should be changed in the future. I'd like to hear more opinions to see whether this issue's PR should have the `* 1` or not.
