### ISSUE TITLE
Rename `ENGINE_FISH_SWARM` to `ENGINE_QWILFISH_SWARM`

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#875]
This would match `ENGINE_DUNSPARCE_SWARM` and `ENGINE_YANMA_SWARM`.

**Comment by Rangi42** [comment]
(pokegold had a single `ENGINE_SWARM` flag applicable to all six swarms; Crystal kept three swarms, each with their own flag.)

**Comment by Idain** [comment]
Why did someone nane it "fish" in the first place? That's weird.

**Comment by mid-kid** [comment]
Probably on a hunch that there was one flag for water swarms and one for grass swarms.
It's common to make incomplete assumptions when still reverse engineering code.

**Comment by Pokechu22** [comment]
https://github.com/pret/pokecrystal/blob/0817dee42ca7482db81a8eb66413e77ad903888f/engine/phone/scripts/ralph.asm#L48-L56
https://github.com/pret/pokecrystal/blob/0817dee42ca7482db81a8eb66413e77ad903888f/engine/events/fish.asm#L113-L125

Is `FISHSWARM_REMORAID` unused?  I couldn't find anything that used it.

**Comment by Rangi42** [comment]
Crystal removed the Remoraid swarm from G/S. (Also the Snubbull and Marill swarms.)
