### ISSUE TITLE
"palfix.py" doesn't work with Python 3.9+

### ISSUE THREAD

**Issue by Idain** [pret/pokecrystal#881]
This happens because palfix.py imports png.py from pokemontools, which uses a method called "tostring()". This method has been deprecated and replaced with "tobytes()" in Python 3. This is problematic for new people trying to use the palfix.py script, especially for those with very little programming knowledge.

The solution is simple and I would've made a PR right away, but I wanted to know how many people still use Python 2.7 and their opinions about this.

**Comment by mid-kid** [comment]
Specifically this is about python 3.9+, as this script has always been compatible with python 3, it only broke recently. From what I gathered, the changed equivalent for this function was backwards compatible, but it should be tested.

Alternatively, this might be a good excuse to update png.py with the newest version of PyPNG. Since upstream keeps this module compatible with many python versions, it saves us having to test.

**Comment by Rangi42** [comment]
The latest png.py requires Python 3, so tools/pokemontools/lz.py, tools/pokemontools/gfx.py, and tools/gfx.py would all need updating to not assume Python 2 (e.g. `print` function vs statement). We may as well make sure that all the other tools/\*.py scripts work with Python 3 as well.

**Comment by Idain** [comment]
I don't mind the change as long as every Python script works with Python 3. I can't speak about the compression algorithms you mentioned since I never worked with them before, so I'll leave the decision up to you guys.

**Comment by Idain** [comment]
Are both the latest png.py and dpcomp algorith easily replaceable or do they need some extra adjustments to work with pokecrystal?

**Comment by Rangi42** [comment]
- current gfx.py algorithm: already written in Python, but compresses poorly
- lzss/mpcomp algorithm: relatively simple, especially without the matching-behavior flags, but needs translating from C
- dpcomp: more complicated, and needs translating from C, but gives best compression

**Comment by Idain** [comment]
Is compression a priority for the moment? Because in that case we could use mpcomp in the meantime. Also we can adapt the other Python scripts in a short time for Python 3 users.

**Comment by Rangi42** [comment]
Priority order:

1. Get palfix.py to work
2. Get gfx.py able to decompress 1/2bpp to PNG
3. Get gfx.py able to convert PNG to 1/2bpp (rgbgfx does this anyway)
4. Get gfx.py able to compress 1/2bpp to LZ (lzcomp does this anyway)
5. Make gfx.py's compression efficient

**Comment by Idain** [comment]
Fixing palfix.py is easy (changing `row.tostring()` to `row.tobytes()`), but the optimal approach would be to take the latest png.py and adapt it if necessary.
