### ISSUE TITLE
Don't use unistd.h or getopt.h in tools

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#883]
The getopt.h functions are useful for command-line parsing, but can be included cross-platform like rgbds does, with implementations ported from musl.

The [unistd.h functions](https://pubs.opengroup.org/onlinepubs/7908799/xsh/unistd.h.html#tag_000_010_276_007) are not available on Windows, and if possible we should avoid using them.

Ideally it would be possible to install [Git](https://gitforwindows.org), [rgbds](https://github.com/gbdev/rgbds/releases/tag/v0.5.2), [gcc](https://osdn.net/projects/mingw/), and [make](https://pakstech.com/blog/make-windows/) on Windows without WSL, Cygwin, or any other POSIX compatibility shim, and have `git clone https://github.com/pret/pokecrystal && cd pokecrystal && make` successfully build the ROM. (Note that our Makefile does rely on a couple of other non-Windows shell commands: `make compare` uses `sha1sum`, and `make clean` uses `find` and `rm`; but `make` alone should work.)

**Comment by aaaaaa123456789** [comment]
`sha1sum`  would be trivial to replace, but `find` and `rm` cannot be done in non-OS-specific ways, unfortunately.

**Comment by Rangi42** [comment]
For now I'm not truly concerned about supporting plain-Windows builds; but if we did, it has `certutil -hashfile pokecrystal.gbc SHA1` for that. And if the Makefile has a cross-platform way of detecting whether it's running on Windows (obviously not `uname`), it could conditionally do the cmd-style alternatives to `rm` (`del`) and `find` (I don't know).

**Comment by mid-kid** [comment]
-1. Writing makefiles without a unix shell/environment is absolute hell. Arguments and paths are all interpreted differently, and as mentioned above many useful utilities aren't available, preventing the creation and use of simple scripts over grabbing the big guns again with C (not to mention this proposes restricting C usage too!). I don't want to test for yet another annoying environment when modifying the makefile and I don't think there's much to be gained. There's no gcc toolchain that's shipped without a unix environment (the one linked above is both old and iirc mingw-get includes msys), and this would put us in a position where there's even less wiggling room in terms of using new tools to simplify the build process, as the user would have to install even more random binaries all in different ways/with different installers and package managers.

If we want a sanctioned build environment, cygwin's setup.exe has enough command-line flags to automatically build a portable environment that can be redistributed to users. Other than this I don't really see the point.

**Comment by Rangi42** [comment]
Turns out unistd.h wasn't used anyway. As for getopt.h, I see your point that it's not attempting to fully support Windows without a Unix-style shell.

**Comment by mid-kid** [comment]
Getopt.h is a minor issue, as a trivial strcmp() loop may be used to get good option parsing anyway. I'm just not sure going through the effort to support a full windows environment is worth it.
