### ISSUE TITLE
Improve the Virtual Console patch identification

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#886]
- [ ] Give the patches better `vc_hook`/`vc_patch` label names, and add comments in the asm briefly explaining what they're for.
- [ ] Don't hard-code the `wWindowStackPointer` values in `ConditionValueC`s.

**Comment by vulcandth** [comment]
I'm learning more about what the patches/hooks are doing now. I'll have some PR's open to address some of this soon.

Also; are we sure we want the comments on what a patch is for in the actual code, and not a wiki? Just want to verify before I go through the effort of doing a PR with comments in the code.

**Comment by Rangi42** [comment]
I do think comments have been appropriate so far, like for the Celebi hook. They don't need to go in-depth about the inner workings of each hook, only their effect on the game (like "prevents flashing" or "colors Jynx purple" or "makes link trading work over Wi-Fi"). A wiki article would be fine for deeper discussion if you've discovered that much info.

**Comment by Rangi42** [comment]
Noting something @vulcandth mentioned on Discord: `[linkCable fake begin]` needs a `vc_assert` that `hSerialConnectionStatus == $ffcb`.

**Comment by vulcandth** [comment]
> Noting something @vulcandth mentioned on Discord: `[linkCable fake begin]` needs a `vc_assert` that `hSerialConnectionStatus == $ffcb`.
This should be resolved when #906 merges.
