### ISSUE TITLE
pokecrystal fails to build on macOS

### ISSUE THREAD

**Issue by ISSOtm** [pret/pokecrystal#888]
`make compare` fails on macOS 10.15 and 11.0, just reported from our CI: https://github.com/gbdev/rgbds/runs/5527267454?check_suite_focus=true

Granted, this could be a problem on our side (we're only doing a sparse checkout), but given that it works on other OSes, I'm rather inclined to think the problem's with upstream. Will keep investigating, I'm not sure what the error is exactly.

**Comment by ISSOtm** [comment]
This commit https://github.com/ISSOtm/rgbds/commit/e219c06339dada358976f3dda5888b0b74f19c16 fixes the build (the failures on Windows are "patch does not apply", so I believe they can be overlooked).

I believe the reason for the breakage is a change in how the order of rules affect dependencies. Ah, Make. :)

**Comment by mid-kid** [comment]
Fixed in https://github.com/pret/pokecrystal/commit/a3e31d6463e6313aed12ebc733b3f772f2fc78d7
