### ISSUE TITLE
Add `vc_assert MOBILE_EVENT_OBJECT_GS_BALL == $B` for `vc_hook Enable_GS_Ball_mobile_event`

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#892]
This hook is hard-coded in the VC emulator to write $0b to $01:be3c and $01:be44. We assert that those locations are `sMobileEventIndex` and `sMobileEventIndexBackup`, but do not yet assert that the value is `MOBILE_EVENT_OBJECT_GS_BALL`.

**Comment by vulcandth** [comment]
I'll open a PR for this shortly, once I finish verification of another possible vc_assert requirement.
