### ISSUE TITLE
Create pull_request_template.md

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#903]
This can remind people to:

- Be sure that `make compare` prints `OK`, since we want to reproduce all the original ROMs
- Create a corresponding PR in pokegold for any shared changes
- Run tools/palfix.py on any new or modified PNGs to make sure they're consistently encoded and compressed
- Follow the STYLE.md guidelines, or more specifically, follow the style in context of what you're editing
- Anything else?

Same goes for pokegold, pokered, and pokeyellow.

**Comment by mid-kid** [comment]
> Be sure that make compare prints OK, since we want to reproduce all the original ROMs

That's what the CI is for, they'll find out sooner or later, and I honestly forget to compare before making a PR more often than not.

> Run tools/palfix.py on any new or modified PNGs to make sure they're consistently encoded and compressed

Are ours even compressed with that? This seems very situational, I can't recall the last time a PNG was added or modified, aside from the few recent palette fixes.

The rest is fine, but I can't think of much else.

**Comment by Rangi42** [comment]
Most of the PNGs were generated with the old gfx.py, which used png.py for output, and always used either 2-bit grayscale or 4-color indexed with a certain amount of compression and no metadata (e.g. gAMA or tEXt chunks).

Since then we've had a few commits to fix bloated PNGs which got in at some point. Before palfix.py existed we probably used pngcrush or something similar.

CI doesn't run for new contributors until someone in pret manually approves the job. I'm hoping to give people as many reminders up-front as possible so reviewers don't have to.

**Comment by mid-kid** [comment]
I wasn't aware of this. Travis ci used to be ran on PRs, so the github actions ci should be configured the same way

**Comment by Rangi42** [comment]
It is configured the same way. GitHub works like that to prevent bots from abusing CI resources to mine cryptocurrency or things like that.

**Comment by aaaaaa123456789** [comment]
I guess it might help to run `find -name "*.png" -exec pngcrush -ow -rem alla {} \;` every now and then...

**Comment by aaaaaa123456789** [comment]
I'd say, let's avoid the failures that the gen 3 repos already went through, having a complex issue/PR template that was more of a hindrance than an enabler for contributions. Keep it as simple as possible and reduce the administrative overhead to as close to zero as possible: you want to encourage contributions, not throw paperwork at volunteers.

In other words, keep the template as short as possible. Walls of text can be intimidating.

**Comment by Rangi42** [comment]
I guess a wiki article would be more appropriate. It has room for formatting, screenshots if necessary, sections for uncommon cases, etc.
