### ISSUE TITLE
Comment that some code depends on `farcall` returning the value of `c` in `a`

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#915]
See https://discord.com/channels/442462691542695948/487424856913346580/971165772632186980:

> `TryTileCollisionEvent` loads `wFacingTileID` into `c`, then `farcall`s `CheckFacingTileForStdScript`, which preserves `c`, but since it's a `farcall`, implicitly copies `c` back into `a` on return.  Then it calls `CheckCutTreeTile` which checks this value.  Notice how every other <code>Check<i>&lt;x&gt;</i>Tile</code> call in the same function explicitly loads `wFacingTileID` again.

**Comment by Idain** [comment]
Yeah, this can be easily documented in the code. Also, it's a funny oversight.
