### ISSUE TITLE
Some Labels have redundant comments

### ISSUE THREAD

**Issue by vulcandth** [pret/pokecrystal#916]
Example: 
[engine/battle/move_effects/attract.asm](https://github.com/pret/pokecrystal/blob/fbcc8d1b0e05cace2abe2083a88a8c2304efc9d7/engine/battle/move_effects/attract.asm#L1-L2)
```asm
BattleCommand_Attract:
; attract
```

These comments are redundant and old from (7-9 years ago) when I believe functions were still being identified, and I believe are no longer needed. I believe all of the move_effects/*.asm functions have these. I'm sure more exist throughout the repo.

Edit:
This Primarily appears to occur in `engine/battle/move_effects/*.asm`,  `engine/battle/effect_commands.asm`, and `engine/events/overworld.asm` based on preliminary regex searching.

**Comment by mid-kid** [comment]
The example you've given is because the command named `attract` is implemented there, and it's there for grep-searchability. If anything, we should consider doing this for every subsystem that uses commands whose names may be different compared to the labels that implement them.

**Comment by vulcandth** [comment]
> The example you've given is because the command named `attract` is implemented there, and it's there for grep-searchability. If anything, we should consider doing this for every subsystem that uses commands whose names may be different compared to the labels that implement them.

If the reason is because the "A" in `BattleCommand_Attract:` is capitalized, then that is kind of a dumb reason, in my opinion. If you want to grep on "attract"... then just grep -r -i attract .  or whatever similar ignore case flag.

**Comment by Rangi42** [comment]
I personally support getting rid of such comments. There's a clear relationship between `checkobedience` and `BattleCommand_CheckObedience`, just like `SLASH` and `SlashDescription`, `playsound` and `Script_playsound`, etc. The only time we usually have constant comments is when the names are not self-explanatory, like `dw StatusHealingEffect ; PSNCUREBERRY`, and then the comment is in the data table, not the definition of `StatusHealingEffect`.
