### ISSUE TITLE
Missing Tutorial

### ISSUE THREAD

**Issue by Ryuzac** [pret/pokecrystal#919]
The tutorial for adding [colored trainer card badges](https://github.com/pret/pokecrystal/wiki/Colored-trainer-card-badges) is a blank page despite being listed alongside the other complete tutorials.

**Comment by Rangi42** [comment]
The downside of anyone being able to edit the wiki (even if this was just a careless mistake). I'll restore it later.

**Comment by vulcandth** [comment]
@Ryuzac Until Rangi has time to restore it, you can access the most recent version of the page here: https://github.com/pret/pokecrystal/wiki/Colored-trainer-card-badges/57b5d82e4ecb33b185536e450aa1aee17d4cb817

**Comment by vulcandth** [comment]
@Rangi42 Thanks for restoring the page; This is a reminder that this issue may be closed now :).
