### ISSUE TITLE
Add night music tutorial issues

### ISSUE THREAD

**Issue by Ryuzac** [pret/pokecrystal#923]
The "[Add more music that changes at night](https://github.com/pret/pokecrystal/wiki/Add-more-music-that-changes-at-night)" tutorial has a few issues, including a section with (presumably) old code, and some misnamed songs in an external github.

Near the end of section 3 it says to change this code at around line 2228 in `home/map.asm`
```
.clearedradiotower
-       ld de, MUSIC_GOLDENROD_CITY
+	ld c, MUSIC_GOLDENROD_CITY
	jr .done
```

But in the current version of `home/map.asm` has this in the same area:
```
.clearedradiotower
	; the rest of the byte
	ld a, c
	and RADIO_TOWER_MUSIC - 1
	ld e, a
	ld d, 0
	jr .done
```

The surrounding code all matches up otherwise.

Further on in section 4 it instructs you to update the conversion table with a variety of songs included in an external github, but there seem to be issues with at least three of the songs in the table.
```
NightMusicTable:
night_music: MACRO
	db \1, \2
    ;\1 - original song
    ;\2 - night song
ENDM
    night_music MUSIC_NEW_BARK_TOWN,    MUSIC_NEW_BARK_TOWN_NIGHT
+   night_music MUSIC_ROUTE_29,         MUSIC_ROUTE_29_NIGHT
+   night_music MUSIC_CHERRYGROVE_CITY, MUSIC_CHERRYGROVE_CITY_NIGHT
+   night_music MUSIC_ROUTE_30,         MUSIC_ROUTE_30_NIGHT
+   night_music MUSIC_VIOLET_CITY,      MUSIC_VIOLET_CITY_NIGHT 
+   night_music MUSIC_AZALEA_TOWN,      MUSIC_AZALEA_TOWN_NIGHT
+   night_music MUSIC_ROUTE_32,         MUSIC_ROUTE_32_NIGHT
+   night_music MUSIC_GOLDENROD_CITY,   MUSIC_GOLDENROD_CITY_NIGHT
+   night_music MUSIC_ECRUTEAK_CITY,    MUSIC_ECRUTEAK_CITY_NIGHT
+   night_music MUSIC_ROUTE_38,         MUSIC_ROUTE_38_NIGHT
+   night_music MUSIC_LAKE_OF_RAGE,     MUSIC_LAKE_OF_RAGE_NIGHT
+   night_music MUSIC_ROUTE_26,         MUSIC_ROUTE_26_NIGHT
+   night_music MUSIC_VIRIDIAN_CITY,    MUSIC_VIRIDIAN_CITY_NIGHT
+   night_music MUSIC_ROUTE_3,          MUSIC_ROUTE_3_NIGHT
+   night_music MUSIC_ROUTE_12,         MUSIC_ROUTE_12_NIGHT
+   night_music MUSIC_CELADON_CITY,     MUSIC_CELADON_CITY_NIGHT
+   night_music MUSIC_VERMILION_CITY,   MUSIC_VERMILION_CITY_NIGHT
+   night_music MUSIC_PALLET_TOWN,      MUSIC_PALLET_TOWN_NIGHT
+   night_music MUSIC_ROUTE_1,          MUSIC_ROUTE_1_NIGHT
+   night_music MUSIC_LAVENDER_TOWN,    MUSIC_LAVENDER_TOWN_NIGHT
	db -1 ; end
```
The external github with the night versions of the tracks has no Lake of Rage track, but it does have a Route 34, Route 38, and Route 42 tracks, none of which are part of the disassembly. Route 42 could be a misnamed version of the missing Lake of Rage track with the wrong name (though I could be mistaken).

It's possible the Route 34 and Route 38 tracks are just misnamed as well, but I'm not familiar enough with the music to know what's what.

At the end in step's 7 and 8 `start_battle.asm:` should be `engine/battle/start_battle.asm:`

And finally in step 8 this code from `engine/battle/start_battle.asm` is missing part of what it told you to add in Step 7:
```
.kantowild
	;same comparison for Kanto - integrate in the other comparison?
	ld de, MUSIC_KANTO_WILD_BATTLE
	ld a, [wTimeOfDay]
	cp NITE_F
-       jr nz                                        ; In step 7 this line is: jr nz, .done
+       jr c, .done ; not NITE_F or EVE_F
	ld de, MUSIC_KANTO_WILD_BATTLE_NIGHT
	jr .done
```

**Comment by Ryuzac** [comment]
Hopefully this isn't overboard, figured I'd track stuff I came across while doing the tutorial.

**Comment by TriteHexagon** [comment]
It's true that this tutorial was written a while ago (although definitely not in 2018, more like 2020) so some code is likely to be outdated by now. However, I haven't actually looked at any code for a while so I'm not confident I can fix everything wrong with it without wasting a lot of time relearning everything. Feel free to edit the tutorial and fix outdated parts.

**Comment by vulcandth** [comment]
> It's true that this tutorial was written a while ago (although definitely not in 2018, more like 2020) so some code is likely to be outdated by now. However, I haven't actually looked at any code for a while so I'm not confident I can fix everything wrong with it without wasting a lot of time relearning everything. Feel free to edit the tutorial and fix outdated parts.

It's not so much that it's outdated, as that it looks like it was written for a rom-hack instead of the original roms. I also stated 2018 as the latest commit on your polishedcrystal fork was from [Mar 12, 2018](https://github.com/TriteHexagon/polishedcrystal/commit/ef0b132ed82aa4befa75cc7ad6a920d32f1e18e4). Which I assumed you must have used to get the code for the tutorial. At least that particular section I pointed out.

**Comment by TriteHexagon** [comment]
I never really worked on my own fork of polished crystal though, and really I should delete it... Anyway, I distinctly remember having a clean version of the base pokecrystal repo with _just_ these changes, and I followed my own tutorial without problems, but maybe some wires got crossed somewhere. I honestly don't remember. Either way, nothing I did here was super complicated, so it shouldn't be too hard to fix in the future, hopefully after pokecrystal decides to stop changing its code.

**Comment by TriteHexagon** [comment]
> The great part, is you explained a lot of what you were doing outside the actual code changes, which is super helpful.

My point with this tutorial (and others I've written) was to teach people how to understand the code instead of just regurgitating what I did. If there's any thing you need help with, don't hesitate in asking; I more or less know what the code is doing.

> Oh, I also wanted to thank you for your contributions and work. I love your GSC music additions you've put out.

Thank you, I appreciate it. I'll keep being involved with the community in that manner at least.

**Comment by coltongit** [comment]
Added a short sentence saying that particular design flaw fix should be implemented first before the tutorial this references, available at the most recent iteration of https://github.com/pret/pokecrystal/wiki/Add-more-music-that-changes-at-night as of the writing of this comment

**Comment by vulcandth** [comment]
>The external github with the night versions of the tracks has no Lake of Rage track, but it does have a Route 34, Route 38, and Route 42 tracks, none of which are part of the disassembly. Route 42 could be a misnamed version of the missing Lake of Rage track with the wrong name (though I could be mistaken).

>It's possible the Route 34 and Route 38 tracks are just misnamed as well, but I'm not familiar enough with the music to know what's what.

@TriteHexagon Since you maintain the `TriteHexagon/Trite_ASM_Repository/` repository. Was there ever a LAKE_OF_RAGE night track? If not, I can just simply remove the lines referencing it from Wiki Tutorial.

**Comment by vulcandth** [comment]
> The external github with the night versions of the tracks has no Lake of Rage track, but it does have a Route 34, Route 38, and Route 42 tracks, none of which are part of the disassembly. Route 42 could be a misnamed version of the missing Lake of Rage track with the wrong name (though I could be mistaken).
> 
> It's possible the Route 34 and Route 38 tracks are just misnamed as well, but I'm not familiar enough with the music to know what's what.

I have confirmed with TriteHexagon that the ROUTE_42 track is the same as LAKE_OF_RAGE. I'll double check on the others you mentioned.

**Comment by Ryuzac** [comment]
Awesome, thanks for the help with figuring those out!

**Comment by coltongit** [comment]
If these were fixed on that external github, then we can say this issue has been fixed

**Comment by Idain** [comment]
I took the freedom to edit the tutorial with your observations, so please check it out in case there's something else that needs to be fixed.

**Comment by coltongit** [comment]
@Ryuzac Does this version of the tutorial suit your needs now? Hopefully it's got the tutorial fixed now, if so you can close this issue

**Comment by Ryuzac** [comment]
My bad, I forgot to close it. Everything looks good, thanks for the help everyone!
