### ISSUE TITLE
How can i modify the AI behavior?

### ISSUE THREAD

**Issue by SDiCesare** [pret/pokecrystal#929]
Hi! Im trying to modify how the AI choose the move, and the idea is that the opponents pokemon could use a random move from the entire pool of moves, o qualcosa di simile.
Im trying to set the wCurEnemyMoveNum manually in the AIChooseMove function, but the game just ignores it and chooses by itself which move use.
Can someone explain how the battle/core.asm works and where the ai chooses the different moves (switch, item, moves, ecc..)?

Thanks.

**Comment by Rangi42** [comment]
These issues are for the developers of pokecrystal. You may get help on the Discord server linked in the README.

**Comment by SDiCesare** [comment]
Oh ok, sorry. Thanks for the advice!
