### ISSUE TITLE
Use issue/PR templates to keep issues and PRs relevant

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#930]
Here's an example: https://github.com/spacejam/sled/tree/main/.github/ISSUE_TEMPLATE

Clicking the New Issue button leads to a set of choices, including a Discord server link for questions that shouldn't be GitHub issues: https://github.com/spacejam/sled/issues/new/choose

**Comment by mid-kid** [comment]
I'm not sure how this will help people file better bug reports. We don't really have a universal way to format these issues, and we don't really get a high enough volume of issues to warrant standard procedures. The few issues we get are usually pretty good.

I don't think "rom bug/documentation" vs "repo issue" is a useful distinction when this entire repository is documentation. It would make no difference in the issue template anyway, these are simply labels, and we use those a bunch already (refactoring, renaming, tools, comments, bug docs). Something similar applies to "wiki issue": it's a label, not really a template for an issue to fill in.

Also despite the "build help" option, people will file build issues under repo issues anyway. If we do that then I'd suggest a similar deterrent for people trying to create pull requests for their own rom hacks.

**Comment by vulcandth** [comment]
Yes. I only came up with some labels so far.. (no actual templates) but the only reason this got brought up was due to people opening up irrelevant issues that could have simply been asked in discord. I'd also be happy only having two options.. one to create an issue.. and another explaining to go to discord for build/Romhack/questions. 

I don't want to deter people from making issues by making complicated issues templates. If you want templates, then they should be simple.

Will people still create issues for simple build issues that could have been asked in discord despite our issue template link? Yes. But perhaps it would happen less often. And users will be directed to a better place to get help.

**Comment by coltongit** [comment]
I for one would be game for having an issue template system in place here similar to the one in pokeemerald

**Comment by coltongit** [comment]
```
<!--- Provide a general summary of the issue in the Title above -->

## Description
<!--- Describe the issue in detail -->

## **Discord contact info**
<!--- formatted as name#numbers, e.g. PikalaxALT#5823 -->
<!--- Contributors must join https://discord.gg/d5dubZ3 -->
```

This would be a good format for an issue template, not just in pokecrystal, across all pret repos as well

**Comment by mid-kid** [comment]
I disagree with discord contact info being a requirement here. Github serves discussions just fine and is generally better for long-term archival of conversations, where they'd be lost in a sea of crap on discord.

**Comment by coltongit** [comment]
> I disagree with discord contact info being a requirement here. Github serves discussions just fine and is generally better for long-term archival of conversations, where they'd be lost in a sea of crap on discord.

That would mean also removing it from pull request templates
Meaning it's fine without that section in there?

**Comment by coltongit** [comment]
Would the above be any better for the issue template here and on other pret repos?

**Comment by vulcandth** [comment]
We don't really need actual templates. We prolly just want to abuse the github template system to have it pop up two options when a user goes to create an issue. One option to create an issue with a blank template...  And the other is a link to the discord for Romhack help, non-issue questions, ect.

**Comment by coltongit** [comment]
Which is also a perfectly valid way to do it, I'm game with that as well

**Comment by vulcandth** [comment]
I put together a `Pret-Test-Issue-Templates` repo. Check out https://github.com/vulcandth/Pret-Test-Issue-Templates/issues/new/choose

Feel like we should just keep it as simple as possible. Let me know what you think.. or if you want to permissions to play around with it.

@Rangi42 @mid-kid 

Going to tag @dannye as well; in case we want to do this for pokered/pokeyellow too.

**Comment by mid-kid** [comment]
I'm always iffy about only linking the discord (without linking the IRC too, at least), but this template looks fine. I'm not entirely convinced we need it, but it doesn't really hurt either.

**Comment by mid-kid** [comment]
I was mostly thinking of an "I want to improve the disassembly" and an "I want to modify the game".

**Comment by vulcandth** [comment]
> requesting pull request template to deter people from making a pull request upstream. Simply two options, one that says: "Improve pret/pokecrystal", the other being a link to how to fork a github repo and make a pull request there, or "clone" the repo without making it a direct fork.

This sounds good and I agree. 

>Didn't we have a tutorial page for this?

I didn't see one; but if we don't... I believe it would be worth the effort to write one. Something like [this](https://yangsu.github.io/pull-request-tutorial/) could be helpful for writing something like this... would just need to add in information about how to create forks or clone your own repo.. ect.

**Comment by vulcandth** [comment]
Alright the Issue templates have been implemented. I'm leaving this Issue open to enable discussion on possible PR templates. Those may get implemented whenever we come to a consensus on what we want to do for them. 👍

**Comment by vulcandth** [comment]
Slight consequence of adding these Issue Templates.. New Forks will also clone the templates. So when issues are created on downstream forks, they are presented with the same options as upstream pokecrystal. Now I don't see this being a big issue for the issue templates we implemented... I do feel like the pull request templates could be confusing if the options are:
>I was mostly thinking of an "I want to improve the disassembly" and an "I want to modify the game"-kinda choice.

As if a downstream user is trying to create a PR to say... merge one of their branches to their main branch... The first option "I want to improve the disassembly" would allow them to create their PR.. and the second option "I want to modify the game" would send them to a tutorial on how to fork/clone a repo ect.... which they would have already done. This might be confusing for downstream users who don't know how github works, and that they'd need to delete the templates from their downstream repos.

**Comment by mid-kid** [comment]
That's fair, nevermind then.
