### ISSUE TITLE
Pokémon animation frame banks are derived from their species IDs

### ISSUE THREAD

**Issue by coltongit** [pret/pokecrystal#938]
Design flaw that seems to have slipped through `design_flaws.md`
Was fixed in https://github.com/aaaaaa123456789/pokecrystal16/commit/53301875a9d2ca049e0d2a4b5d1d3523d7260d0a and could possibly be used in there just like the Pokédex entry fix in the same file.

**Comment by Rangi42** [comment]
This is not a design flaw. Animation frame and bitmask data is small enough that for 8-bit species, the current approach is more efficient (bitmasks in one bank, frames in two split by the mon ID, the same approach that's recommended for having [unique icons per mon](https://github.com/pret/pokecrystal/wiki/Add-a-new-party-menu-icon#5-how-to-add-a-unique-icon-for-each-pok%C3%A9mon)).

Once you start expanding data far beyond the original game limits, there are many `dw` tables that could become `dba`, such as trainer parties, item effects, etc.
