### ISSUE TITLE
Gym leader visual displays through its badge on the trainer card

### ISSUE THREAD

**Issue by DamienDoury** [pret/pokecrystal#945]
https://discord.com/channels/442462691542695948/986439308766478356/986607876120399902

There is an oversight in vanilla Pokémon Crystal: the badge sprite uses the white color (index 0), which is transparent as it is a sprite.
As it animates while overlapping its gym leader's head (background), you can see the gym leader's hair through the badge at a specific frame.
The one you can see the most is Falkner's hair.
![image](https://user-images.githubusercontent.com/3067727/173864298-8b6eb3bc-62a4-4bb8-8628-6ca23222a221.png)

**Comment by Rangi42** [comment]
Yeah, that's just how it is. If you think using the light color instead of white color would look better (flatter shading, but it wouldn't be transparent), you can change that.
