### ISSUE TITLE
Remove non-existent rNR20 and rNR40 hardware register constants

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#946]
As described in the [Pan Docs](https://gbdev.io/pandocs/Sound_Controller.html), channels 2 and 4 do not have a Tone Envelope/Sweep Register. However, pokecrystal and pokegold define `rNR20` and `rNR40` constants, not because those registers are directly used, but just as offsets to pass to `ClearChannel`, which expects `hl` to point to some rNRx0-1-2-3-4 series of registers. We should use `rNR21 - 1` and `rNR41 - 1` with appropriate comments (even just `; there is no rNR20`).

**Comment by coltongit** [comment]
This change has been applied on both pokegold and pokecrystal through PRs. They also identify two previously unknown constants thanks to `hardware.inc`.
