### ISSUE TITLE
Rename some numbered engine files

### ISSUE THREAD

**Issue by vulcandth** [pret/pokecrystal#951]
Some of these files could have better names, as mentioned by @Rangi42 in discord https://discord.com/channels/442462691542695948/487424856913346580/988135717182001182

If you have suggestions, please provide them here.

- [x] engine/pokemon/search.asm => engine/pokemon/search_owned.asm a1498e63e27d651ef85fdfc7bcc255d67fb04d57
- [x] engine/pokemon/search2.asm => engine/pokemon/search_party.asm a1498e63e27d651ef85fdfc7bcc255d67fb04d57
- [ ] engine/events/bug_contest/contest.asm
- [ ] engine/events/bug_contest/contest_2.asm
- [ ] engine/events/print_unown.asm
- [ ] engine/events/print_unown_2.asm
- [ ] engine/items/tmhm.asm
- [ ] engine/items/tmhm2.asm
- [ ] engine/link/link.asm
- [ ] engine/link/link_2.asm
- [ ] engine/link/mystery_gift.asm
- [ ] engine/link/myster_gift_2.asm
- [ ] engine/link/time_capsule.asm
- [ ] engine/link/time_capsule_2.asm
- [ ] engine/menus/menu.asm
- [ ] engine/menus/menu_2.asm
- [ ] engine/overworld/map_objects.asm
- [ ] engine/overworld/map_objects_2.asm
- [ ] engine/phone/scripts/hangups.asm
- [ ] engine/phone/scripts/hangups_2.asm
- [ ] engine/phone/scripts/reminders.asm
- [ ] engine/phone/scripts/reminders_2.asm
- [ ] engine/pokedex/pokedex.asm
- [ ] engine/pokedex/pokedex_2.asm
- [ ] engine/pokedex/pokedex_3.asm
- [ ] engine/pokemon/mail.asm
- [ ] engine/pokemon/mail_2.asm

**Comment by coltongit** [comment]
Literally all of the numbered files in `mobile/` need better function names and names in general as well

**Comment by coltongit** [comment]
mobile/mobile_12.asm
mobile/mobile_12_2.asm
mobile/mobile_22.asm
mobile/mobile_22_2.asm
mobile/mobile_40.asm
mobile/mobile_41.asm
mobile/mobile_42.asm
mobile/mobile_45.asm
mobile/mobile_45_2.asm
mobile/mobile_45_sprite_engine.asm
mobile/mobile_45_stadium.asm
mobile/mobile_46.asm
mobile/mobile_5b.asm
mobile/mobile_5c.asm
mobile/mobile_5e.asm
mobile/mobile_5f.asm

**Comment by vulcandth** [comment]
> Literally all of the numbered files in `mobile/` need better function names and names in general as well

Since the `mobile/` code is not well understood and hasn't been fully identified; Renaming those files will have to be done after their functions have been labeled and their purpose identified. That will be outside the scope of this issue.

**Comment by coltongit** [comment]
> > Literally all of the numbered files in `mobile/` need better function names and names in general as well
> 
> Since the `mobile/` code is not well understood and hasn't been fully identified; Renaming those files will have to be done after their functions have been labeled and their purpose identified. That will be outside the scope of this issue.

another issue may need to be opened up for that, will do

**Comment by coltongit** [comment]
The discussion surrounding obile code and the names of mobile-related files has been moved to #952

**Comment by vulcandth** [comment]
https://discord.com/channels/442462691542695948/487424856913346580/988240885114343424
