### ISSUE TITLE
Keep rgbdscheck.asm as backwards-compatible as possible

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#966]
Currently rgbds 0.5.2 prefers `DEF` syntax for constants, and will probably deprecate the non-`DEF` first-column syntax eventually. But until then, it's useful to have the old syntax in `rgbdscheck.asm` to give a sensible error message for as many old rgbds versions as possible.

**Comment by coltongit** [comment]
Should there only be the old syntax in there or can both syntaxes coexist as to prevent future errors?
