### ISSUE TITLE
INSTALL.md has dead link

### ISSUE THREAD

**Issue by wolfboyft** [pret/pokecrystal#967]
`Then follow the [rgbds instructions](https://rgbds.gbdev.io/install/windows) for Windows with Cygwin to install rgbds 0.5.2.`

https://rgbds.gbdev.io/install/windows is a dead link

**Comment by coltongit** [comment]
All dead links have been fixed in the README.md from #968

**Comment by wolfboyft** [comment]
Nice, guess I should've check the PRs
