### ISSUE TITLE
Pocket PC from the tutorials doesn't open 

### ISSUE THREAD

**Issue by KantaroFR** [pret/pokecrystal#973]
Hello everyone and sorry for my English.

I am trying to add a Pocket PC to Pokemon Crystal, following the instructions from this page :

https://github.com/pret/pokecrystal/wiki/How-To-Add-a-Pocket-PC

After compilation, I got the Pocket PC from the Elm's Aide, but when I try to open it, I always get the Oak's message saying that "It"s not the time to use that !"
I always have the same problem, whenever I am in a city, on a road, or inside a house, and the problem is the same if I use the select button instead of going in the key items menu.

Does anyone knows of to fix that ?

Thanks in advance.

**Comment by Rangi42** [comment]
GitHub issues are for fixing or improving pokecrystal itself. For help with using pokecrystal, please ask in the [Discord server](https://discord.gg/d5dubZ3).
