### ISSUE TITLE
Define scene constants alongside their `scene_script` pointers

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#978]
Right now we have constants/scene_constants.asm, which defines constants for each map that have to correlate to the map's scene IDs.

https://github.com/pret/pokered/pull/367/files is introducing a `dw_const` macro to pokered that will simultaneously declare a pointer and define a corresponding constant. It's particularly useful in Gen 1 because there were tables of text and script pointers, and bg and object events referred directly to them.

pokecrystal could do the same:

```diff
 AzaleaTown_MapScripts:
 	def_scene_scripts
-	scene_script .DummyScene0 ; SCENE_AZALEATOWN_NOTHING
-	scene_script .DummyScene1 ; SCENE_AZALEATOWN_RIVAL_BATTLE
-	scene_script .DummyScene2 ; SCENE_AZALEATOWN_KURT_RETURNS_GS_BALL
+	scene_script .DummyScene0, SCENE_AZALEATOWN_NOTHING
+	scene_script .DummyScene1, SCENE_AZALEATOWN_RIVAL_BATTLE
+	scene_script .DummyScene2, SCENE_AZALEATOWN_KURT_RETURNS_GS_BALL
```

The advantages are not having to edit two files, related data being kept together, and symmetry with pokered.

The disadvantage is that many `scene_script`s are just dummies, because the scene ID is meant for a `coord_event` instead. Furthermore, although Game Freak defined a `scene_script` for every valid scene ID, you don't actually have to. None of those Azalea Town `scene_script`s need to exist because they're all for `coord_event`s. So editing the macro this way would either force people to define dummy `scene_script`s, or we'd need to complicate the macro to allow defining only a constant.

Alternatively, we could do the same thing as `object_const_def`, and define a sequence of scene IDs in each map file. This would hopefully not be confusing when a different map uses the constant, as in `setmapscene AZALEA_TOWN, SCENE_AZALEATOWN_RIVAL_BATTLE`.

**Comment by mid-kid** [comment]
With endeavors like these I'd always request that the possibility for splitting separate map scripts into separate translation units be kept in mind. Make sure the values can be EXPORTed, so avoid EQUS and similar constructs that require a specific order of file inclusion.

The proposed `dw_const` solution sounds good, I believe we've already been doing it for some tables across the code, and while I'm personally not too keen on having to look someplace other than constants/ for cross-file definitions, in this case it makes more than enough sense.

**Comment by Rangi42** [comment]
`dw_const` or `scene_script` could both handle exporting the constants.

We have't yet added any `dw_const` macro; I had just proposed it in #748 for the various jumptables throughout the engine.

**Comment by vulcandth** [comment]
For consistency I like `dw_const`; as it has since grown on me.

Although I am okay with complicating the macro a little to allow either an optional argument... or accepting a true "dummy" argument that simply ignores the `dw`.

Alternatively, If you didn't want to define a dummy scene script, you could also simply do something like this:

```asm
BrunosRoom_MapScripts:
	def_scene_scripts
	dw_const .LockDoor, SCENE_BRUNOSROOM_DEFAULT
	const               SCENE_BRUNOSROOM_FINISHED
```

**Comment by Rangi42** [comment]
`scene_script` is more than just a `dw`, so it will stay.

```
MACRO scene_script
;\1: script pointer
	dw \1
	dw 0 ; filler
	DEF {_NUM_SCENE_SCRIPTS} += 1
ENDM
```

**Comment by mid-kid** [comment]
Another place in the code that could use defining constants along with the pointers is the sprite anim subsystem, having to go back and forth between the constants and the tables to add entries is a major pain.
