### ISSUE TITLE
`object_struct` wram labels should match their offset constants

### ISSUE THREAD

**Issue by vulcandth** [pret/pokecrystal#990]
Currently the wram labels for the `object_struct` have things such as:

```
\1StandingMapX::      db
\1StandingMapY::      db
\1LastMapX::          db
\1LastMapY::          db
```

However the offset constants use:

```
DEF OBJECT_NEXT_MAP_X          rb ; 10
DEF OBJECT_NEXT_MAP_Y          rb ; 11
DEF OBJECT_MAP_X               rb ; 12
DEF OBJECT_MAP_Y               rb ; 13
```

In the above examples, the wram labels should be renamed to match the offset constants. There are a few others here than need addressed.

Also we should investigate the true purpose of the following, and come up with better names for these:

```
DEF OBJECT_1C                  rb ; 1c
DEF OBJECT_1D                  rb ; 1d
DEF OBJECT_1E                  rb ; 1e
DEF OBJECT_1F                  rb ; 1f
```

**Comment by Rangi42** [comment]
Right now `OBJECT_DIRECTION_WALKING` is for `\1Walking` and `OBJECT_FACING` is for `\1Direction`. We should rename them to `OBJECT_WALKING` and `OBJECT_DIRECTION`, assuming the labels are what's most accurate.
