### ISSUE TITLE
Macros to verify trainer parties

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#992]
Concept: begin each party with `def_trainer`, and end them with `end_trainer`, which will declare the `db -1` terminator and assert that the total party size corresponds to the `TRAINERTYPE`.

```
MACRO def_trainer
	db \1, \2 ; name, type
	DEF CURRENT_TRAINER_MON_SIZE = \
		2 * ((\2) == TRAINERTYPE_NORMAL) + \
		6 * ((\2) == TRAINERTYPE_MOVES) + \
		3 * ((\2) == TRAINERTYPE_ITEM) + \
		7 * ((\2) == TRAINERTYPE_ITEM_MOVES)
	REDEF CURRENT_TRAINER_LABEL EQUS "._def_trainer_\@"
{CURRENT_TRAINER_LABEL}:
ENDM

MACRO end_trainer
	assert (@ - {CURRENT_TRAINER_LABEL}) % CURRENT_TRAINER_MON_SIZE == 0, \
		"def_trainer: expected {d:CURRENT_TRAINER_MON_SIZE} bytes per Pokémon"
	db -1 ; end
ENDM

OfficerGroup:
	; OFFICER (1)
	def_trainer "KEITH@", TRAINERTYPE_NORMAL
	db 17, GROWLITHE
	end_trainer

	; OFFICER (2)
	def_trainer "DIRK@", TRAINERTYPE_NORMAL
	db 14, GROWLITHE
	db 14, GROWLITHE
	end_trainer
```

**Comment by vulcandth** [comment]
Can we add an additional end\_trainer assert? Something like...

```
assert (@ - {CURRENT_TRAINER_LABEL}) / CURRENT_TRAINER_MON_SIZE > 0 && \
	(@ - {CURRENT_TRAINER_LABEL}) / CURRENT_TRAINER_MON_SIZE < PARTY_LENGTH, \
	"def_trainer: expected number of pokemon to be > 0 or <= {d:PARTY_LENGTH}"
```

**Comment by Rangi42** [comment]
See the discussion in #pokecrystal with @mid-kid about that.

**Comment by mid-kid** [comment]
LGTM

**Comment by Rangi42** [comment]
@aaaaaa123456789 pointed out that this could still have false negatives. This has six bytes of party data, which is enough for one mon with `MOVES`, but is actually three `NORMAL` mons:

```
	def_trainer "KEITH@", TRAINERTYPE_MOVES
	db 17, GROWLITHE
	db 18, GROWLITHE
	db 19, GROWLITHE
	end_trainer
```

**Comment by mid-kid** [comment]
I don't want to macroize the entire thing I don't want to macroize the entire thing I don't want to macroize the entire thing aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by Rangi42** [comment]
Yeah, if it were a simple `def_X`/`end_X` macro pair like the rest I'd do it, but it's not.
